// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access_tokens.query.sql

package sqlc

import (
	"context"
)

const getAccessTokenByToken = `-- name: GetAccessTokenByToken :one
SELECT token, user_id, expires_at, revoked_at, created_at
FROM access_tokens
WHERE token = $1
`

func (q *Queries) GetAccessTokenByToken(ctx context.Context, token string) (AccessToken, error) {
	row := q.db.QueryRow(ctx, getAccessTokenByToken, token)
	var i AccessToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}
