// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: frequencies.query.sql

package sqlc

import (
	"context"
)

const listTaskFrequencies = `-- name: ListTaskFrequencies :many
SELECT frequency, label, label_jp, created_at, updated_at
FROM frequency_master
`

func (q *Queries) ListTaskFrequencies(ctx context.Context) ([]FrequencyMaster, error) {
	rows, err := q.db.Query(ctx, listTaskFrequencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FrequencyMaster
	for rows.Next() {
		var i FrequencyMaster
		if err := rows.Scan(
			&i.Frequency,
			&i.Label,
			&i.LabelJp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
