// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProject = `-- name: GetProject :one
SELECT id, user_id, type, title, goal, description, progress, priority, start_at, end_at, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Goal,
		&i.Description,
		&i.Progress,
		&i.Priority,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByUser = `-- name: GetProjectByUser :one
SELECT id, user_id, type, title, goal, description, progress, priority, start_at, end_at, created_at, updated_at
FROM projects
WHERE id = $1
  AND user_id = $2
`

type GetProjectByUserParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetProjectByUser(ctx context.Context, arg GetProjectByUserParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByUser, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Goal,
		&i.Description,
		&i.Progress,
		&i.Priority,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectTasksByUser = `-- name: ListProjectTasksByUser :many
SELECT id, user_id, project_id, title, description, estimated_minutes, actual_minutes, progress,
       priority, status, created_at, updated_at
FROM tasks
WHERE project_id = $1
  AND user_id = $2
ORDER BY created_at ASC
`

type ListProjectTasksByUserParams struct {
	ProjectID pgtype.Text
	UserID    string
}

func (q *Queries) ListProjectTasksByUser(ctx context.Context, arg ListProjectTasksByUserParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listProjectTasksByUser, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Progress,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
