// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_schedules.mut.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTaskScheduleFrequency = `-- name: AddTaskScheduleFrequency :exec
INSERT INTO task_schedule_frequencies (task_schedule_id, frequency)
VALUES ($1, $2)
`

type AddTaskScheduleFrequencyParams struct {
	TaskScheduleID string
	Frequency      string
}

func (q *Queries) AddTaskScheduleFrequency(ctx context.Context, arg AddTaskScheduleFrequencyParams) error {
	_, err := q.db.Exec(ctx, addTaskScheduleFrequency, arg.TaskScheduleID, arg.Frequency)
	return err
}

const createTaskSchedule = `-- name: CreateTaskSchedule :one
INSERT INTO task_schedules (id, task_id, title, description, location, interval_weeks, start_at, end_at, due_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, task_id, title, description, location, interval_weeks, start_at, end_at, due_at, created_at, updated_at
`

type CreateTaskScheduleParams struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	Location      pgtype.Text
	IntervalWeeks int32
	StartAt       pgtype.Timestamptz
	EndAt         pgtype.Timestamptz
	DueAt         pgtype.Timestamptz
}

func (q *Queries) CreateTaskSchedule(ctx context.Context, arg CreateTaskScheduleParams) (TaskSchedule, error) {
	row := q.db.QueryRow(ctx, createTaskSchedule,
		arg.ID,
		arg.TaskID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.IntervalWeeks,
		arg.StartAt,
		arg.EndAt,
		arg.DueAt,
	)
	var i TaskSchedule
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.IntervalWeeks,
		&i.StartAt,
		&i.EndAt,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTaskScheduleByTaskAndUser = `-- name: CreateTaskScheduleByTaskAndUser :one
WITH inserted AS (
    INSERT INTO task_schedules (id, task_id, title, description, location, interval_weeks, start_at, end_at, due_at)
    SELECT
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9
    FROM tasks AS t
    WHERE t.id = $2
      AND t.user_id = $10
    RETURNING id, task_id, title, description, location, interval_weeks, start_at, end_at, due_at, created_at, updated_at
),
inserted_frequencies AS (
    INSERT INTO task_schedule_frequencies (task_schedule_id, frequency)
    SELECT inserted.id, unnest($11::text[])
    FROM inserted
    ON CONFLICT DO NOTHING
)
SELECT
    inserted.id,
    inserted.task_id,
    inserted.title,
    inserted.description,
    inserted.location,
    inserted.interval_weeks,
    ARRAY(
        SELECT tsf.frequency
        FROM task_schedule_frequencies AS tsf
        WHERE tsf.task_schedule_id = inserted.id
        ORDER BY tsf.frequency
    )::text[] AS frequencies,
    inserted.start_at,
    inserted.end_at,
    inserted.due_at,
    inserted.created_at,
    inserted.updated_at
FROM inserted
`

type CreateTaskScheduleByTaskAndUserParams struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	Location      pgtype.Text
	IntervalWeeks int32
	StartAt       pgtype.Timestamptz
	EndAt         pgtype.Timestamptz
	DueAt         pgtype.Timestamptz
	UserID        string
	Frequencies   []string
}

type CreateTaskScheduleByTaskAndUserRow struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	Location      pgtype.Text
	IntervalWeeks int32
	Frequencies   []string
	StartAt       pgtype.Timestamptz
	EndAt         pgtype.Timestamptz
	DueAt         pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateTaskScheduleByTaskAndUser(ctx context.Context, arg CreateTaskScheduleByTaskAndUserParams) (CreateTaskScheduleByTaskAndUserRow, error) {
	row := q.db.QueryRow(ctx, createTaskScheduleByTaskAndUser,
		arg.ID,
		arg.TaskID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.IntervalWeeks,
		arg.StartAt,
		arg.EndAt,
		arg.DueAt,
		arg.UserID,
		arg.Frequencies,
	)
	var i CreateTaskScheduleByTaskAndUserRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.IntervalWeeks,
		&i.Frequencies,
		&i.StartAt,
		&i.EndAt,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTaskSchedule = `-- name: DeleteTaskSchedule :exec
DELETE FROM task_schedules
WHERE id = $1
`

func (q *Queries) DeleteTaskSchedule(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTaskSchedule, id)
	return err
}

const deleteTaskScheduleByTaskAndUser = `-- name: DeleteTaskScheduleByTaskAndUser :one
DELETE FROM task_schedules AS ts
USING tasks AS t
WHERE ts.id = $1
  AND ts.task_id = $2
  AND t.id = ts.task_id
  AND t.user_id = $3
RETURNING ts.id
`

type DeleteTaskScheduleByTaskAndUserParams struct {
	ID     string
	TaskID string
	UserID string
}

func (q *Queries) DeleteTaskScheduleByTaskAndUser(ctx context.Context, arg DeleteTaskScheduleByTaskAndUserParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteTaskScheduleByTaskAndUser, arg.ID, arg.TaskID, arg.UserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteTaskScheduleFrequencies = `-- name: DeleteTaskScheduleFrequencies :exec
DELETE FROM task_schedule_frequencies
WHERE task_schedule_id = $1
`

func (q *Queries) DeleteTaskScheduleFrequencies(ctx context.Context, taskScheduleID string) error {
	_, err := q.db.Exec(ctx, deleteTaskScheduleFrequencies, taskScheduleID)
	return err
}

const updateTaskSchedule = `-- name: UpdateTaskSchedule :one
UPDATE task_schedules
SET task_id = $2,
    title = $3,
    description = $4,
    location = $5,
    interval_weeks = $6,
    start_at = $7,
    end_at = $8,
    due_at = $9,
    updated_at = now()
WHERE id = $1
RETURNING id, task_id, title, description, location, interval_weeks, start_at, end_at, due_at, created_at, updated_at
`

type UpdateTaskScheduleParams struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	Location      pgtype.Text
	IntervalWeeks int32
	StartAt       pgtype.Timestamptz
	EndAt         pgtype.Timestamptz
	DueAt         pgtype.Timestamptz
}

func (q *Queries) UpdateTaskSchedule(ctx context.Context, arg UpdateTaskScheduleParams) (TaskSchedule, error) {
	row := q.db.QueryRow(ctx, updateTaskSchedule,
		arg.ID,
		arg.TaskID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.IntervalWeeks,
		arg.StartAt,
		arg.EndAt,
		arg.DueAt,
	)
	var i TaskSchedule
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.IntervalWeeks,
		&i.StartAt,
		&i.EndAt,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskScheduleByTaskAndUser = `-- name: UpdateTaskScheduleByTaskAndUser :one
WITH updated AS (
    UPDATE task_schedules AS ts
    SET title = $1,
        description = $2,
        location = $3,
        interval_weeks = $4,
        start_at = $5,
        end_at = $6,
        due_at = $7,
        updated_at = now()
    FROM tasks AS t
    WHERE ts.id = $8
      AND ts.task_id = $9
      AND t.id = ts.task_id
      AND t.user_id = $10
    RETURNING ts.id, ts.task_id, ts.title, ts.description, ts.location, ts.interval_weeks, ts.start_at, ts.end_at, ts.due_at, ts.created_at, ts.updated_at
),
deleted_frequencies AS (
    DELETE FROM task_schedule_frequencies AS tsf
    USING updated
    WHERE tsf.task_schedule_id = updated.id
    RETURNING tsf.task_schedule_id
),
inserted_frequencies AS (
    INSERT INTO task_schedule_frequencies (task_schedule_id, frequency)
    SELECT updated.id, unnest($11::text[])
    FROM updated
    LEFT JOIN (SELECT count(*) AS deleted_count FROM deleted_frequencies) AS deleted ON true
    ON CONFLICT DO NOTHING
)
SELECT
    updated.id,
    updated.task_id,
    updated.title,
    updated.description,
    updated.location,
    updated.interval_weeks,
    ARRAY(
        SELECT tsf.frequency
        FROM task_schedule_frequencies AS tsf
        WHERE tsf.task_schedule_id = updated.id
        ORDER BY tsf.frequency
    )::text[] AS frequencies,
    updated.start_at,
    updated.end_at,
    updated.due_at,
    updated.created_at,
    updated.updated_at
FROM updated
`

type UpdateTaskScheduleByTaskAndUserParams struct {
	Title         string
	Description   pgtype.Text
	Location      pgtype.Text
	IntervalWeeks int32
	StartAt       pgtype.Timestamptz
	EndAt         pgtype.Timestamptz
	DueAt         pgtype.Timestamptz
	ID            string
	TaskID        string
	UserID        string
	Frequencies   []string
}

type UpdateTaskScheduleByTaskAndUserRow struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	Location      pgtype.Text
	IntervalWeeks int32
	Frequencies   []string
	StartAt       pgtype.Timestamptz
	EndAt         pgtype.Timestamptz
	DueAt         pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) UpdateTaskScheduleByTaskAndUser(ctx context.Context, arg UpdateTaskScheduleByTaskAndUserParams) (UpdateTaskScheduleByTaskAndUserRow, error) {
	row := q.db.QueryRow(ctx, updateTaskScheduleByTaskAndUser,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.IntervalWeeks,
		arg.StartAt,
		arg.EndAt,
		arg.DueAt,
		arg.ID,
		arg.TaskID,
		arg.UserID,
		arg.Frequencies,
	)
	var i UpdateTaskScheduleByTaskAndUserRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.IntervalWeeks,
		&i.Frequencies,
		&i.StartAt,
		&i.EndAt,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
