// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_status.sql

package sqlc

import (
	"context"
)

const listTaskStatuses = `-- name: ListTaskStatuses :many
SELECT status, label, label_jp, created_at, updated_at
FROM task_status_master
`

func (q *Queries) ListTaskStatuses(ctx context.Context) ([]TaskStatusMaster, error) {
	rows, err := q.db.Query(ctx, listTaskStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskStatusMaster
	for rows.Next() {
		var i TaskStatusMaster
		if err := rows.Scan(
			&i.Status,
			&i.Label,
			&i.LabelJp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
