// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_schedules.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTaskSchedule = `-- name: CreateTaskSchedule :one
INSERT INTO task_schedules (id, task_id, title, description, location, interval_weeks, start_at, end_at, due_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, task_id, title, description, location, interval_weeks, start_at, end_at, due_at, created_at, updated_at
`

type CreateTaskScheduleParams struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	Location      pgtype.Text
	IntervalWeeks int32
	StartAt       pgtype.Timestamptz
	EndAt         pgtype.Timestamptz
	DueAt         pgtype.Timestamptz
}

func (q *Queries) CreateTaskSchedule(ctx context.Context, arg CreateTaskScheduleParams) (TaskSchedule, error) {
	row := q.db.QueryRow(ctx, createTaskSchedule,
		arg.ID,
		arg.TaskID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.IntervalWeeks,
		arg.StartAt,
		arg.EndAt,
		arg.DueAt,
	)
	var i TaskSchedule
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.IntervalWeeks,
		&i.StartAt,
		&i.EndAt,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTaskSchedule = `-- name: DeleteTaskSchedule :exec
DELETE FROM task_schedules
WHERE id = $1
`

func (q *Queries) DeleteTaskSchedule(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTaskSchedule, id)
	return err
}

const getTaskSchedule = `-- name: GetTaskSchedule :one
SELECT id, task_id, title, description, location, interval_weeks, start_at, end_at, due_at, created_at, updated_at
FROM task_schedules
WHERE id = $1
`

func (q *Queries) GetTaskSchedule(ctx context.Context, id string) (TaskSchedule, error) {
	row := q.db.QueryRow(ctx, getTaskSchedule, id)
	var i TaskSchedule
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.IntervalWeeks,
		&i.StartAt,
		&i.EndAt,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskSchedule = `-- name: UpdateTaskSchedule :one
UPDATE task_schedules
SET task_id = $2,
    title = $3,
    description = $4,
    location = $5,
    interval_weeks = $6,
    start_at = $7,
    end_at = $8,
    due_at = $9,
    updated_at = now()
WHERE id = $1
RETURNING id, task_id, title, description, location, interval_weeks, start_at, end_at, due_at, created_at, updated_at
`

type UpdateTaskScheduleParams struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	Location      pgtype.Text
	IntervalWeeks int32
	StartAt       pgtype.Timestamptz
	EndAt         pgtype.Timestamptz
	DueAt         pgtype.Timestamptz
}

func (q *Queries) UpdateTaskSchedule(ctx context.Context, arg UpdateTaskScheduleParams) (TaskSchedule, error) {
	row := q.db.QueryRow(ctx, updateTaskSchedule,
		arg.ID,
		arg.TaskID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.IntervalWeeks,
		arg.StartAt,
		arg.EndAt,
		arg.DueAt,
	)
	var i TaskSchedule
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.IntervalWeeks,
		&i.StartAt,
		&i.EndAt,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
