// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTask = `-- name: GetTask :one
SELECT id, user_id, project_id, title, description, due_date, estimated_minutes, actual_minutes, progress,
       priority, status, created_at, updated_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.DueDate,
		&i.EstimatedMinutes,
		&i.ActualMinutes,
		&i.Progress,
		&i.Priority,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByFrequency = `-- name: GetTaskByFrequency :many
SELECT t.id, t.user_id, t.project_id, t.title, t.description, t.due_date, t.estimated_minutes, t.actual_minutes, t.progress,
       t.priority, t.status, t.created_at, t.updated_at
FROM tasks AS t
WHERE EXISTS (
    SELECT 1
    FROM todo_items AS ti
    JOIN todo_item_frequencies AS tif ON tif.todo_item_id = ti.id
    WHERE ti.task_id = t.id
      AND tif.frequency = $1::text
)
OR EXISTS (
    SELECT 1
    FROM task_schedules AS ts
    JOIN task_schedule_frequencies AS tsf ON tsf.task_schedule_id = ts.id
    WHERE ts.task_id = t.id
      AND tsf.frequency = $1::text
)
`

func (q *Queries) GetTaskByFrequency(ctx context.Context, frequency string) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTaskByFrequency, frequency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Progress,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByPriority = `-- name: GetTaskByPriority :many
SELECT id, user_id, project_id, title, description, due_date, estimated_minutes, actual_minutes, progress,
       priority, status, created_at, updated_at
FROM tasks
WHERE priority = $1
`

func (q *Queries) GetTaskByPriority(ctx context.Context, priority string) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTaskByPriority, priority)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Progress,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByProject = `-- name: GetTaskByProject :many
SELECT id, user_id, project_id, title, description, due_date, estimated_minutes, actual_minutes, progress,
       priority, status, created_at, updated_at
FROM tasks
WHERE project_id = $1::text
`

func (q *Queries) GetTaskByProject(ctx context.Context, projectID string) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTaskByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Progress,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByProjectType = `-- name: GetTaskByProjectType :many
SELECT t.id, t.user_id, t.project_id, t.title, t.description, t.due_date, t.estimated_minutes, t.actual_minutes, t.progress,
       t.priority, t.status, t.created_at, t.updated_at
FROM tasks AS t
JOIN projects AS p ON p.id = t.project_id
WHERE p.type = $1
`

func (q *Queries) GetTaskByProjectType(ctx context.Context, type_ string) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTaskByProjectType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Progress,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByStatus = `-- name: GetTaskByStatus :many
SELECT id, user_id, project_id, title, description, due_date, estimated_minutes, actual_minutes, progress,
       priority, status, created_at, updated_at
FROM tasks
WHERE status = $1
`

func (q *Queries) GetTaskByStatus(ctx context.Context, status string) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTaskByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Progress,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByTag = `-- name: GetTaskByTag :many
SELECT t.id, t.user_id, t.project_id, t.title, t.description, t.due_date, t.estimated_minutes, t.actual_minutes, t.progress,
       t.priority, t.status, t.created_at, t.updated_at
FROM tasks AS t
JOIN task_tag_assignments AS tta ON tta.task_id = t.id
WHERE tta.tag_id = $1
`

func (q *Queries) GetTaskByTag(ctx context.Context, tagID string) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTaskByTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Progress,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByUser = `-- name: GetTaskByUser :one
SELECT id, user_id, project_id, title, description, due_date, estimated_minutes, actual_minutes, progress,
       priority, status, created_at, updated_at
FROM tasks
WHERE id = $1
  AND user_id = $2
`

type GetTaskByUserParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetTaskByUser(ctx context.Context, arg GetTaskByUserParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByUser, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.DueDate,
		&i.EstimatedMinutes,
		&i.ActualMinutes,
		&i.Progress,
		&i.Priority,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTaskSchedulesByTaskForUser = `-- name: ListTaskSchedulesByTaskForUser :many
SELECT
    ts.id,
    ts.task_id,
    ts.title,
    ts.description,
    ts.location,
    ts.interval_weeks,
    ARRAY(
        SELECT tsf.frequency
        FROM task_schedule_frequencies AS tsf
        WHERE tsf.task_schedule_id = ts.id
        ORDER BY tsf.frequency
    )::text[] AS frequencies,
    ts.start_at,
    ts.end_at,
    ts.created_at,
    ts.updated_at
FROM task_schedules AS ts
JOIN tasks AS t ON t.id = ts.task_id
WHERE ts.task_id = $1
  AND t.user_id = $2
ORDER BY ts.start_at ASC
`

type ListTaskSchedulesByTaskForUserParams struct {
	TaskID string
	UserID string
}

type ListTaskSchedulesByTaskForUserRow struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	Location      pgtype.Text
	IntervalWeeks int32
	Frequencies   []string
	StartAt       pgtype.Timestamptz
	EndAt         pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) ListTaskSchedulesByTaskForUser(ctx context.Context, arg ListTaskSchedulesByTaskForUserParams) ([]ListTaskSchedulesByTaskForUserRow, error) {
	rows, err := q.db.Query(ctx, listTaskSchedulesByTaskForUser, arg.TaskID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskSchedulesByTaskForUserRow
	for rows.Next() {
		var i ListTaskSchedulesByTaskForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.IntervalWeeks,
			&i.Frequencies,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProjectAndUser = `-- name: ListTasksByProjectAndUser :many
SELECT t.id, t.user_id, t.project_id, t.title, t.description, t.due_date, t.estimated_minutes, t.actual_minutes, t.progress,
       t.priority, t.status, t.created_at, t.updated_at
FROM tasks AS t
JOIN projects AS p ON p.id = t.project_id
WHERE t.project_id = $1
  AND p.user_id = $2
ORDER BY t.created_at ASC
`

type ListTasksByProjectAndUserParams struct {
	ProjectID pgtype.Text
	UserID    string
}

func (q *Queries) ListTasksByProjectAndUser(ctx context.Context, arg ListTasksByProjectAndUserParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByProjectAndUser, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Progress,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoItemsByTaskForUser = `-- name: ListTodoItemsByTaskForUser :many
SELECT
    ti.id,
    ti.task_id,
    ti.title,
    ti.description,
    ti.due_date,
    ti.completed,
    ti.position,
    ti.interval_weeks,
    ARRAY(
        SELECT tif.frequency
        FROM todo_item_frequencies AS tif
        WHERE tif.todo_item_id = ti.id
        ORDER BY tif.frequency
    )::text[] AS frequencies,
    ti.created_at,
    ti.updated_at
FROM todo_items AS ti
JOIN tasks AS t ON t.id = ti.task_id
WHERE ti.task_id = $1
  AND t.user_id = $2
ORDER BY ti.position ASC
`

type ListTodoItemsByTaskForUserParams struct {
	TaskID string
	UserID string
}

type ListTodoItemsByTaskForUserRow struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	DueDate       pgtype.Date
	Completed     bool
	Position      int32
	IntervalWeeks int32
	Frequencies   []string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) ListTodoItemsByTaskForUser(ctx context.Context, arg ListTodoItemsByTaskForUserParams) ([]ListTodoItemsByTaskForUserRow, error) {
	rows, err := q.db.Query(ctx, listTodoItemsByTaskForUser, arg.TaskID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTodoItemsByTaskForUserRow
	for rows.Next() {
		var i ListTodoItemsByTaskForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.Completed,
			&i.Position,
			&i.IntervalWeeks,
			&i.Frequencies,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
