// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todo_items.mut.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTodoItemFrequency = `-- name: AddTodoItemFrequency :exec
INSERT INTO todo_item_frequencies (todo_item_id, frequency)
VALUES ($1, $2)
`

type AddTodoItemFrequencyParams struct {
	TodoItemID string
	Frequency  string
}

func (q *Queries) AddTodoItemFrequency(ctx context.Context, arg AddTodoItemFrequencyParams) error {
	_, err := q.db.Exec(ctx, addTodoItemFrequency, arg.TodoItemID, arg.Frequency)
	return err
}

const createTodoItem = `-- name: CreateTodoItem :one
INSERT INTO todo_items (id, task_id, title, description, completed, position, interval_weeks)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, task_id, title, description, completed, position, interval_weeks, created_at, updated_at
`

type CreateTodoItemParams struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	Completed     bool
	Position      int32
	IntervalWeeks int32
}

func (q *Queries) CreateTodoItem(ctx context.Context, arg CreateTodoItemParams) (TodoItem, error) {
	row := q.db.QueryRow(ctx, createTodoItem,
		arg.ID,
		arg.TaskID,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.Position,
		arg.IntervalWeeks,
	)
	var i TodoItem
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.Position,
		&i.IntervalWeeks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTodoItemByTaskAndUser = `-- name: CreateTodoItemByTaskAndUser :one
WITH owned_task AS (
    SELECT tasks.id
    FROM tasks
    WHERE tasks.id = $1
      AND tasks.user_id = $2
),
next_position AS (
    SELECT COALESCE($3::integer, COALESCE(MAX(ti.position), -1)::integer + 1) AS position
    FROM owned_task AS ot
    LEFT JOIN todo_items AS ti ON ti.task_id = ot.id
),
inserted AS (
    INSERT INTO todo_items (id, task_id, title, description, completed, position, interval_weeks)
    SELECT
        $4,
        owned_task.id,
        $5,
        $6,
        false,
        next_position.position,
        $7
    FROM owned_task
    CROSS JOIN next_position
    RETURNING id, task_id, title, description, completed, position, interval_weeks, created_at, updated_at
),
inserted_frequencies AS (
    INSERT INTO todo_item_frequencies (todo_item_id, frequency)
    SELECT inserted.id, unnest($8::text[])
    FROM inserted
    ON CONFLICT DO NOTHING
)
SELECT
    inserted.id,
    inserted.task_id,
    inserted.title,
    inserted.description,
    inserted.completed,
    inserted.position,
    inserted.interval_weeks,
    ARRAY(
        SELECT tif.frequency
        FROM todo_item_frequencies AS tif
        WHERE tif.todo_item_id = inserted.id
        ORDER BY tif.frequency
    )::text[] AS frequencies,
    inserted.created_at,
    inserted.updated_at
FROM inserted
`

type CreateTodoItemByTaskAndUserParams struct {
	TaskID        string
	UserID        string
	Position      pgtype.Int4
	ID            string
	Title         string
	Description   pgtype.Text
	IntervalWeeks int32
	Frequencies   []string
}

type CreateTodoItemByTaskAndUserRow struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	Completed     bool
	Position      int32
	IntervalWeeks int32
	Frequencies   []string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) CreateTodoItemByTaskAndUser(ctx context.Context, arg CreateTodoItemByTaskAndUserParams) (CreateTodoItemByTaskAndUserRow, error) {
	row := q.db.QueryRow(ctx, createTodoItemByTaskAndUser,
		arg.TaskID,
		arg.UserID,
		arg.Position,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.IntervalWeeks,
		arg.Frequencies,
	)
	var i CreateTodoItemByTaskAndUserRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.Position,
		&i.IntervalWeeks,
		&i.Frequencies,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTodoItem = `-- name: DeleteTodoItem :exec
DELETE FROM todo_items
WHERE id = $1
`

func (q *Queries) DeleteTodoItem(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTodoItem, id)
	return err
}

const deleteTodoItemByTaskAndUser = `-- name: DeleteTodoItemByTaskAndUser :one
DELETE FROM todo_items AS ti
USING tasks AS t
WHERE ti.id = $1
  AND ti.task_id = $2
  AND t.id = ti.task_id
  AND t.user_id = $3
RETURNING ti.id
`

type DeleteTodoItemByTaskAndUserParams struct {
	ID     string
	TaskID string
	UserID string
}

func (q *Queries) DeleteTodoItemByTaskAndUser(ctx context.Context, arg DeleteTodoItemByTaskAndUserParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteTodoItemByTaskAndUser, arg.ID, arg.TaskID, arg.UserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteTodoItemFrequencies = `-- name: DeleteTodoItemFrequencies :exec
DELETE FROM todo_item_frequencies
WHERE todo_item_id = $1
`

func (q *Queries) DeleteTodoItemFrequencies(ctx context.Context, todoItemID string) error {
	_, err := q.db.Exec(ctx, deleteTodoItemFrequencies, todoItemID)
	return err
}

const setTodoItemCompletedByTaskAndUser = `-- name: SetTodoItemCompletedByTaskAndUser :one
UPDATE todo_items AS ti
SET completed = $4,
    updated_at = now()
FROM tasks AS t
WHERE ti.id = $1
  AND ti.task_id = $2
  AND t.id = ti.task_id
  AND t.user_id = $3
RETURNING ti.id, ti.task_id, ti.title, ti.description, ti.completed, ti.position, ti.interval_weeks, ti.created_at, ti.updated_at
`

type SetTodoItemCompletedByTaskAndUserParams struct {
	ID        string
	TaskID    string
	UserID    string
	Completed bool
}

func (q *Queries) SetTodoItemCompletedByTaskAndUser(ctx context.Context, arg SetTodoItemCompletedByTaskAndUserParams) (TodoItem, error) {
	row := q.db.QueryRow(ctx, setTodoItemCompletedByTaskAndUser,
		arg.ID,
		arg.TaskID,
		arg.UserID,
		arg.Completed,
	)
	var i TodoItem
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.Position,
		&i.IntervalWeeks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTodoItem = `-- name: UpdateTodoItem :one
UPDATE todo_items
SET task_id = $2,
    title = $3,
    description = $4,
    completed = $5,
    position = $6,
    interval_weeks = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, task_id, title, description, completed, position, interval_weeks, created_at, updated_at
`

type UpdateTodoItemParams struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	Completed     bool
	Position      int32
	IntervalWeeks int32
}

func (q *Queries) UpdateTodoItem(ctx context.Context, arg UpdateTodoItemParams) (TodoItem, error) {
	row := q.db.QueryRow(ctx, updateTodoItem,
		arg.ID,
		arg.TaskID,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.Position,
		arg.IntervalWeeks,
	)
	var i TodoItem
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.Position,
		&i.IntervalWeeks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
