// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todo_items.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTodoItem = `-- name: GetTodoItem :one
SELECT
    ti.id,
    ti.task_id,
    ti.title,
    ti.description,
    ti.completed,
    ti.position,
    ti.interval_weeks,
    ARRAY(
        SELECT tif.frequency
        FROM todo_item_frequencies AS tif
        WHERE tif.todo_item_id = ti.id
        ORDER BY tif.frequency
    )::text[] AS frequencies,
    ti.created_at,
    ti.updated_at
FROM todo_items AS ti
WHERE ti.id = $1
`

type GetTodoItemRow struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	Completed     bool
	Position      int32
	IntervalWeeks int32
	Frequencies   []string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) GetTodoItem(ctx context.Context, id string) (GetTodoItemRow, error) {
	row := q.db.QueryRow(ctx, getTodoItem, id)
	var i GetTodoItemRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.Position,
		&i.IntervalWeeks,
		&i.Frequencies,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTodoItemByTaskAndUser = `-- name: GetTodoItemByTaskAndUser :one
SELECT
    ti.id,
    ti.task_id,
    ti.title,
    ti.description,
    ti.completed,
    ti.position,
    ti.interval_weeks,
    ARRAY(
        SELECT tif.frequency
        FROM todo_item_frequencies AS tif
        WHERE tif.todo_item_id = ti.id
        ORDER BY tif.frequency
    )::text[] AS frequencies,
    ti.created_at,
    ti.updated_at
FROM todo_items AS ti
JOIN tasks AS t ON t.id = ti.task_id
WHERE ti.id = $1
  AND ti.task_id = $2
  AND t.user_id = $3
`

type GetTodoItemByTaskAndUserParams struct {
	ID     string
	TaskID string
	UserID string
}

type GetTodoItemByTaskAndUserRow struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	Completed     bool
	Position      int32
	IntervalWeeks int32
	Frequencies   []string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) GetTodoItemByTaskAndUser(ctx context.Context, arg GetTodoItemByTaskAndUserParams) (GetTodoItemByTaskAndUserRow, error) {
	row := q.db.QueryRow(ctx, getTodoItemByTaskAndUser, arg.ID, arg.TaskID, arg.UserID)
	var i GetTodoItemByTaskAndUserRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.Position,
		&i.IntervalWeeks,
		&i.Frequencies,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTodoItemsByTaskAndUser = `-- name: ListTodoItemsByTaskAndUser :many
SELECT
    ti.id,
    ti.task_id,
    ti.title,
    ti.description,
    ti.completed,
    ti.position,
    ti.interval_weeks,
    ARRAY(
        SELECT tif.frequency
        FROM todo_item_frequencies AS tif
        WHERE tif.todo_item_id = ti.id
        ORDER BY tif.frequency
    )::text[] AS frequencies,
    ti.created_at,
    ti.updated_at
FROM todo_items AS ti
JOIN tasks AS t ON t.id = ti.task_id
WHERE ti.task_id = $1
  AND t.user_id = $2
ORDER BY ti.position ASC
`

type ListTodoItemsByTaskAndUserParams struct {
	TaskID string
	UserID string
}

type ListTodoItemsByTaskAndUserRow struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	Completed     bool
	Position      int32
	IntervalWeeks int32
	Frequencies   []string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) ListTodoItemsByTaskAndUser(ctx context.Context, arg ListTodoItemsByTaskAndUserParams) ([]ListTodoItemsByTaskAndUserRow, error) {
	rows, err := q.db.Query(ctx, listTodoItemsByTaskAndUser, arg.TaskID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTodoItemsByTaskAndUserRow
	for rows.Next() {
		var i ListTodoItemsByTaskAndUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.Position,
			&i.IntervalWeeks,
			&i.Frequencies,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextTodoItemPosition = `-- name: NextTodoItemPosition :one
SELECT COALESCE(MAX(ti.position), -1)::integer + 1 AS position
FROM todo_items AS ti
JOIN tasks AS t ON t.id = ti.task_id
WHERE ti.task_id = $1
  AND t.user_id = $2
`

type NextTodoItemPositionParams struct {
	TaskID string
	UserID string
}

func (q *Queries) NextTodoItemPosition(ctx context.Context, arg NextTodoItemPositionParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextTodoItemPosition, arg.TaskID, arg.UserID)
	var position int32
	err := row.Scan(&position)
	return position, err
}
