// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todo_items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTodoItem = `-- name: CreateTodoItem :one
INSERT INTO todo_items (id, task_id, title, description, completed, position, interval_weeks)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, task_id, title, description, completed, position, interval_weeks, created_at, updated_at
`

type CreateTodoItemParams struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	Completed     bool
	Position      int32
	IntervalWeeks int32
}

func (q *Queries) CreateTodoItem(ctx context.Context, arg CreateTodoItemParams) (TodoItem, error) {
	row := q.db.QueryRow(ctx, createTodoItem,
		arg.ID,
		arg.TaskID,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.Position,
		arg.IntervalWeeks,
	)
	var i TodoItem
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.Position,
		&i.IntervalWeeks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTodoItem = `-- name: DeleteTodoItem :exec
DELETE FROM todo_items
WHERE id = $1
`

func (q *Queries) DeleteTodoItem(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTodoItem, id)
	return err
}

const getTodoItem = `-- name: GetTodoItem :one
SELECT
    ti.id,
    ti.task_id,
    ti.title,
    ti.description,
    ti.completed,
    ti.position,
    ti.interval_weeks,
    ARRAY(
        SELECT tif.frequency
        FROM todo_item_frequencies AS tif
        WHERE tif.todo_item_id = ti.id
        ORDER BY tif.frequency
    )::text[] AS frequencies,
    ti.created_at,
    ti.updated_at
FROM todo_items AS ti
WHERE ti.id = $1
`

type GetTodoItemRow struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	Completed     bool
	Position      int32
	IntervalWeeks int32
	Frequencies   []string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) GetTodoItem(ctx context.Context, id string) (GetTodoItemRow, error) {
	row := q.db.QueryRow(ctx, getTodoItem, id)
	var i GetTodoItemRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.Position,
		&i.IntervalWeeks,
		&i.Frequencies,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTodoItem = `-- name: UpdateTodoItem :one
UPDATE todo_items
SET task_id = $2,
    title = $3,
    description = $4,
    completed = $5,
    position = $6,
    interval_weeks = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, task_id, title, description, completed, position, interval_weeks, created_at, updated_at
`

type UpdateTodoItemParams struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	Completed     bool
	Position      int32
	IntervalWeeks int32
}

func (q *Queries) UpdateTodoItem(ctx context.Context, arg UpdateTodoItemParams) (TodoItem, error) {
	row := q.db.QueryRow(ctx, updateTodoItem,
		arg.ID,
		arg.TaskID,
		arg.Title,
		arg.Description,
		arg.Completed,
		arg.Position,
		arg.IntervalWeeks,
	)
	var i TodoItem
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.Position,
		&i.IntervalWeeks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
