CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE users (
    -- Q: Why 26 characters?
    -- A: We use ULID (Universally Unique Lexicographically Sortable Identifier) for user IDs.
    id text PRIMARY KEY CHECK (id ~ '^[0-9ABCDEFGHJKMNPQRSTVWXYZ]{26}$'),
    first_name text NOT NULL,
    last_name text NOT NULL,
    email citext NOT NULL UNIQUE,
    password text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    timezone text NOT NULL DEFAULT 'Asia/Tokyo'
);

CREATE TABLE roles (
    role_id text PRIMARY KEY CHECK (role_id ~ '^[a-z][a-z0-9_]*$'),
    name text NOT NULL UNIQUE CHECK (btrim(name) <> ''),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TYPE permission_action AS ENUM ('create', 'read', 'update', 'delete');
CREATE TYPE permission_effect AS ENUM ('allow', 'deny');

CREATE TABLE managed_resources (
    resource_id text PRIMARY KEY CHECK (resource_id ~ '^[a-z][a-z0-9_]*$'),
    name text NOT NULL UNIQUE CHECK (btrim(name) <> ''),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE permissions (
    permission_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id text NOT NULL REFERENCES managed_resources(resource_id) ON DELETE CASCADE,
    action permission_action NOT NULL,
    effect permission_effect NOT NULL,
    description text NOT NULL CHECK (btrim(description) <> ''),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (resource_id, action, effect)
);

CREATE TABLE role_permissions (
    role_id text NOT NULL REFERENCES roles(role_id) ON DELETE CASCADE,
    permission_id bigint NOT NULL REFERENCES permissions(permission_id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (role_id, permission_id)
);

INSERT INTO roles (role_id, name) VALUES
    ('viewer', 'Viewer'),
    ('editor', 'Editor'),
    ('admin', 'Administrator');

INSERT INTO managed_resources (resource_id, name) VALUES
    ('project', 'Project'),
    ('task', 'Task'),
    ('todo_item', 'Todo item'),
    ('task_schedule', 'Task schedule'),
    ('task_assignment', 'Task assignment'),
    ('occurrence', 'Recurrence occurrence'),
    ('project_member', 'Project member management'),
    ('deleted_history', 'Deleted resource history');

INSERT INTO permissions (resource_id, action, effect, description)
SELECT resource_id, action::permission_action, effect::permission_effect,
       format('%s %s access (%s)', name, action, effect)
FROM managed_resources
CROSS JOIN LATERAL unnest(ARRAY['create', 'read', 'update', 'delete']) AS actions(action)
CROSS JOIN LATERAL unnest(ARRAY['allow', 'deny']) AS effects(effect)
WHERE (resource_id, action::text) IN (
    ('project', 'read'), ('project', 'update'), ('project', 'delete'),
    ('task', 'read'), ('task', 'create'), ('task', 'update'), ('task', 'delete'),
    ('todo_item', 'read'), ('todo_item', 'create'), ('todo_item', 'update'), ('todo_item', 'delete'),
    ('task_schedule', 'read'), ('task_schedule', 'create'), ('task_schedule', 'update'), ('task_schedule', 'delete'),
    ('task_assignment', 'update'), ('occurrence', 'update'),
    ('project_member', 'read'), ('project_member', 'create'), ('project_member', 'update'), ('project_member', 'delete'),
    ('deleted_history', 'read')
);

INSERT INTO role_permissions (role_id, permission_id)
SELECT 'viewer', permission_id
FROM permissions
WHERE effect = 'allow' AND (resource_id, action) IN (
    ('project', 'read'), ('task', 'read'), ('todo_item', 'read'), ('task_schedule', 'read')
);

INSERT INTO role_permissions (role_id, permission_id)
SELECT 'editor', permission_id
FROM permissions
WHERE effect = 'allow' AND (resource_id, action) IN (
    ('project', 'read'), ('project', 'update'),
    ('task', 'read'), ('task', 'create'), ('task', 'update'),
    ('todo_item', 'read'), ('todo_item', 'create'), ('todo_item', 'update'),
    ('task_schedule', 'read'), ('task_schedule', 'create'), ('task_schedule', 'update'),
    ('task_assignment', 'update'), ('occurrence', 'update')
);

INSERT INTO role_permissions (role_id, permission_id)
SELECT 'admin', permission_id
FROM permissions
WHERE effect = 'allow';

CREATE TABLE access_tokens (
    token TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES users(id),
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_access_tokens_user_id ON access_tokens(user_id);
CREATE INDEX idx_access_tokens_expires_at ON access_tokens(expires_at);
