// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access_tokens.mut.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccessToken = `-- name: CreateAccessToken :one
INSERT INTO access_tokens (token, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING token, user_id, expires_at, revoked_at, created_at
`

type CreateAccessTokenParams struct {
	Token     string
	UserID    string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (AccessToken, error) {
	row := q.db.QueryRow(ctx, createAccessToken, arg.Token, arg.UserID, arg.ExpiresAt)
	var i AccessToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAccessToken = `-- name: RevokeAccessToken :exec
UPDATE access_tokens
SET revoked_at = $2
WHERE token = $1
`

type RevokeAccessTokenParams struct {
	Token     string
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeAccessToken(ctx context.Context, arg RevokeAccessTokenParams) error {
	_, err := q.db.Exec(ctx, revokeAccessToken, arg.Token, arg.RevokedAt)
	return err
}
