// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorization.query.sql

package sqlc

import (
	"context"
)

const hasProjectPermission = `-- name: HasProjectPermission :one
SELECT project_has_permission(
    p.id,
    $1::text,
    $2::text,
    $3::action
) AS allowed
FROM projects AS p
WHERE p.id = $4::text AND p.deleted_at IS NULL
`

type HasProjectPermissionParams struct {
	ActorID    string
	ResourceID string
	Action     Action
	ProjectID  string
}

func (q *Queries) HasProjectPermission(ctx context.Context, arg HasProjectPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasProjectPermission,
		arg.ActorID,
		arg.ResourceID,
		arg.Action,
		arg.ProjectID,
	)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const hasTaskPermission = `-- name: HasTaskPermission :one
SELECT task_has_permission(
    t.id,
    $1::text,
    $2::text,
    $3::action
) AS allowed
FROM tasks AS t
WHERE t.id = $4::text AND t.deleted_at IS NULL
`

type HasTaskPermissionParams struct {
	ActorID    string
	ResourceID string
	Action     Action
	TaskID     string
}

func (q *Queries) HasTaskPermission(ctx context.Context, arg HasTaskPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasTaskPermission,
		arg.ActorID,
		arg.ResourceID,
		arg.Action,
		arg.TaskID,
	)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}
