// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Action string

const (
	ActionCreate Action = "create"
	ActionRead   Action = "read"
	ActionUpdate Action = "update"
	ActionDelete Action = "delete"
)

func (e *Action) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Action(s)
	case string:
		*e = Action(s)
	default:
		return fmt.Errorf("unsupported scan type for Action: %T", src)
	}
	return nil
}

type NullAction struct {
	Action Action
	Valid  bool // Valid is true if Action is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAction) Scan(value interface{}) error {
	if value == nil {
		ns.Action, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Action.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Action), nil
}

type Effect string

const (
	EffectAllow Effect = "allow"
	EffectDeny  Effect = "deny"
)

func (e *Effect) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Effect(s)
	case string:
		*e = Effect(s)
	default:
		return fmt.Errorf("unsupported scan type for Effect: %T", src)
	}
	return nil
}

type NullEffect struct {
	Effect Effect
	Valid  bool // Valid is true if Effect is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEffect) Scan(value interface{}) error {
	if value == nil {
		ns.Effect, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Effect.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEffect) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Effect), nil
}

type FrequencyMaster struct {
	Frequency string
	Label     string
	LabelJp   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ManagedResource struct {
	ResourceID string
	Name       string
	CreatedAt  pgtype.Timestamptz
}

type Permission struct {
	PermissionID int64
	ResourceID   string
	Action       Action
	Effect       Effect
	Description  string
	CreatedAt    pgtype.Timestamptz
}

type PersonalAccessToken struct {
	Token     string
	UserID    string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type PriorityMaster struct {
	Priority  string
	Label     string
	LabelJp   string
	Weight    int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Project struct {
	ID          string
	UserID      string
	Type        string
	Title       string
	Goal        pgtype.Text
	Description pgtype.Text
	Priority    string
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	Revision    int32
	DeletedAt   pgtype.Timestamptz
	ChangedBy   string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Status      string
}

type ProjectMember struct {
	ProjectID string
	UserID    string
	RoleID    string
	AddedBy   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ProjectRevision struct {
	ID          string
	Revision    int32
	UserID      string
	Type        string
	Title       string
	Goal        pgtype.Text
	Description pgtype.Text
	Priority    string
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	DeletedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ChangedBy   string
	ChangedAt   pgtype.Timestamptz
	Status      string
}

type ProjectTypeMaster struct {
	Type      string
	Label     string
	LabelJp   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Role struct {
	RoleID    string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type RolePermission struct {
	RoleID       string
	PermissionID int64
	CreatedAt    pgtype.Timestamptz
}

type Schedule struct {
	ID                  string
	UserID              string
	ProjectID           pgtype.Text
	AssigneeID          string
	Title               string
	Description         pgtype.Text
	Location            pgtype.Text
	StartAt             pgtype.Timestamptz
	EndAt               pgtype.Timestamptz
	SeriesID            string
	OccurrenceDate      pgtype.Date
	Timezone            string
	IsException         bool
	RepeatState         pgtype.Text
	FrequencyAnchorDate pgtype.Date
	IntervalWeeks       int32
	Completed           bool
	DeletedAt           pgtype.Timestamptz
	SkippedAt           pgtype.Timestamptz
	Revision            int32
	ChangedBy           string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type ScheduleFrequency struct {
	ScheduleID string
	Frequency  string
	CreatedAt  pgtype.Timestamptz
}

type ScheduleRevision struct {
	ID                  string
	Revision            int32
	UserID              string
	ProjectID           pgtype.Text
	AssigneeID          string
	Title               string
	Description         pgtype.Text
	Location            pgtype.Text
	StartAt             pgtype.Timestamptz
	EndAt               pgtype.Timestamptz
	SeriesID            string
	OccurrenceDate      pgtype.Date
	Timezone            string
	IsException         bool
	RepeatState         pgtype.Text
	FrequencyAnchorDate pgtype.Date
	IntervalWeeks       int32
	Completed           bool
	DeletedAt           pgtype.Timestamptz
	SkippedAt           pgtype.Timestamptz
	Frequencies         []string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ChangedBy           string
	ChangedAt           pgtype.Timestamptz
}

type ScheduleTagAssignment struct {
	ScheduleID string
	TagID      string
	CreatedAt  pgtype.Timestamptz
}

type StatusMaster struct {
	Status    string
	Label     string
	LabelJp   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Tag struct {
	ID        string
	UserID    string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Task struct {
	ID               string
	UserID           string
	ProjectID        pgtype.Text
	AssigneeID       string
	Title            string
	Description      pgtype.Text
	DueDate          pgtype.Date
	EstimatedMinutes pgtype.Int4
	ActualMinutes    pgtype.Int4
	Priority         string
	Status           string
	Revision         int32
	DeletedAt        pgtype.Timestamptz
	ChangedBy        string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type TaskRevision struct {
	ID               string
	Revision         int32
	UserID           string
	ProjectID        pgtype.Text
	AssigneeID       string
	Title            string
	Description      pgtype.Text
	DueDate          pgtype.Date
	EstimatedMinutes pgtype.Int4
	ActualMinutes    pgtype.Int4
	Priority         string
	Status           string
	DeletedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ChangedBy        string
	ChangedAt        pgtype.Timestamptz
}

type TaskTagAssignment struct {
	TaskID    string
	TagID     string
	CreatedAt pgtype.Timestamptz
}

type TodoItem struct {
	ID                  string
	TaskID              string
	Title               string
	Description         pgtype.Text
	DueDate             pgtype.Date
	Completed           bool
	Position            int32
	SeriesID            string
	OccurrenceDate      pgtype.Date
	Timezone            string
	IsException         bool
	RepeatState         pgtype.Text
	FrequencyAnchorDate pgtype.Date
	IntervalWeeks       int32
	DeletedAt           pgtype.Timestamptz
	SkippedAt           pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type TodoItemFrequency struct {
	TodoItemID string
	Frequency  string
	CreatedAt  pgtype.Timestamptz
}

type TodoList struct {
	ID        string
	UserID    string
	ListDate  pgtype.Date
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TodoListItem struct {
	TodoListID string
	TodoItemID string
	Position   int32
	CreatedAt  pgtype.Timestamptz
}

type TodoListSchedule struct {
	TodoListID string
	ScheduleID string
	CreatedAt  pgtype.Timestamptz
}

type User struct {
	ID        string
	FirstName string
	LastName  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Timezone  string
}
