// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PermissionAction string

const (
	PermissionActionCreate PermissionAction = "create"
	PermissionActionRead   PermissionAction = "read"
	PermissionActionUpdate PermissionAction = "update"
	PermissionActionDelete PermissionAction = "delete"
)

func (e *PermissionAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PermissionAction(s)
	case string:
		*e = PermissionAction(s)
	default:
		return fmt.Errorf("unsupported scan type for PermissionAction: %T", src)
	}
	return nil
}

type NullPermissionAction struct {
	PermissionAction PermissionAction
	Valid            bool // Valid is true if PermissionAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPermissionAction) Scan(value interface{}) error {
	if value == nil {
		ns.PermissionAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PermissionAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPermissionAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PermissionAction), nil
}

type PermissionEffect string

const (
	PermissionEffectAllow PermissionEffect = "allow"
	PermissionEffectDeny  PermissionEffect = "deny"
)

func (e *PermissionEffect) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PermissionEffect(s)
	case string:
		*e = PermissionEffect(s)
	default:
		return fmt.Errorf("unsupported scan type for PermissionEffect: %T", src)
	}
	return nil
}

type NullPermissionEffect struct {
	PermissionEffect PermissionEffect
	Valid            bool // Valid is true if PermissionEffect is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPermissionEffect) Scan(value interface{}) error {
	if value == nil {
		ns.PermissionEffect, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PermissionEffect.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPermissionEffect) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PermissionEffect), nil
}

type AccessToken struct {
	Token     string
	UserID    string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type FrequencyMaster struct {
	Frequency string
	Label     string
	LabelJp   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ManagedResource struct {
	ResourceID string
	Name       string
	CreatedAt  pgtype.Timestamptz
}

type Permission struct {
	PermissionID int64
	ResourceID   string
	Action       PermissionAction
	Effect       PermissionEffect
	Description  string
	CreatedAt    pgtype.Timestamptz
}

type PriorityMaster struct {
	Priority  string
	Label     string
	LabelJp   string
	Weight    int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Project struct {
	ID          string
	UserID      string
	Type        string
	Title       string
	Goal        pgtype.Text
	Description pgtype.Text
	Priority    string
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	Revision    int32
	DeletedAt   pgtype.Timestamptz
	ChangedBy   string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ProjectMember struct {
	ProjectID string
	UserID    string
	RoleID    string
	AddedBy   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ProjectRevision struct {
	ID          string
	Revision    int32
	UserID      string
	Type        string
	Title       string
	Goal        pgtype.Text
	Description pgtype.Text
	Priority    string
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	DeletedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ChangedBy   string
	ChangedAt   pgtype.Timestamptz
}

type ProjectTypeMaster struct {
	Type      string
	Label     string
	LabelJp   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Role struct {
	RoleID    string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type RolePermission struct {
	RoleID       string
	PermissionID int64
	CreatedAt    pgtype.Timestamptz
}

type Task struct {
	ID               string
	UserID           string
	ProjectID        pgtype.Text
	AssigneeID       string
	Title            string
	Description      pgtype.Text
	DueDate          pgtype.Date
	EstimatedMinutes pgtype.Int4
	ActualMinutes    pgtype.Int4
	Priority         string
	Status           string
	Revision         int32
	DeletedAt        pgtype.Timestamptz
	ChangedBy        string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type TaskRevision struct {
	ID               string
	Revision         int32
	UserID           string
	ProjectID        pgtype.Text
	AssigneeID       string
	Title            string
	Description      pgtype.Text
	DueDate          pgtype.Date
	EstimatedMinutes pgtype.Int4
	ActualMinutes    pgtype.Int4
	Priority         string
	Status           string
	DeletedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ChangedBy        string
	ChangedAt        pgtype.Timestamptz
}

type TaskSchedule struct {
	ID                  string
	TaskID              string
	Title               string
	Description         pgtype.Text
	Location            pgtype.Text
	StartAt             pgtype.Timestamptz
	EndAt               pgtype.Timestamptz
	SeriesID            string
	OccurrenceDate      pgtype.Date
	Timezone            string
	IsException         bool
	RepeatState         pgtype.Text
	FrequencyAnchorDate pgtype.Date
	IntervalWeeks       int32
	Completed           bool
	DeletedAt           pgtype.Timestamptz
	SkippedAt           pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type TaskScheduleFrequency struct {
	TaskScheduleID string
	Frequency      string
	CreatedAt      pgtype.Timestamptz
}

type TaskStatusMaster struct {
	Status    string
	Label     string
	LabelJp   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TaskTag struct {
	ID        string
	UserID    string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TaskTagAssignment struct {
	TaskID    string
	TagID     string
	CreatedAt pgtype.Timestamptz
}

type TodoItem struct {
	ID                  string
	TaskID              string
	Title               string
	Description         pgtype.Text
	DueDate             pgtype.Date
	Completed           bool
	Position            int32
	SeriesID            string
	OccurrenceDate      pgtype.Date
	Timezone            string
	IsException         bool
	RepeatState         pgtype.Text
	FrequencyAnchorDate pgtype.Date
	IntervalWeeks       int32
	DeletedAt           pgtype.Timestamptz
	SkippedAt           pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type TodoItemFrequency struct {
	TodoItemID string
	Frequency  string
	CreatedAt  pgtype.Timestamptz
}

type TodoList struct {
	ID        string
	UserID    string
	ListDate  pgtype.Date
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TodoListItem struct {
	TodoListID string
	TodoItemID string
	Position   int32
	CreatedAt  pgtype.Timestamptz
}

type TodoListTaskSchedule struct {
	TodoListID     string
	TaskScheduleID string
	CreatedAt      pgtype.Timestamptz
}

type User struct {
	ID        string
	FirstName string
	LastName  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Timezone  string
}
