// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessToken struct {
	Token     string
	UserID    string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type FrequencyMaster struct {
	Frequency string
	Label     string
	LabelJp   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type PriorityMaster struct {
	Priority  string
	Label     string
	LabelJp   string
	Weight    int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Project struct {
	ID          string
	UserID      string
	Type        string
	Title       string
	Goal        pgtype.Text
	Description pgtype.Text
	Progress    int16
	Priority    string
	StartAt     pgtype.Timestamptz
	EndAt       pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ProjectTypeMaster struct {
	Type      string
	Label     string
	LabelJp   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Task struct {
	ID               string
	UserID           string
	ProjectID        pgtype.Text
	Title            string
	Description      pgtype.Text
	DueDate          pgtype.Date
	EstimatedMinutes pgtype.Int4
	ActualMinutes    pgtype.Int4
	Progress         int16
	Priority         string
	Status           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type TaskSchedule struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	Location      pgtype.Text
	IntervalWeeks int32
	StartAt       pgtype.Timestamptz
	EndAt         pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type TaskScheduleFrequency struct {
	TaskScheduleID string
	Frequency      string
	CreatedAt      pgtype.Timestamptz
}

type TaskStatusMaster struct {
	Status    string
	Label     string
	LabelJp   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TaskTag struct {
	ID        string
	UserID    string
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TaskTagAssignment struct {
	TaskID    string
	TagID     string
	CreatedAt pgtype.Timestamptz
}

type TodoItem struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	DueDate       pgtype.Date
	Completed     bool
	Position      int32
	IntervalWeeks int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type TodoItemFrequency struct {
	TodoItemID string
	Frequency  string
	CreatedAt  pgtype.Timestamptz
}

type TodoList struct {
	ID        string
	UserID    string
	ListDate  pgtype.Date
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TodoListItem struct {
	TodoListID string
	TodoItemID string
	Position   int32
	CreatedAt  pgtype.Timestamptz
}

type TodoListTaskSchedule struct {
	TodoListID     string
	TaskScheduleID string
	CreatedAt      pgtype.Timestamptz
}

type User struct {
	ID        string
	FirstName string
	LastName  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
