// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personal_access_tokens.query.sql

package sqlc

import (
	"context"
)

const getPersonalAccessTokenByToken = `-- name: GetPersonalAccessTokenByToken :one
SELECT token, user_id, expires_at, revoked_at, created_at
FROM personal_access_tokens
WHERE token = $1
`

func (q *Queries) GetPersonalAccessTokenByToken(ctx context.Context, token string) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, getPersonalAccessTokenByToken, token)
	var i PersonalAccessToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}
