// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: personal_access_tokens.mut.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPersonalAccessToken = `-- name: CreatePersonalAccessToken :one
INSERT INTO personal_access_tokens (token, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING token, user_id, expires_at, revoked_at, created_at
`

type CreatePersonalAccessTokenParams struct {
	Token     string
	UserID    string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreatePersonalAccessToken(ctx context.Context, arg CreatePersonalAccessTokenParams) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, createPersonalAccessToken, arg.Token, arg.UserID, arg.ExpiresAt)
	var i PersonalAccessToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokePersonalAccessToken = `-- name: RevokePersonalAccessToken :exec
UPDATE personal_access_tokens
SET revoked_at = $2
WHERE token = $1
`

type RevokePersonalAccessTokenParams struct {
	Token     string
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokePersonalAccessToken(ctx context.Context, arg RevokePersonalAccessTokenParams) error {
	_, err := q.db.Exec(ctx, revokePersonalAccessToken, arg.Token, arg.RevokedAt)
	return err
}
