// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: priorities.query.sql

package sqlc

import (
	"context"
)

const listTaskPriorities = `-- name: ListTaskPriorities :many
SELECT priority, label, label_jp, weight, created_at, updated_at
FROM priority_master
`

func (q *Queries) ListTaskPriorities(ctx context.Context) ([]PriorityMaster, error) {
	rows, err := q.db.Query(ctx, listTaskPriorities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PriorityMaster
	for rows.Next() {
		var i PriorityMaster
		if err := rows.Scan(
			&i.Priority,
			&i.Label,
			&i.LabelJp,
			&i.Weight,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
