// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: progress.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const readProjectScheduleProgressCounts = `-- name: ReadProjectScheduleProgressCounts :many
WITH requested AS (
    SELECT s.id, s.project_id, s.series_id, s.occurrence_date,
           s.completed, s.deleted_at, s.skipped_at
    FROM schedules s
    WHERE s.project_id = ANY($1::text[])
), schedule_occurrences AS (
    SELECT DISTINCT ON (s.project_id, s.series_id, s.occurrence_date)
        s.project_id, s.completed, s.deleted_at, s.skipped_at
    FROM requested s
    ORDER BY s.project_id, s.series_id, s.occurrence_date,
             (s.deleted_at IS NOT NULL AND s.skipped_at IS NOT NULL) ASC,
             (s.id <> s.series_id) DESC
)
SELECT project_id,
       COUNT(*) FILTER (WHERE deleted_at IS NULL AND skipped_at IS NULL)::bigint AS total,
       COUNT(*) FILTER (WHERE deleted_at IS NULL AND skipped_at IS NULL AND completed)::bigint AS completed
FROM schedule_occurrences
GROUP BY project_id
`

type ReadProjectScheduleProgressCountsRow struct {
	ProjectID pgtype.Text
	Total     int64
	Completed int64
}

func (q *Queries) ReadProjectScheduleProgressCounts(ctx context.Context, projectIds []string) ([]ReadProjectScheduleProgressCountsRow, error) {
	rows, err := q.db.Query(ctx, readProjectScheduleProgressCounts, projectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadProjectScheduleProgressCountsRow
	for rows.Next() {
		var i ReadProjectScheduleProgressCountsRow
		if err := rows.Scan(&i.ProjectID, &i.Total, &i.Completed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readProjectScheduleProgressRoots = `-- name: ReadProjectScheduleProgressRoots :many
SELECT root.project_id,
       root.occurrence_date::text AS occurrence_date,
       root.timezone, root.interval_weeks,
       COALESCE(root.frequency_anchor_date, root.occurrence_date) AS frequency_anchor_date,
       ARRAY(
           SELECT f.frequency FROM schedule_frequencies f
           WHERE f.schedule_id = root.id ORDER BY f.frequency
       )::text[] AS frequencies,
       root.start_at, root.end_at,
       (root.occurrence_date = ($1::timestamptz AT TIME ZONE root.timezone)::date
        OR EXISTS (
            SELECT 1 FROM schedules child
            WHERE child.series_id = root.id AND child.id <> root.id
              AND (child.deleted_at IS NULL OR child.is_exception)
              AND child.occurrence_date = ($1::timestamptz AT TIME ZONE root.timezone)::date
        )) AS occurrence_saved_today
FROM schedules root
WHERE root.project_id = ANY($2::text[])
  AND root.id = root.series_id
  AND root.deleted_at IS NULL
  AND root.repeat_state = 'active'
`

type ReadProjectScheduleProgressRootsParams struct {
	AsOf       pgtype.Timestamptz
	ProjectIds []string
}

type ReadProjectScheduleProgressRootsRow struct {
	ProjectID            pgtype.Text
	OccurrenceDate       string
	Timezone             string
	IntervalWeeks        int32
	FrequencyAnchorDate  pgtype.Date
	Frequencies          []string
	StartAt              pgtype.Timestamptz
	EndAt                pgtype.Timestamptz
	OccurrenceSavedToday pgtype.Bool
}

func (q *Queries) ReadProjectScheduleProgressRoots(ctx context.Context, arg ReadProjectScheduleProgressRootsParams) ([]ReadProjectScheduleProgressRootsRow, error) {
	rows, err := q.db.Query(ctx, readProjectScheduleProgressRoots, arg.AsOf, arg.ProjectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadProjectScheduleProgressRootsRow
	for rows.Next() {
		var i ReadProjectScheduleProgressRootsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.OccurrenceDate,
			&i.Timezone,
			&i.IntervalWeeks,
			&i.FrequencyAnchorDate,
			&i.Frequencies,
			&i.StartAt,
			&i.EndAt,
			&i.OccurrenceSavedToday,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readTaskProgressSources = `-- name: ReadTaskProgressSources :many
WITH requested AS (
    SELECT unnest($1::text[]) AS task_id
    UNION
    SELECT t.id AS task_id
    FROM tasks t
    WHERE t.project_id = ANY($2::text[])
      AND t.deleted_at IS NULL
),
action_item_occurrences AS (
    SELECT DISTINCT ON (ti.task_id, ti.series_id, ti.occurrence_date)
        ti.task_id, ti.completed, ti.deleted_at, ti.skipped_at
    FROM action_items AS ti
    JOIN requested AS r ON r.task_id = ti.task_id
    ORDER BY ti.task_id, ti.series_id, ti.occurrence_date, (ti.id <> ti.series_id) DESC
),
action_item_counts AS (
    SELECT task_id,
           COUNT(*) FILTER (WHERE deleted_at IS NULL AND skipped_at IS NULL)::bigint AS total,
           COUNT(*) FILTER (WHERE deleted_at IS NULL AND skipped_at IS NULL AND completed)::bigint AS completed
    FROM action_item_occurrences GROUP BY task_id
),
action_item_roots AS (
    SELECT root.task_id,
           json_agg(json_build_object(
               'series_id', root.id,
               'occurrence_date', root.occurrence_date,
               'timezone', root.timezone,
               'interval_weeks', root.interval_weeks,
               'frequency_anchor_date', root.frequency_anchor_date,
               'frequencies', ARRAY(
                   SELECT f.frequency FROM action_item_frequencies AS f
                   WHERE f.action_item_id = root.id ORDER BY f.frequency
               ),
               'occurrence_saved_today',
                   root.occurrence_date = ($3::timestamptz AT TIME ZONE root.timezone)::date
                   OR EXISTS (
                       SELECT 1 FROM action_items child
                       WHERE child.series_id = root.id AND child.id <> root.id
                         AND child.occurrence_date = ($3::timestamptz AT TIME ZONE root.timezone)::date
                   )
           )) AS roots
    FROM action_items root
    JOIN requested r ON r.task_id = root.task_id
    WHERE root.id = root.series_id AND root.deleted_at IS NULL AND root.repeat_state = 'active'
    GROUP BY root.task_id
)
SELECT t.id AS task_id, t.project_id, t.status,
       COALESCE(tc.total, 0)::bigint AS action_item_total,
       COALESCE(tc.completed, 0)::bigint AS action_item_completed,
       COALESCE(tr.roots, '[]'::json)::json AS action_item_roots
FROM requested r
JOIN tasks t ON t.id = r.task_id
LEFT JOIN action_item_counts tc ON tc.task_id = t.id
LEFT JOIN action_item_roots tr ON tr.task_id = t.id
WHERE t.deleted_at IS NULL
`

type ReadTaskProgressSourcesParams struct {
	TaskIds    []string
	ProjectIds []string
	AsOf       pgtype.Timestamptz
}

type ReadTaskProgressSourcesRow struct {
	TaskID              string
	ProjectID           pgtype.Text
	Status              string
	ActionItemTotal     int64
	ActionItemCompleted int64
	ActionItemRoots     []byte
}

func (q *Queries) ReadTaskProgressSources(ctx context.Context, arg ReadTaskProgressSourcesParams) ([]ReadTaskProgressSourcesRow, error) {
	rows, err := q.db.Query(ctx, readTaskProgressSources, arg.TaskIds, arg.ProjectIds, arg.AsOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadTaskProgressSourcesRow
	for rows.Next() {
		var i ReadTaskProgressSourcesRow
		if err := rows.Scan(
			&i.TaskID,
			&i.ProjectID,
			&i.Status,
			&i.ActionItemTotal,
			&i.ActionItemCompleted,
			&i.ActionItemRoots,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
