// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_types.query.sql

package sqlc

import (
	"context"
)

const listProjectTypes = `-- name: ListProjectTypes :many
SELECT type, label, label_jp, created_at, updated_at
FROM project_type_master
`

func (q *Queries) ListProjectTypes(ctx context.Context) ([]ProjectTypeMaster, error) {
	rows, err := q.db.Query(ctx, listProjectTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectTypeMaster
	for rows.Next() {
		var i ProjectTypeMaster
		if err := rows.Scan(
			&i.Type,
			&i.Label,
			&i.LabelJp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
