// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.mut.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, user_id, type, title, goal, description, priority, start_date, end_date, changed_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $2)
RETURNING id, user_id, type, title, goal, description, priority, start_date, end_date, revision, deleted_at, changed_by, created_at, updated_at, status
`

type CreateProjectParams struct {
	ID          string
	UserID      string
	Type        string
	Title       string
	Goal        pgtype.Text
	Description pgtype.Text
	Priority    string
	StartDate   pgtype.Date
	EndDate     pgtype.Date
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Goal,
		arg.Description,
		arg.Priority,
		arg.StartDate,
		arg.EndDate,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Goal,
		&i.Description,
		&i.Priority,
		&i.StartDate,
		&i.EndDate,
		&i.Revision,
		&i.DeletedAt,
		&i.ChangedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :execrows
UPDATE projects
SET deleted_at = now(), changed_by = user_id
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteProject(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProjectByUserID = `-- name: DeleteProjectByUserID :one
WITH deleted_project AS (
    UPDATE projects
    SET deleted_at = now(), changed_by = $1::text
    WHERE id = $2::text
      AND deleted_at IS NULL
      AND revision = $3::integer
      AND project_has_permission(id, $1::text, 'project', 'delete')
    RETURNING id
)
SELECT id FROM deleted_project
`

type DeleteProjectByUserIDParams struct {
	UserID           string
	ID               string
	ExpectedRevision int32
}

func (q *Queries) DeleteProjectByUserID(ctx context.Context, arg DeleteProjectByUserIDParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteProjectByUserID, arg.UserID, arg.ID, arg.ExpectedRevision)
	var id string
	err := row.Scan(&id)
	return id, err
}

const restoreProjectByUserID = `-- name: RestoreProjectByUserID :one
UPDATE projects
SET deleted_at = NULL,
    changed_by = $1::text
WHERE id = $2::text
  AND deleted_at IS NOT NULL
  AND revision = $3::integer
  AND project_has_permission(id, $1::text, 'project', 'delete')
RETURNING id, user_id, type, title, goal, description, priority, start_date, end_date, revision, deleted_at, changed_by, created_at, updated_at, status
`

type RestoreProjectByUserIDParams struct {
	UserID           string
	ID               string
	ExpectedRevision int32
}

func (q *Queries) RestoreProjectByUserID(ctx context.Context, arg RestoreProjectByUserIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, restoreProjectByUserID, arg.UserID, arg.ID, arg.ExpectedRevision)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Goal,
		&i.Description,
		&i.Priority,
		&i.StartDate,
		&i.EndDate,
		&i.Revision,
		&i.DeletedAt,
		&i.ChangedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const setProjectStatusByUserID = `-- name: SetProjectStatusByUserID :one
UPDATE projects
SET status = $1::text,
    changed_by = $2::text
WHERE id = $3::text
  AND deleted_at IS NULL
  AND revision = $4::integer
  AND project_has_permission(id, $2::text, 'project', 'update')
RETURNING id, user_id, type, title, goal, description, priority, start_date, end_date, revision, deleted_at, changed_by, created_at, updated_at, status
`

type SetProjectStatusByUserIDParams struct {
	Status           string
	UserID           string
	ID               string
	ExpectedRevision int32
}

func (q *Queries) SetProjectStatusByUserID(ctx context.Context, arg SetProjectStatusByUserIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, setProjectStatusByUserID,
		arg.Status,
		arg.UserID,
		arg.ID,
		arg.ExpectedRevision,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Goal,
		&i.Description,
		&i.Priority,
		&i.StartDate,
		&i.EndDate,
		&i.Revision,
		&i.DeletedAt,
		&i.ChangedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const setProjectStatusForLifecycle = `-- name: SetProjectStatusForLifecycle :one
UPDATE projects
SET status = $1::text,
    changed_by = $2::text
WHERE id = $3::text
  AND deleted_at IS NULL
  AND status <> $1::text
RETURNING id, user_id, type, title, goal, description, priority, start_date, end_date, revision, deleted_at, changed_by, created_at, updated_at, status
`

type SetProjectStatusForLifecycleParams struct {
	Status  string
	ActorID string
	ID      string
}

func (q *Queries) SetProjectStatusForLifecycle(ctx context.Context, arg SetProjectStatusForLifecycleParams) (Project, error) {
	row := q.db.QueryRow(ctx, setProjectStatusForLifecycle, arg.Status, arg.ActorID, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Goal,
		&i.Description,
		&i.Priority,
		&i.StartDate,
		&i.EndDate,
		&i.Revision,
		&i.DeletedAt,
		&i.ChangedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET type = $2,
    title = $3,
    goal = $4,
    description = $5,
    priority = $6,
    start_date = $7,
    end_date = $8,
    changed_by = $9
WHERE id = $1
RETURNING id, user_id, type, title, goal, description, priority, start_date, end_date, revision, deleted_at, changed_by, created_at, updated_at, status
`

type UpdateProjectParams struct {
	ID          string
	Type        string
	Title       string
	Goal        pgtype.Text
	Description pgtype.Text
	Priority    string
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	ChangedBy   string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Type,
		arg.Title,
		arg.Goal,
		arg.Description,
		arg.Priority,
		arg.StartDate,
		arg.EndDate,
		arg.ChangedBy,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Goal,
		&i.Description,
		&i.Priority,
		&i.StartDate,
		&i.EndDate,
		&i.Revision,
		&i.DeletedAt,
		&i.ChangedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const updateProjectByUserID = `-- name: UpdateProjectByUserID :one
UPDATE projects
SET type = $3,
    title = $4,
    goal = $5,
    description = $6,
    priority = $7,
    start_date = $8,
    end_date = $9,
    changed_by = $2
WHERE id = $1
  AND deleted_at IS NULL
  AND revision = $10::integer
  AND project_has_permission(id, $11::text, 'project', 'update')
RETURNING id, user_id, type, title, goal, description, priority, start_date, end_date, revision, deleted_at, changed_by, created_at, updated_at, status
`

type UpdateProjectByUserIDParams struct {
	ID               string
	ChangedBy        string
	Type             string
	Title            string
	Goal             pgtype.Text
	Description      pgtype.Text
	Priority         string
	StartDate        pgtype.Date
	EndDate          pgtype.Date
	ExpectedRevision int32
	UserID           string
}

func (q *Queries) UpdateProjectByUserID(ctx context.Context, arg UpdateProjectByUserIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectByUserID,
		arg.ID,
		arg.ChangedBy,
		arg.Type,
		arg.Title,
		arg.Goal,
		arg.Description,
		arg.Priority,
		arg.StartDate,
		arg.EndDate,
		arg.ExpectedRevision,
		arg.UserID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Goal,
		&i.Description,
		&i.Priority,
		&i.StartDate,
		&i.EndDate,
		&i.Revision,
		&i.DeletedAt,
		&i.ChangedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}
