// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_members.mut.sql

package sqlc

import (
	"context"
)

const deleteProjectMember = `-- name: DeleteProjectMember :execrows
DELETE FROM project_members AS pm
USING projects AS p
WHERE p.id = pm.project_id
  AND p.id = $1::text
  AND pm.user_id = $2::text
  AND p.deleted_at IS NULL
  AND p.user_id <> pm.user_id
  AND project_has_permission(p.id, $3::text, 'project_member', 'delete')
`

type DeleteProjectMemberParams struct {
	ProjectID string
	MemberID  string
	ActorID   string
}

func (q *Queries) DeleteProjectMember(ctx context.Context, arg DeleteProjectMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectMember, arg.ProjectID, arg.MemberID, arg.ActorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const hasProjectMemberUpsertPermission = `-- name: HasProjectMemberUpsertPermission :one
SELECT project_has_permission(
    p.id,
    $1::text,
    'project_member',
    CASE WHEN EXISTS (
        SELECT 1 FROM project_members AS existing
        WHERE existing.project_id = p.id AND existing.user_id = $2::text
    ) THEN 'update'::action ELSE 'create'::action END
) AS allowed
FROM projects AS p
WHERE p.id = $3::text AND p.deleted_at IS NULL
`

type HasProjectMemberUpsertPermissionParams struct {
	ActorID   string
	MemberID  string
	ProjectID string
}

func (q *Queries) HasProjectMemberUpsertPermission(ctx context.Context, arg HasProjectMemberUpsertPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasProjectMemberUpsertPermission, arg.ActorID, arg.MemberID, arg.ProjectID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const lockProjectForMemberChange = `-- name: LockProjectForMemberChange :one
SELECT p.id
FROM projects AS p
WHERE p.id = $1::text
  AND p.deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) LockProjectForMemberChange(ctx context.Context, projectID string) (string, error) {
	row := q.db.QueryRow(ctx, lockProjectForMemberChange, projectID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const reassignProjectMemberTasks = `-- name: ReassignProjectMemberTasks :execrows
UPDATE tasks AS t
SET assignee_id = t.user_id,
    changed_by = $1::text
FROM projects AS p
WHERE t.project_id = p.id
  AND p.id = $2::text
  AND p.deleted_at IS NULL
  AND t.assignee_id = $3::text
  AND t.deleted_at IS NULL
  AND project_has_permission(p.id, $1::text, 'project_member', 'delete')
`

type ReassignProjectMemberTasksParams struct {
	ActorID   string
	ProjectID string
	MemberID  string
}

func (q *Queries) ReassignProjectMemberTasks(ctx context.Context, arg ReassignProjectMemberTasksParams) (int64, error) {
	result, err := q.db.Exec(ctx, reassignProjectMemberTasks, arg.ActorID, arg.ProjectID, arg.MemberID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertProjectMember = `-- name: UpsertProjectMember :execrows
INSERT INTO project_members (project_id, user_id, role_id, added_by)
SELECT p.id, $1::text, $2::text, $3::text
FROM projects AS p
WHERE p.id = $4::text
  AND p.deleted_at IS NULL
  AND p.user_id <> $1::text
  AND project_has_permission(
      p.id,
      $3::text,
      'project_member',
      CASE WHEN EXISTS (
          SELECT 1 FROM project_members AS existing
          WHERE existing.project_id = p.id AND existing.user_id = $1::text
      ) THEN 'update'::action ELSE 'create'::action END
  )
ON CONFLICT (project_id, user_id) DO UPDATE
SET role_id = EXCLUDED.role_id,
    added_by = EXCLUDED.added_by,
    updated_at = now()
WHERE project_has_permission(EXCLUDED.project_id, $3::text, 'project_member', 'update')
`

type UpsertProjectMemberParams struct {
	MemberID  string
	RoleID    string
	ActorID   string
	ProjectID string
}

func (q *Queries) UpsertProjectMember(ctx context.Context, arg UpsertProjectMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertProjectMember,
		arg.MemberID,
		arg.RoleID,
		arg.ActorID,
		arg.ProjectID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
