// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProject = `-- name: GetProject :one
SELECT id, user_id, type, title, goal, description, priority, start_date, end_date, revision, deleted_at, changed_by, created_at, updated_at, status
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Goal,
		&i.Description,
		&i.Priority,
		&i.StartDate,
		&i.EndDate,
		&i.Revision,
		&i.DeletedAt,
		&i.ChangedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const getProjectByUserID = `-- name: GetProjectByUserID :one
SELECT id, user_id, type, title, goal, description, priority, start_date, end_date, revision, deleted_at, changed_by, created_at, updated_at, status
FROM projects
WHERE id = $1
  AND deleted_at IS NULL
  AND project_has_permission(id, $2, 'project', 'read')
`

type GetProjectByUserIDParams struct {
	ID       string
	ActorKey string
}

func (q *Queries) GetProjectByUserID(ctx context.Context, arg GetProjectByUserIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByUserID, arg.ID, arg.ActorKey)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Goal,
		&i.Description,
		&i.Priority,
		&i.StartDate,
		&i.EndDate,
		&i.Revision,
		&i.DeletedAt,
		&i.ChangedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const getProjectByUserIDForPermission = `-- name: GetProjectByUserIDForPermission :one
SELECT p.id, p.user_id, p.type, p.title, p.goal, p.description, p.priority, p.start_date, p.end_date, p.revision, p.deleted_at, p.changed_by, p.created_at, p.updated_at, p.status
FROM projects AS p
WHERE p.id = $1::text
  AND p.deleted_at IS NULL
  AND project_has_permission(p.id, $2::text, $3::text, $4::action)
`

type GetProjectByUserIDForPermissionParams struct {
	ID         string
	ActorID    string
	ResourceID string
	Action     Action
}

func (q *Queries) GetProjectByUserIDForPermission(ctx context.Context, arg GetProjectByUserIDForPermissionParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByUserIDForPermission,
		arg.ID,
		arg.ActorID,
		arg.ResourceID,
		arg.Action,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Goal,
		&i.Description,
		&i.Priority,
		&i.StartDate,
		&i.EndDate,
		&i.Revision,
		&i.DeletedAt,
		&i.ChangedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const listProjectCandidates = `-- name: ListProjectCandidates :many
SELECT p.id, p.user_id, p.type, p.title, p.goal, p.description, p.priority, p.start_date, p.end_date, p.revision, p.deleted_at, p.changed_by, p.created_at, p.updated_at, p.status, pm.weight AS priority_weight,
       project_has_permission(p.id, $1::text, 'project', 'update') AS can_update,
       project_has_permission(p.id, $1::text, 'project', 'delete') AS can_delete
FROM projects AS p
JOIN priority_master AS pm ON pm.priority = p.priority
WHERE ($2::boolean AND p.deleted_at IS NOT NULL
       AND project_has_permission(p.id, $1::text, 'project', 'delete'))
   OR (NOT $2::boolean AND p.deleted_at IS NULL
       AND project_has_permission(p.id, $1::text, 'project', 'read')
       AND ($3::text IS NULL OR p.status = $3::text))
ORDER BY p.created_at DESC, p.id DESC
`

type ListProjectCandidatesParams struct {
	UserID  string
	IsTrash bool
	Status  pgtype.Text
}

type ListProjectCandidatesRow struct {
	ID             string
	UserID         string
	Type           string
	Title          string
	Goal           pgtype.Text
	Description    pgtype.Text
	Priority       string
	StartDate      pgtype.Date
	EndDate        pgtype.Date
	Revision       int32
	DeletedAt      pgtype.Timestamptz
	ChangedBy      string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Status         string
	PriorityWeight int32
	CanUpdate      bool
	CanDelete      bool
}

func (q *Queries) ListProjectCandidates(ctx context.Context, arg ListProjectCandidatesParams) ([]ListProjectCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listProjectCandidates, arg.UserID, arg.IsTrash, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectCandidatesRow
	for rows.Next() {
		var i ListProjectCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Goal,
			&i.Description,
			&i.Priority,
			&i.StartDate,
			&i.EndDate,
			&i.Revision,
			&i.DeletedAt,
			&i.ChangedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.PriorityWeight,
			&i.CanUpdate,
			&i.CanDelete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectPageBySort = `-- name: ListProjectPageBySort :many
SELECT p.id, p.user_id, p.type, p.title, p.goal, p.description, p.priority, p.start_date, p.end_date, p.revision, p.deleted_at, p.changed_by, p.created_at, p.updated_at, p.status, pm.weight AS priority_weight,
       project_has_permission(p.id, $1::text, 'project', 'update') AS can_update,
       project_has_permission(p.id, $1::text, 'project', 'delete') AS can_delete
FROM projects AS p
JOIN priority_master AS pm ON pm.priority = p.priority
WHERE (($2::boolean AND p.deleted_at IS NOT NULL
        AND project_has_permission(p.id, $1::text, 'project', 'delete'))
    OR (NOT $2::boolean AND p.deleted_at IS NULL
        AND project_has_permission(p.id, $1::text, 'project', 'read')
        AND ($3::text IS NULL OR p.status = $3::text)))
  AND (
    $4::text IS NULL
    OR (
      $5::text = 'created_at'
      AND (
        ($6::text = 'forward' AND (
          ($7::text = 'desc' AND (p.created_at, p.id) < ($8::timestamptz, $4::text))
          OR ($7::text = 'asc' AND (p.created_at, p.id) > ($8::timestamptz, $4::text))
        ))
        OR ($6::text = 'backward' AND (
          ($7::text = 'desc' AND (p.created_at, p.id) > ($8::timestamptz, $4::text))
          OR ($7::text = 'asc' AND (p.created_at, p.id) < ($8::timestamptz, $4::text))
        ))
      )
    )
    OR (
      $5::text = 'title'
      AND (
        ($6::text = 'forward' AND (
          ($7::text = 'asc' AND (lower(p.title) > $9::text OR (lower(p.title) = $9::text AND (pm.weight < $10::integer OR (pm.weight = $10::integer AND p.id > $4::text)))))
          OR ($7::text = 'desc' AND (lower(p.title) < $9::text OR (lower(p.title) = $9::text AND (pm.weight < $10::integer OR (pm.weight = $10::integer AND p.id > $4::text)))))
        ))
        OR ($6::text = 'backward' AND (
          ($7::text = 'asc' AND (lower(p.title) < $9::text OR (lower(p.title) = $9::text AND (pm.weight > $10::integer OR (pm.weight = $10::integer AND p.id < $4::text)))))
          OR ($7::text = 'desc' AND (lower(p.title) > $9::text OR (lower(p.title) = $9::text AND (pm.weight > $10::integer OR (pm.weight = $10::integer AND p.id < $4::text)))))
        ))
      )
    )
    OR (
      $5::text = 'end_date'
      AND (
        ($11::date IS NULL AND (
          ($6::text = 'forward' AND p.end_date IS NULL AND (pm.weight < $10::integer OR (pm.weight = $10::integer AND p.id > $4::text)))
          OR ($6::text = 'backward' AND (p.end_date IS NOT NULL OR (p.end_date IS NULL AND (pm.weight > $10::integer OR (pm.weight = $10::integer AND p.id < $4::text)))))
        ))
        OR ($11::date IS NOT NULL AND (
          ($6::text = 'forward' AND (
            p.end_date IS NULL
            OR ($7::text = 'asc' AND (p.end_date > $11::date OR (p.end_date = $11::date AND (pm.weight < $10::integer OR (pm.weight = $10::integer AND p.id > $4::text)))))
            OR ($7::text = 'desc' AND (p.end_date < $11::date OR (p.end_date = $11::date AND (pm.weight < $10::integer OR (pm.weight = $10::integer AND p.id > $4::text)))))
          ))
          OR ($6::text = 'backward' AND p.end_date IS NOT NULL AND (
            ($7::text = 'asc' AND (p.end_date < $11::date OR (p.end_date = $11::date AND (pm.weight > $10::integer OR (pm.weight = $10::integer AND p.id < $4::text)))))
            OR ($7::text = 'desc' AND (p.end_date > $11::date OR (p.end_date = $11::date AND (pm.weight > $10::integer OR (pm.weight = $10::integer AND p.id < $4::text)))))
          ))
        ))
      )
    )
  )
ORDER BY
    CASE WHEN $5::text = 'created_at' AND (($7::text = 'asc' AND $6::text = 'forward') OR ($7::text = 'desc' AND $6::text = 'backward')) THEN p.created_at END ASC,
    CASE WHEN $5::text = 'created_at' AND NOT (($7::text = 'asc' AND $6::text = 'forward') OR ($7::text = 'desc' AND $6::text = 'backward')) THEN p.created_at END DESC,
    CASE WHEN $5::text = 'title' AND (($7::text = 'asc' AND $6::text = 'forward') OR ($7::text = 'desc' AND $6::text = 'backward')) THEN lower(p.title) END ASC,
    CASE WHEN $5::text = 'title' AND NOT (($7::text = 'asc' AND $6::text = 'forward') OR ($7::text = 'desc' AND $6::text = 'backward')) THEN lower(p.title) END DESC,
    CASE WHEN $5::text = 'end_date' AND $6::text = 'forward' THEN (p.end_date IS NULL)::integer END ASC,
    CASE WHEN $5::text = 'end_date' AND $6::text = 'backward' THEN (p.end_date IS NULL)::integer END DESC,
    CASE WHEN $5::text = 'end_date' AND (($7::text = 'asc' AND $6::text = 'forward') OR ($7::text = 'desc' AND $6::text = 'backward')) THEN p.end_date END ASC,
    CASE WHEN $5::text = 'end_date' AND NOT (($7::text = 'asc' AND $6::text = 'forward') OR ($7::text = 'desc' AND $6::text = 'backward')) THEN p.end_date END DESC,
    CASE WHEN $5::text <> 'created_at' AND $6::text = 'backward' THEN pm.weight END ASC,
    CASE WHEN $5::text <> 'created_at' AND $6::text = 'forward' THEN pm.weight END DESC,
    CASE WHEN $5::text = 'created_at' AND (($7::text = 'asc' AND $6::text = 'forward') OR ($7::text = 'desc' AND $6::text = 'backward')) THEN p.id END ASC,
    CASE WHEN $5::text = 'created_at' AND NOT (($7::text = 'asc' AND $6::text = 'forward') OR ($7::text = 'desc' AND $6::text = 'backward')) THEN p.id END DESC,
    CASE WHEN $5::text <> 'created_at' AND $6::text = 'backward' THEN p.id END DESC,
    CASE WHEN $5::text <> 'created_at' AND $6::text = 'forward' THEN p.id END ASC
LIMIT $12::integer
`

type ListProjectPageBySortParams struct {
	UserID         string
	IsTrash        bool
	Status         pgtype.Text
	AnchorID       pgtype.Text
	SortBy         string
	Direction      string
	SortOrder      string
	AnchorAt       pgtype.Timestamptz
	AnchorTitle    pgtype.Text
	AnchorPriority pgtype.Int4
	AnchorEndDate  pgtype.Date
	PageLimit      int32
}

type ListProjectPageBySortRow struct {
	ID             string
	UserID         string
	Type           string
	Title          string
	Goal           pgtype.Text
	Description    pgtype.Text
	Priority       string
	StartDate      pgtype.Date
	EndDate        pgtype.Date
	Revision       int32
	DeletedAt      pgtype.Timestamptz
	ChangedBy      string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Status         string
	PriorityWeight int32
	CanUpdate      bool
	CanDelete      bool
}

func (q *Queries) ListProjectPageBySort(ctx context.Context, arg ListProjectPageBySortParams) ([]ListProjectPageBySortRow, error) {
	rows, err := q.db.Query(ctx, listProjectPageBySort,
		arg.UserID,
		arg.IsTrash,
		arg.Status,
		arg.AnchorID,
		arg.SortBy,
		arg.Direction,
		arg.SortOrder,
		arg.AnchorAt,
		arg.AnchorTitle,
		arg.AnchorPriority,
		arg.AnchorEndDate,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectPageBySortRow
	for rows.Next() {
		var i ListProjectPageBySortRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Goal,
			&i.Description,
			&i.Priority,
			&i.StartDate,
			&i.EndDate,
			&i.Revision,
			&i.DeletedAt,
			&i.ChangedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.PriorityWeight,
			&i.CanUpdate,
			&i.CanDelete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectPriorities = `-- name: ListProjectPriorities :many
SELECT priority, label, label_jp, weight, created_at, updated_at
FROM priority_master
ORDER BY weight DESC, priority
`

func (q *Queries) ListProjectPriorities(ctx context.Context) ([]PriorityMaster, error) {
	rows, err := q.db.Query(ctx, listProjectPriorities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PriorityMaster
	for rows.Next() {
		var i PriorityMaster
		if err := rows.Scan(
			&i.Priority,
			&i.Label,
			&i.LabelJp,
			&i.Weight,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTasksByUserID = `-- name: ListProjectTasksByUserID :many
SELECT t.id, t.user_id, t.project_id, t.assignee_id, t.title, t.description, t.due_date, t.estimated_minutes, t.actual_minutes, t.priority, t.status, t.revision, t.deleted_at, t.changed_by, t.created_at, t.updated_at
FROM tasks AS t
WHERE t.project_id = $1
  AND t.deleted_at IS NULL
  AND task_has_permission(t.id, $2, 'task', 'read')
  AND EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL)
ORDER BY t.created_at ASC
`

type ListProjectTasksByUserIDParams struct {
	ProjectID pgtype.Text
	ActorKey  string
}

func (q *Queries) ListProjectTasksByUserID(ctx context.Context, arg ListProjectTasksByUserIDParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listProjectTasksByUserID, arg.ProjectID, arg.ActorKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Priority,
			&i.Status,
			&i.Revision,
			&i.DeletedAt,
			&i.ChangedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByUserID = `-- name: ListProjectsByUserID :many
SELECT id, user_id, type, title, goal, description, priority, start_date, end_date, revision, deleted_at, changed_by, created_at, updated_at, status
FROM projects
WHERE deleted_at IS NULL
  AND project_has_permission(projects.id, $1::text, 'project', 'read')
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListProjectsByUserID(ctx context.Context, userID string) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Goal,
			&i.Description,
			&i.Priority,
			&i.StartDate,
			&i.EndDate,
			&i.Revision,
			&i.DeletedAt,
			&i.ChangedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByUserIDPage = `-- name: ListProjectsByUserIDPage :many
SELECT id, user_id, type, title, goal, description, priority, start_date, end_date, revision, deleted_at, changed_by, created_at, updated_at, status
FROM projects
WHERE deleted_at IS NULL
  AND project_has_permission(projects.id, $1::text, 'project', 'read')
  AND ($2::timestamptz IS NULL OR (created_at, id) < ($2::timestamptz, $3::text))
ORDER BY created_at DESC, id DESC
LIMIT $4::integer
`

type ListProjectsByUserIDPageParams struct {
	UserID    string
	CursorAt  pgtype.Timestamptz
	CursorID  pgtype.Text
	PageLimit int32
}

func (q *Queries) ListProjectsByUserIDPage(ctx context.Context, arg ListProjectsByUserIDPageParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByUserIDPage,
		arg.UserID,
		arg.CursorAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Goal,
			&i.Description,
			&i.Priority,
			&i.StartDate,
			&i.EndDate,
			&i.Revision,
			&i.DeletedAt,
			&i.ChangedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveProjectTasksForDeletion = `-- name: LockActiveProjectTasksForDeletion :many
SELECT id
FROM tasks
WHERE project_id = $1::text
  AND deleted_at IS NULL
ORDER BY id
FOR UPDATE
`

func (q *Queries) LockActiveProjectTasksForDeletion(ctx context.Context, projectID string) ([]string, error) {
	rows, err := q.db.Query(ctx, lockActiveProjectTasksForDeletion, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDeletedProjectByUserIDForPermission = `-- name: LockDeletedProjectByUserIDForPermission :one
SELECT p.id, p.user_id, p.type, p.title, p.goal, p.description, p.priority, p.start_date, p.end_date, p.revision, p.deleted_at, p.changed_by, p.created_at, p.updated_at, p.status
FROM projects AS p
WHERE p.id = $1::text
  AND p.deleted_at IS NOT NULL
  AND project_has_permission(p.id, $2::text, $3::text, $4::action)
FOR UPDATE
`

type LockDeletedProjectByUserIDForPermissionParams struct {
	ID         string
	UserID     string
	ResourceID string
	Action     Action
}

func (q *Queries) LockDeletedProjectByUserIDForPermission(ctx context.Context, arg LockDeletedProjectByUserIDForPermissionParams) (Project, error) {
	row := q.db.QueryRow(ctx, lockDeletedProjectByUserIDForPermission,
		arg.ID,
		arg.UserID,
		arg.ResourceID,
		arg.Action,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Goal,
		&i.Description,
		&i.Priority,
		&i.StartDate,
		&i.EndDate,
		&i.Revision,
		&i.DeletedAt,
		&i.ChangedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const lockProjectByUserIDForPermission = `-- name: LockProjectByUserIDForPermission :one
SELECT p.id, p.user_id, p.type, p.title, p.goal, p.description, p.priority, p.start_date, p.end_date, p.revision, p.deleted_at, p.changed_by, p.created_at, p.updated_at, p.status
FROM projects AS p
WHERE p.id = $1::text
  AND p.deleted_at IS NULL
  AND project_has_permission(p.id, $2::text, $3::text, $4::action)
FOR UPDATE
`

type LockProjectByUserIDForPermissionParams struct {
	ID         string
	UserID     string
	ResourceID string
	Action     Action
}

func (q *Queries) LockProjectByUserIDForPermission(ctx context.Context, arg LockProjectByUserIDForPermissionParams) (Project, error) {
	row := q.db.QueryRow(ctx, lockProjectByUserIDForPermission,
		arg.ID,
		arg.UserID,
		arg.ResourceID,
		arg.Action,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Goal,
		&i.Description,
		&i.Priority,
		&i.StartDate,
		&i.EndDate,
		&i.Revision,
		&i.DeletedAt,
		&i.ChangedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const lockProjectForLifecycle = `-- name: LockProjectForLifecycle :one
SELECT id
FROM projects
WHERE id = $1
  AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) LockProjectForLifecycle(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockProjectForLifecycle, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const readProjectListSummary = `-- name: ReadProjectListSummary :one
WITH user_calendar AS (
    SELECT timezone, ($1::timestamptz AT TIME ZONE timezone)::date AS today
    FROM users WHERE id = $2::text
), live_readable AS (
    SELECT p.id, p.user_id, p.type, p.title, p.goal, p.description, p.priority, p.start_date, p.end_date, p.revision, p.deleted_at, p.changed_by, p.created_at, p.updated_at, p.status FROM projects p
    WHERE p.deleted_at IS NULL
      AND project_has_permission(p.id, $2::text, 'project', 'read')
), trash_deletable AS (
    SELECT p.id, p.user_id, p.type, p.title, p.goal, p.description, p.priority, p.start_date, p.end_date, p.revision, p.deleted_at, p.changed_by, p.created_at, p.updated_at, p.status FROM projects p
    WHERE p.deleted_at IS NOT NULL
      AND project_has_permission(p.id, $2::text, 'project', 'delete')
), selected AS (
    SELECT p.id, p.user_id, p.type, p.title, p.goal, p.description, p.priority, p.start_date, p.end_date, p.revision, p.deleted_at, p.changed_by, p.created_at, p.updated_at, p.status FROM projects p, user_calendar c
    WHERE ($3::boolean AND p.deleted_at IS NOT NULL
           AND project_has_permission(p.id, $2::text, 'project', 'delete'))
       OR (NOT $3::boolean AND p.deleted_at IS NULL
           AND project_has_permission(p.id, $2::text, 'project', 'read')
           AND ($4::text IS NULL OR p.status = $4::text))
)
SELECT
    (SELECT COUNT(*) FROM selected)::bigint AS total_count,
    (SELECT COUNT(*) FROM selected p CROSS JOIN user_calendar c
      WHERE p.end_date >= c.today AND p.end_date <= c.today + 14)::bigint AS due_soon_count,
    (SELECT COUNT(*) FROM selected p CROSS JOIN user_calendar c
      WHERE p.end_date < c.today)::bigint AS overdue_count,
    (SELECT COUNT(*) FROM live_readable WHERE status = 'in_progress')::bigint AS in_progress_count,
    (SELECT COUNT(*) FROM live_readable WHERE status = 'pending')::bigint AS pending_count,
    (SELECT COUNT(*) FROM live_readable WHERE status = 'done')::bigint AS done_count,
    (SELECT COUNT(*) FROM live_readable WHERE status = 'open')::bigint AS open_count,
    (SELECT COUNT(*) FROM live_readable WHERE status = 'waiting_on_others')::bigint AS waiting_on_others_count,
    (SELECT COUNT(*) FROM trash_deletable)::bigint AS trash_count,
    (SELECT today FROM user_calendar) AS today,
    (SELECT timezone FROM user_calendar) AS timezone
`

type ReadProjectListSummaryParams struct {
	AsOf    pgtype.Timestamptz
	UserID  string
	IsTrash bool
	Status  pgtype.Text
}

type ReadProjectListSummaryRow struct {
	TotalCount           int64
	DueSoonCount         int64
	OverdueCount         int64
	InProgressCount      int64
	PendingCount         int64
	DoneCount            int64
	OpenCount            int64
	WaitingOnOthersCount int64
	TrashCount           int64
	Today                pgtype.Date
	Timezone             string
}

func (q *Queries) ReadProjectListSummary(ctx context.Context, arg ReadProjectListSummaryParams) (ReadProjectListSummaryRow, error) {
	row := q.db.QueryRow(ctx, readProjectListSummary,
		arg.AsOf,
		arg.UserID,
		arg.IsTrash,
		arg.Status,
	)
	var i ReadProjectListSummaryRow
	err := row.Scan(
		&i.TotalCount,
		&i.DueSoonCount,
		&i.OverdueCount,
		&i.InProgressCount,
		&i.PendingCount,
		&i.DoneCount,
		&i.OpenCount,
		&i.WaitingOnOthersCount,
		&i.TrashCount,
		&i.Today,
		&i.Timezone,
	)
	return i, err
}

const readProjectStatusForLifecycle = `-- name: ReadProjectStatusForLifecycle :one
SELECT status
FROM projects
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) ReadProjectStatusForLifecycle(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, readProjectStatusForLifecycle, id)
	var status string
	err := row.Scan(&status)
	return status, err
}
