// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_members.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT pm.project_id, pm.user_id, pm.role_id, r.name AS role_name,
       u.first_name, u.last_name, u.email, pm.added_by,
       pm.created_at, pm.updated_at
FROM project_members AS pm
JOIN projects AS p ON p.id = pm.project_id
JOIN roles AS r ON r.role_id = pm.role_id
JOIN users AS u ON u.id = pm.user_id
WHERE pm.project_id = $1::text
  AND p.deleted_at IS NULL
  AND project_has_permission(p.id, $2::text, 'project_member', 'read')
ORDER BY u.last_name, u.first_name, pm.user_id
`

type ListProjectMembersParams struct {
	ProjectID string
	ActorID   string
}

type ListProjectMembersRow struct {
	ProjectID string
	UserID    string
	RoleID    string
	RoleName  string
	FirstName string
	LastName  string
	Email     string
	AddedBy   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListProjectMembers(ctx context.Context, arg ListProjectMembersParams) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, arg.ProjectID, arg.ActorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectMembersRow
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.RoleID,
			&i.RoleName,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.AddedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
