// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurrence_occurrences.mut.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSkippedActionItemOccurrenceByTaskAndUserID = `-- name: DeleteSkippedActionItemOccurrenceByTaskAndUserID :exec
DELETE FROM action_items child
USING action_items root, tasks t
WHERE child.series_id = root.id
  AND root.task_id = t.id
  AND child.series_id = $1::text
  AND child.occurrence_date = $2::date
  AND child.task_id = $3::text
  AND child.id <> child.series_id
  AND NOT child.is_exception
  AND child.deleted_at IS NULL
  AND child.skipped_at IS NOT NULL
  AND root.deleted_at IS NULL
  AND task_has_permission(t.id, $4::text, 'occurrence', 'update')
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
`

type DeleteSkippedActionItemOccurrenceByTaskAndUserIDParams struct {
	SeriesID       string
	OccurrenceDate pgtype.Date
	TaskID         string
	UserID         string
}

func (q *Queries) DeleteSkippedActionItemOccurrenceByTaskAndUserID(ctx context.Context, arg DeleteSkippedActionItemOccurrenceByTaskAndUserIDParams) error {
	_, err := q.db.Exec(ctx, deleteSkippedActionItemOccurrenceByTaskAndUserID,
		arg.SeriesID,
		arg.OccurrenceDate,
		arg.TaskID,
		arg.UserID,
	)
	return err
}

const restoreEditedActionItemOccurrenceByTaskAndUserID = `-- name: RestoreEditedActionItemOccurrenceByTaskAndUserID :exec
UPDATE action_items child
SET skipped_at = NULL, updated_at = now()
FROM action_items root, tasks t
WHERE child.series_id = root.id
  AND root.task_id = t.id
  AND child.series_id = $1::text
  AND child.occurrence_date = $2::date
  AND child.task_id = $3::text
  AND child.id <> child.series_id
  AND child.is_exception
  AND child.deleted_at IS NULL
  AND child.skipped_at IS NOT NULL
  AND root.deleted_at IS NULL
  AND task_has_permission(t.id, $4::text, 'occurrence', 'update')
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
`

type RestoreEditedActionItemOccurrenceByTaskAndUserIDParams struct {
	SeriesID       string
	OccurrenceDate pgtype.Date
	TaskID         string
	UserID         string
}

func (q *Queries) RestoreEditedActionItemOccurrenceByTaskAndUserID(ctx context.Context, arg RestoreEditedActionItemOccurrenceByTaskAndUserIDParams) error {
	_, err := q.db.Exec(ctx, restoreEditedActionItemOccurrenceByTaskAndUserID,
		arg.SeriesID,
		arg.OccurrenceDate,
		arg.TaskID,
		arg.UserID,
	)
	return err
}

const skipActionItemOccurrenceByTaskAndUserID = `-- name: SkipActionItemOccurrenceByTaskAndUserID :one
INSERT INTO action_items (
    id, task_id, title, description, due_date, completed, position,
    series_id, occurrence_date, timezone, is_exception, repeat_state,
    frequency_anchor_date, interval_weeks, deleted_at, skipped_at
)
SELECT $1::text, root.task_id, root.title, root.description, root.due_date,
       false, root.position, root.id, $2::date, root.timezone,
       false, NULL, NULL, 0, NULL, now()
FROM action_items root
JOIN tasks t ON t.id = root.task_id
WHERE root.id = $3::text
  AND root.task_id = $4::text
  AND root.series_id = root.id
  AND root.deleted_at IS NULL
  AND task_has_permission(t.id, $5::text, 'occurrence', 'update')
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
ON CONFLICT (series_id, occurrence_date) WHERE id <> series_id
DO UPDATE SET skipped_at = COALESCE(action_items.skipped_at, now()), updated_at = now()
WHERE action_items.deleted_at IS NULL
RETURNING id
`

type SkipActionItemOccurrenceByTaskAndUserIDParams struct {
	ID             string
	OccurrenceDate pgtype.Date
	SeriesID       string
	TaskID         string
	UserID         string
}

func (q *Queries) SkipActionItemOccurrenceByTaskAndUserID(ctx context.Context, arg SkipActionItemOccurrenceByTaskAndUserIDParams) (string, error) {
	row := q.db.QueryRow(ctx, skipActionItemOccurrenceByTaskAndUserID,
		arg.ID,
		arg.OccurrenceDate,
		arg.SeriesID,
		arg.TaskID,
		arg.UserID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const upsertActionItemOverrideByTaskAndUserID = `-- name: UpsertActionItemOverrideByTaskAndUserID :one
INSERT INTO action_items (
    id, task_id, title, description, due_date, estimated_minutes, priority, completed, position,
    series_id, occurrence_date, timezone, is_exception, repeat_state,
    frequency_anchor_date, interval_weeks, deleted_at, skipped_at
)
SELECT $1::text, t.id, $2::text, $3::text,
       $4::date, $5::integer, $6::text,
       $7::boolean, $8::integer,
       root.id, $9::date, $10::text, true, NULL, NULL, 0,
       CASE WHEN $11::boolean THEN now() ELSE NULL END, NULL
FROM tasks t
JOIN action_items root ON root.id = $12::text AND root.task_id = t.id
WHERE t.id = $13::text
  AND task_has_permission(t.id, $14::text, 'action_item', 'update')
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND root.deleted_at IS NULL
ON CONFLICT (series_id, occurrence_date) WHERE id <> series_id DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    due_date = EXCLUDED.due_date,
    estimated_minutes = EXCLUDED.estimated_minutes,
    priority = EXCLUDED.priority,
    completed = EXCLUDED.completed,
    position = EXCLUDED.position,
    timezone = EXCLUDED.timezone,
    is_exception = true,
    deleted_at = EXCLUDED.deleted_at,
    updated_at = now()
WHERE action_items.deleted_at IS NULL
RETURNING id
`

type UpsertActionItemOverrideByTaskAndUserIDParams struct {
	ID               string
	Title            string
	Description      pgtype.Text
	DueDate          pgtype.Date
	EstimatedMinutes pgtype.Int4
	Priority         string
	Completed        bool
	Position         int32
	OccurrenceDate   pgtype.Date
	Timezone         string
	Deleted          bool
	SeriesID         string
	TaskID           string
	UserID           string
}

func (q *Queries) UpsertActionItemOverrideByTaskAndUserID(ctx context.Context, arg UpsertActionItemOverrideByTaskAndUserIDParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertActionItemOverrideByTaskAndUserID,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.DueDate,
		arg.EstimatedMinutes,
		arg.Priority,
		arg.Completed,
		arg.Position,
		arg.OccurrenceDate,
		arg.Timezone,
		arg.Deleted,
		arg.SeriesID,
		arg.TaskID,
		arg.UserID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
