// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurrence_occurrences.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listTaskScheduleSkippedOccurrencesByTaskAndUserID = `-- name: ListTaskScheduleSkippedOccurrencesByTaskAndUserID :many
SELECT child.occurrence_date
FROM task_schedules child
JOIN task_schedules root ON root.id = child.series_id AND root.series_id = root.id
JOIN tasks t ON t.id = root.task_id
WHERE child.series_id = $1::text
  AND root.task_id = $2::text
  AND child.id <> child.series_id
  AND child.deleted_at IS NULL
  AND child.skipped_at IS NOT NULL
  AND root.deleted_at IS NULL
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND task_has_permission(t.id, $3::text, 'task_schedule', 'read')
ORDER BY child.occurrence_date
`

type ListTaskScheduleSkippedOccurrencesByTaskAndUserIDParams struct {
	SeriesID string
	TaskID   string
	UserID   string
}

func (q *Queries) ListTaskScheduleSkippedOccurrencesByTaskAndUserID(ctx context.Context, arg ListTaskScheduleSkippedOccurrencesByTaskAndUserIDParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listTaskScheduleSkippedOccurrencesByTaskAndUserID, arg.SeriesID, arg.TaskID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var occurrence_date pgtype.Date
		if err := rows.Scan(&occurrence_date); err != nil {
			return nil, err
		}
		items = append(items, occurrence_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskScheduleSkippedOccurrencesForCapabilityByTaskAndUserID = `-- name: ListTaskScheduleSkippedOccurrencesForCapabilityByTaskAndUserID :many
SELECT child.occurrence_date
FROM task_schedules child
JOIN task_schedules root ON root.id = child.series_id AND root.series_id = root.id
JOIN tasks t ON t.id = root.task_id
WHERE child.series_id = $1::text
  AND root.task_id = $2::text
  AND child.id <> child.series_id
  AND child.deleted_at IS NULL
  AND child.skipped_at IS NOT NULL
  AND root.deleted_at IS NULL
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND task_has_permission(t.id, $3::text, $4::text, $5::permission_action)
ORDER BY child.occurrence_date
`

type ListTaskScheduleSkippedOccurrencesForCapabilityByTaskAndUserIDParams struct {
	SeriesID   string
	TaskID     string
	ActorID    string
	ResourceID string
	Action     PermissionAction
}

func (q *Queries) ListTaskScheduleSkippedOccurrencesForCapabilityByTaskAndUserID(ctx context.Context, arg ListTaskScheduleSkippedOccurrencesForCapabilityByTaskAndUserIDParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listTaskScheduleSkippedOccurrencesForCapabilityByTaskAndUserID,
		arg.SeriesID,
		arg.TaskID,
		arg.ActorID,
		arg.ResourceID,
		arg.Action,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var occurrence_date pgtype.Date
		if err := rows.Scan(&occurrence_date); err != nil {
			return nil, err
		}
		items = append(items, occurrence_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoItemSkippedOccurrencesByTaskAndUserID = `-- name: ListTodoItemSkippedOccurrencesByTaskAndUserID :many
SELECT child.occurrence_date
FROM todo_items child
JOIN todo_items root ON root.id = child.series_id AND root.series_id = root.id
JOIN tasks t ON t.id = root.task_id
WHERE child.series_id = $1::text
  AND root.task_id = $2::text
  AND child.id <> child.series_id
  AND child.deleted_at IS NULL
  AND child.skipped_at IS NOT NULL
  AND root.deleted_at IS NULL
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND task_has_permission(t.id, $3::text, 'todo_item', 'read')
ORDER BY child.occurrence_date
`

type ListTodoItemSkippedOccurrencesByTaskAndUserIDParams struct {
	SeriesID string
	TaskID   string
	UserID   string
}

func (q *Queries) ListTodoItemSkippedOccurrencesByTaskAndUserID(ctx context.Context, arg ListTodoItemSkippedOccurrencesByTaskAndUserIDParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listTodoItemSkippedOccurrencesByTaskAndUserID, arg.SeriesID, arg.TaskID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var occurrence_date pgtype.Date
		if err := rows.Scan(&occurrence_date); err != nil {
			return nil, err
		}
		items = append(items, occurrence_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoItemSkippedOccurrencesForCapabilityByTaskAndUserID = `-- name: ListTodoItemSkippedOccurrencesForCapabilityByTaskAndUserID :many
SELECT child.occurrence_date
FROM todo_items child
JOIN todo_items root ON root.id = child.series_id AND root.series_id = root.id
JOIN tasks t ON t.id = root.task_id
WHERE child.series_id = $1::text
  AND root.task_id = $2::text
  AND child.id <> child.series_id
  AND child.deleted_at IS NULL
  AND child.skipped_at IS NOT NULL
  AND root.deleted_at IS NULL
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND task_has_permission(t.id, $3::text, $4::text, $5::permission_action)
ORDER BY child.occurrence_date
`

type ListTodoItemSkippedOccurrencesForCapabilityByTaskAndUserIDParams struct {
	SeriesID   string
	TaskID     string
	ActorID    string
	ResourceID string
	Action     PermissionAction
}

func (q *Queries) ListTodoItemSkippedOccurrencesForCapabilityByTaskAndUserID(ctx context.Context, arg ListTodoItemSkippedOccurrencesForCapabilityByTaskAndUserIDParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listTodoItemSkippedOccurrencesForCapabilityByTaskAndUserID,
		arg.SeriesID,
		arg.TaskID,
		arg.ActorID,
		arg.ResourceID,
		arg.Action,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var occurrence_date pgtype.Date
		if err := rows.Scan(&occurrence_date); err != nil {
			return nil, err
		}
		items = append(items, occurrence_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
