// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurrence_occurrences.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listActionItemSkippedOccurrencesByTaskAndUserID = `-- name: ListActionItemSkippedOccurrencesByTaskAndUserID :many
SELECT child.occurrence_date
FROM action_items child
JOIN action_items root ON root.id = child.series_id AND root.series_id = root.id
JOIN tasks t ON t.id = root.task_id
WHERE child.series_id = $1::text
  AND root.task_id = $2::text
  AND child.id <> child.series_id
  AND child.deleted_at IS NULL
  AND child.skipped_at IS NOT NULL
  AND root.deleted_at IS NULL
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND task_has_permission(t.id, $3::text, 'action_item', 'read')
ORDER BY child.occurrence_date
`

type ListActionItemSkippedOccurrencesByTaskAndUserIDParams struct {
	SeriesID string
	TaskID   string
	UserID   string
}

func (q *Queries) ListActionItemSkippedOccurrencesByTaskAndUserID(ctx context.Context, arg ListActionItemSkippedOccurrencesByTaskAndUserIDParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listActionItemSkippedOccurrencesByTaskAndUserID, arg.SeriesID, arg.TaskID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var occurrence_date pgtype.Date
		if err := rows.Scan(&occurrence_date); err != nil {
			return nil, err
		}
		items = append(items, occurrence_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionItemSkippedOccurrencesForCapabilityByTaskAndUserID = `-- name: ListActionItemSkippedOccurrencesForCapabilityByTaskAndUserID :many
SELECT child.occurrence_date
FROM action_items child
JOIN action_items root ON root.id = child.series_id AND root.series_id = root.id
JOIN tasks t ON t.id = root.task_id
WHERE child.series_id = $1::text
  AND root.task_id = $2::text
  AND child.id <> child.series_id
  AND child.deleted_at IS NULL
  AND child.skipped_at IS NOT NULL
  AND root.deleted_at IS NULL
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND task_has_permission(t.id, $3::text, $4::text, $5::action)
ORDER BY child.occurrence_date
`

type ListActionItemSkippedOccurrencesForCapabilityByTaskAndUserIDParams struct {
	SeriesID   string
	TaskID     string
	ActorID    string
	ResourceID string
	Action     Action
}

func (q *Queries) ListActionItemSkippedOccurrencesForCapabilityByTaskAndUserID(ctx context.Context, arg ListActionItemSkippedOccurrencesForCapabilityByTaskAndUserIDParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listActionItemSkippedOccurrencesForCapabilityByTaskAndUserID,
		arg.SeriesID,
		arg.TaskID,
		arg.ActorID,
		arg.ResourceID,
		arg.Action,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var occurrence_date pgtype.Date
		if err := rows.Scan(&occurrence_date); err != nil {
			return nil, err
		}
		items = append(items, occurrence_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
