// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurrence.mut.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearActionItemFrequenciesByTaskAndUserID = `-- name: ClearActionItemFrequenciesByTaskAndUserID :exec
DELETE FROM action_item_frequencies f
USING action_items root, tasks t
WHERE f.action_item_id = $1::text
  AND root.id = f.action_item_id
  AND root.id = root.series_id
  AND root.task_id = $2::text
  AND root.deleted_at IS NULL
  AND t.id = root.task_id
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND task_has_permission(t.id, $3::text, 'action_item', 'update')
`

type ClearActionItemFrequenciesByTaskAndUserIDParams struct {
	SeriesID string
	TaskID   string
	UserID   string
}

func (q *Queries) ClearActionItemFrequenciesByTaskAndUserID(ctx context.Context, arg ClearActionItemFrequenciesByTaskAndUserIDParams) error {
	_, err := q.db.Exec(ctx, clearActionItemFrequenciesByTaskAndUserID, arg.SeriesID, arg.TaskID, arg.UserID)
	return err
}

const createActionItemFrequenciesByTaskAndUserID = `-- name: CreateActionItemFrequenciesByTaskAndUserID :exec
INSERT INTO action_item_frequencies (action_item_id, frequency)
SELECT root.id, f.frequency
FROM action_items root
JOIN tasks t ON t.id = root.task_id
CROSS JOIN unnest($1::text[]) AS f(frequency)
WHERE root.id = $2::text
  AND root.id = root.series_id
  AND root.task_id = $3::text
  AND root.deleted_at IS NULL
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND task_has_permission(t.id, $4::text, 'action_item', 'update')
  AND root.repeat_state = 'active'
ON CONFLICT DO NOTHING
`

type CreateActionItemFrequenciesByTaskAndUserIDParams struct {
	Frequencies []string
	SeriesID    string
	TaskID      string
	UserID      string
}

func (q *Queries) CreateActionItemFrequenciesByTaskAndUserID(ctx context.Context, arg CreateActionItemFrequenciesByTaskAndUserIDParams) error {
	_, err := q.db.Exec(ctx, createActionItemFrequenciesByTaskAndUserID,
		arg.Frequencies,
		arg.SeriesID,
		arg.TaskID,
		arg.UserID,
	)
	return err
}

const replaceActionItemFrequenciesByTaskAndUserID = `-- name: ReplaceActionItemFrequenciesByTaskAndUserID :exec
DELETE FROM action_item_frequencies f
USING action_items root, tasks t
WHERE f.action_item_id = $1::text
  AND root.id = f.action_item_id
  AND root.id = root.series_id
  AND root.task_id = $2::text
  AND root.deleted_at IS NULL
  AND t.id = root.task_id
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND task_has_permission(t.id, $3::text, 'action_item', 'update')
`

type ReplaceActionItemFrequenciesByTaskAndUserIDParams struct {
	SeriesID string
	TaskID   string
	UserID   string
}

func (q *Queries) ReplaceActionItemFrequenciesByTaskAndUserID(ctx context.Context, arg ReplaceActionItemFrequenciesByTaskAndUserIDParams) error {
	_, err := q.db.Exec(ctx, replaceActionItemFrequenciesByTaskAndUserID, arg.SeriesID, arg.TaskID, arg.UserID)
	return err
}

const setActionItemRecurrenceByTaskAndUserID = `-- name: SetActionItemRecurrenceByTaskAndUserID :execrows
UPDATE action_items AS root
SET repeat_state = 'active',
    frequency_anchor_date = $1::date,
    interval_weeks = $2::integer,
    updated_at = now()
FROM tasks AS t
WHERE root.id = $3::text
  AND root.series_id = root.id
  AND root.task_id = $4::text
  AND root.deleted_at IS NULL
  AND t.id = root.task_id
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND task_has_permission(t.id, $5::text, 'action_item', 'update')
  AND $2::integer > 0
`

type SetActionItemRecurrenceByTaskAndUserIDParams struct {
	FrequencyAnchorDate pgtype.Date
	IntervalWeeks       int32
	SeriesID            string
	TaskID              string
	UserID              string
}

func (q *Queries) SetActionItemRecurrenceByTaskAndUserID(ctx context.Context, arg SetActionItemRecurrenceByTaskAndUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, setActionItemRecurrenceByTaskAndUserID,
		arg.FrequencyAnchorDate,
		arg.IntervalWeeks,
		arg.SeriesID,
		arg.TaskID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stopActionItemRecurrenceByTaskAndUserID = `-- name: StopActionItemRecurrenceByTaskAndUserID :execrows
UPDATE action_items AS root
SET repeat_state = 'stopped', interval_weeks = 0, updated_at = now()
FROM tasks AS t
WHERE root.id = $1::text
  AND root.id = root.series_id
  AND root.task_id = $2::text
  AND root.deleted_at IS NULL
  AND t.id = root.task_id
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND task_has_permission(t.id, $3::text, 'action_item', 'update')
  AND root.repeat_state IN ('active', 'stopped')
`

type StopActionItemRecurrenceByTaskAndUserIDParams struct {
	SeriesID string
	TaskID   string
	UserID   string
}

func (q *Queries) StopActionItemRecurrenceByTaskAndUserID(ctx context.Context, arg StopActionItemRecurrenceByTaskAndUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, stopActionItemRecurrenceByTaskAndUserID, arg.SeriesID, arg.TaskID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
