// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurrence.mut.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearTaskScheduleFrequenciesByTaskAndUserID = `-- name: ClearTaskScheduleFrequenciesByTaskAndUserID :exec
DELETE FROM task_schedule_frequencies f
USING task_schedules root, tasks t
WHERE f.task_schedule_id = $1::text
  AND root.id = f.task_schedule_id
  AND root.id = root.series_id
  AND root.task_id = $2::text
  AND root.deleted_at IS NULL
  AND t.id = root.task_id
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND task_has_permission(t.id, $3::text, 'task_schedule', 'update')
`

type ClearTaskScheduleFrequenciesByTaskAndUserIDParams struct {
	SeriesID string
	TaskID   string
	UserID   string
}

func (q *Queries) ClearTaskScheduleFrequenciesByTaskAndUserID(ctx context.Context, arg ClearTaskScheduleFrequenciesByTaskAndUserIDParams) error {
	_, err := q.db.Exec(ctx, clearTaskScheduleFrequenciesByTaskAndUserID, arg.SeriesID, arg.TaskID, arg.UserID)
	return err
}

const clearTodoItemFrequenciesByTaskAndUserID = `-- name: ClearTodoItemFrequenciesByTaskAndUserID :exec
DELETE FROM todo_item_frequencies f
USING todo_items root, tasks t
WHERE f.todo_item_id = $1::text
  AND root.id = f.todo_item_id
  AND root.id = root.series_id
  AND root.task_id = $2::text
  AND root.deleted_at IS NULL
  AND t.id = root.task_id
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND task_has_permission(t.id, $3::text, 'todo_item', 'update')
`

type ClearTodoItemFrequenciesByTaskAndUserIDParams struct {
	SeriesID string
	TaskID   string
	UserID   string
}

func (q *Queries) ClearTodoItemFrequenciesByTaskAndUserID(ctx context.Context, arg ClearTodoItemFrequenciesByTaskAndUserIDParams) error {
	_, err := q.db.Exec(ctx, clearTodoItemFrequenciesByTaskAndUserID, arg.SeriesID, arg.TaskID, arg.UserID)
	return err
}

const createTaskScheduleFrequenciesByTaskAndUserID = `-- name: CreateTaskScheduleFrequenciesByTaskAndUserID :exec
INSERT INTO task_schedule_frequencies (task_schedule_id, frequency)
SELECT root.id, f.frequency
FROM task_schedules root
JOIN tasks t ON t.id = root.task_id
CROSS JOIN unnest($1::text[]) AS f(frequency)
WHERE root.id = $2::text
  AND root.id = root.series_id
  AND root.task_id = $3::text
  AND root.deleted_at IS NULL
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND task_has_permission(t.id, $4::text, 'task_schedule', 'update')
  AND root.repeat_state = 'active'
ON CONFLICT DO NOTHING
`

type CreateTaskScheduleFrequenciesByTaskAndUserIDParams struct {
	Frequencies []string
	SeriesID    string
	TaskID      string
	UserID      string
}

func (q *Queries) CreateTaskScheduleFrequenciesByTaskAndUserID(ctx context.Context, arg CreateTaskScheduleFrequenciesByTaskAndUserIDParams) error {
	_, err := q.db.Exec(ctx, createTaskScheduleFrequenciesByTaskAndUserID,
		arg.Frequencies,
		arg.SeriesID,
		arg.TaskID,
		arg.UserID,
	)
	return err
}

const createTodoItemFrequenciesByTaskAndUserID = `-- name: CreateTodoItemFrequenciesByTaskAndUserID :exec
INSERT INTO todo_item_frequencies (todo_item_id, frequency)
SELECT root.id, f.frequency
FROM todo_items root
JOIN tasks t ON t.id = root.task_id
CROSS JOIN unnest($1::text[]) AS f(frequency)
WHERE root.id = $2::text
  AND root.id = root.series_id
  AND root.task_id = $3::text
  AND root.deleted_at IS NULL
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND task_has_permission(t.id, $4::text, 'todo_item', 'update')
  AND root.repeat_state = 'active'
ON CONFLICT DO NOTHING
`

type CreateTodoItemFrequenciesByTaskAndUserIDParams struct {
	Frequencies []string
	SeriesID    string
	TaskID      string
	UserID      string
}

func (q *Queries) CreateTodoItemFrequenciesByTaskAndUserID(ctx context.Context, arg CreateTodoItemFrequenciesByTaskAndUserIDParams) error {
	_, err := q.db.Exec(ctx, createTodoItemFrequenciesByTaskAndUserID,
		arg.Frequencies,
		arg.SeriesID,
		arg.TaskID,
		arg.UserID,
	)
	return err
}

const replaceTaskScheduleFrequenciesByTaskAndUserID = `-- name: ReplaceTaskScheduleFrequenciesByTaskAndUserID :exec
DELETE FROM task_schedule_frequencies f
USING task_schedules root, tasks t
WHERE f.task_schedule_id = $1::text
  AND root.id = f.task_schedule_id
  AND root.id = root.series_id
  AND root.task_id = $2::text
  AND root.deleted_at IS NULL
  AND t.id = root.task_id
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND task_has_permission(t.id, $3::text, 'task_schedule', 'update')
`

type ReplaceTaskScheduleFrequenciesByTaskAndUserIDParams struct {
	SeriesID string
	TaskID   string
	UserID   string
}

func (q *Queries) ReplaceTaskScheduleFrequenciesByTaskAndUserID(ctx context.Context, arg ReplaceTaskScheduleFrequenciesByTaskAndUserIDParams) error {
	_, err := q.db.Exec(ctx, replaceTaskScheduleFrequenciesByTaskAndUserID, arg.SeriesID, arg.TaskID, arg.UserID)
	return err
}

const replaceTodoItemFrequenciesByTaskAndUserID = `-- name: ReplaceTodoItemFrequenciesByTaskAndUserID :exec
DELETE FROM todo_item_frequencies f
USING todo_items root, tasks t
WHERE f.todo_item_id = $1::text
  AND root.id = f.todo_item_id
  AND root.id = root.series_id
  AND root.task_id = $2::text
  AND root.deleted_at IS NULL
  AND t.id = root.task_id
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND task_has_permission(t.id, $3::text, 'todo_item', 'update')
`

type ReplaceTodoItemFrequenciesByTaskAndUserIDParams struct {
	SeriesID string
	TaskID   string
	UserID   string
}

func (q *Queries) ReplaceTodoItemFrequenciesByTaskAndUserID(ctx context.Context, arg ReplaceTodoItemFrequenciesByTaskAndUserIDParams) error {
	_, err := q.db.Exec(ctx, replaceTodoItemFrequenciesByTaskAndUserID, arg.SeriesID, arg.TaskID, arg.UserID)
	return err
}

const setTaskScheduleRecurrenceByTaskAndUserID = `-- name: SetTaskScheduleRecurrenceByTaskAndUserID :execrows
UPDATE task_schedules AS root
SET repeat_state = 'active',
    frequency_anchor_date = $1::date,
    interval_weeks = $2::integer,
    updated_at = now()
FROM tasks AS t
WHERE root.id = $3::text
  AND root.series_id = root.id
  AND root.task_id = $4::text
  AND root.deleted_at IS NULL
  AND t.id = root.task_id
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND task_has_permission(t.id, $5::text, 'task_schedule', 'update')
  AND $2::integer > 0
`

type SetTaskScheduleRecurrenceByTaskAndUserIDParams struct {
	FrequencyAnchorDate pgtype.Date
	IntervalWeeks       int32
	SeriesID            string
	TaskID              string
	UserID              string
}

func (q *Queries) SetTaskScheduleRecurrenceByTaskAndUserID(ctx context.Context, arg SetTaskScheduleRecurrenceByTaskAndUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTaskScheduleRecurrenceByTaskAndUserID,
		arg.FrequencyAnchorDate,
		arg.IntervalWeeks,
		arg.SeriesID,
		arg.TaskID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTodoItemRecurrenceByTaskAndUserID = `-- name: SetTodoItemRecurrenceByTaskAndUserID :execrows
UPDATE todo_items AS root
SET repeat_state = 'active',
    frequency_anchor_date = $1::date,
    interval_weeks = $2::integer,
    updated_at = now()
FROM tasks AS t
WHERE root.id = $3::text
  AND root.series_id = root.id
  AND root.task_id = $4::text
  AND root.deleted_at IS NULL
  AND t.id = root.task_id
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND task_has_permission(t.id, $5::text, 'todo_item', 'update')
  AND $2::integer > 0
`

type SetTodoItemRecurrenceByTaskAndUserIDParams struct {
	FrequencyAnchorDate pgtype.Date
	IntervalWeeks       int32
	SeriesID            string
	TaskID              string
	UserID              string
}

func (q *Queries) SetTodoItemRecurrenceByTaskAndUserID(ctx context.Context, arg SetTodoItemRecurrenceByTaskAndUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTodoItemRecurrenceByTaskAndUserID,
		arg.FrequencyAnchorDate,
		arg.IntervalWeeks,
		arg.SeriesID,
		arg.TaskID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stopTaskScheduleRecurrenceByTaskAndUserID = `-- name: StopTaskScheduleRecurrenceByTaskAndUserID :execrows
UPDATE task_schedules AS root
SET repeat_state = 'stopped', interval_weeks = 0, updated_at = now()
FROM tasks AS t
WHERE root.id = $1::text
  AND root.id = root.series_id
  AND root.task_id = $2::text
  AND root.deleted_at IS NULL
  AND t.id = root.task_id
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND task_has_permission(t.id, $3::text, 'task_schedule', 'update')
  AND root.repeat_state IN ('active', 'stopped')
`

type StopTaskScheduleRecurrenceByTaskAndUserIDParams struct {
	SeriesID string
	TaskID   string
	UserID   string
}

func (q *Queries) StopTaskScheduleRecurrenceByTaskAndUserID(ctx context.Context, arg StopTaskScheduleRecurrenceByTaskAndUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, stopTaskScheduleRecurrenceByTaskAndUserID, arg.SeriesID, arg.TaskID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stopTodoItemRecurrenceByTaskAndUserID = `-- name: StopTodoItemRecurrenceByTaskAndUserID :execrows
UPDATE todo_items AS root
SET repeat_state = 'stopped', interval_weeks = 0, updated_at = now()
FROM tasks AS t
WHERE root.id = $1::text
  AND root.id = root.series_id
  AND root.task_id = $2::text
  AND root.deleted_at IS NULL
  AND t.id = root.task_id
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND task_has_permission(t.id, $3::text, 'todo_item', 'update')
  AND root.repeat_state IN ('active', 'stopped')
`

type StopTodoItemRecurrenceByTaskAndUserIDParams struct {
	SeriesID string
	TaskID   string
	UserID   string
}

func (q *Queries) StopTodoItemRecurrenceByTaskAndUserID(ctx context.Context, arg StopTodoItemRecurrenceByTaskAndUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, stopTodoItemRecurrenceByTaskAndUserID, arg.SeriesID, arg.TaskID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
