// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revisions.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listProjectRevisionsByActor = `-- name: ListProjectRevisionsByActor :many
SELECT pr.id, pr.revision, pr.user_id, pr.type, pr.title, pr.goal, pr.description, pr.priority, pr.start_date, pr.end_date, pr.deleted_at, pr.created_at, pr.updated_at, pr.changed_by, pr.changed_at, pr.status
FROM project_revisions AS pr
JOIN projects AS p ON p.id = pr.id
WHERE pr.id = $1::text
  AND (
      (p.deleted_at IS NULL AND project_has_permission(p.id, $2::text, 'project', 'read'))
      OR (p.deleted_at IS NOT NULL AND (
          p.user_id = $2::text
          OR project_has_permission(p.id, $2::text, 'deleted_history', 'read')
      ))
  )
  AND ($3::integer IS NULL OR pr.revision < $3::integer)
ORDER BY pr.revision DESC
LIMIT $4::integer
`

type ListProjectRevisionsByActorParams struct {
	ID             string
	ActorID        string
	CursorRevision pgtype.Int4
	PageLimit      int32
}

func (q *Queries) ListProjectRevisionsByActor(ctx context.Context, arg ListProjectRevisionsByActorParams) ([]ProjectRevision, error) {
	rows, err := q.db.Query(ctx, listProjectRevisionsByActor,
		arg.ID,
		arg.ActorID,
		arg.CursorRevision,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectRevision
	for rows.Next() {
		var i ProjectRevision
		if err := rows.Scan(
			&i.ID,
			&i.Revision,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Goal,
			&i.Description,
			&i.Priority,
			&i.StartDate,
			&i.EndDate,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChangedBy,
			&i.ChangedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleRevisionsByActor = `-- name: ListScheduleRevisionsByActor :many
SELECT sr.id, sr.revision, sr.user_id, sr.project_id, sr.assignee_id, sr.title, sr.description, sr.location, sr.start_at, sr.end_at, sr.series_id, sr.occurrence_date, sr.timezone, sr.is_exception, sr.repeat_state, sr.frequency_anchor_date, sr.interval_weeks, sr.completed, sr.deleted_at, sr.skipped_at, sr.frequencies, sr.created_at, sr.updated_at, sr.changed_by, sr.changed_at
FROM schedule_revisions AS sr
JOIN schedules AS s ON s.id = sr.id
LEFT JOIN projects AS p ON p.id = s.project_id
WHERE sr.id = $1::text
  AND (
      (s.deleted_at IS NULL AND (p.id IS NULL OR p.deleted_at IS NULL)
       AND schedule_has_permission(s.id, $2::text, 'schedule', 'read'))
      OR ((s.deleted_at IS NOT NULL OR p.deleted_at IS NOT NULL)
       AND (s.user_id = $2::text
            OR (p.id IS NOT NULL AND project_has_permission(p.id, $2::text, 'deleted_history', 'read'))))
  )
  AND ($3::integer IS NULL OR sr.revision < $3::integer)
ORDER BY sr.revision DESC
LIMIT $4::integer
`

type ListScheduleRevisionsByActorParams struct {
	ID             string
	ActorID        string
	CursorRevision pgtype.Int4
	PageLimit      int32
}

func (q *Queries) ListScheduleRevisionsByActor(ctx context.Context, arg ListScheduleRevisionsByActorParams) ([]ScheduleRevision, error) {
	rows, err := q.db.Query(ctx, listScheduleRevisionsByActor,
		arg.ID,
		arg.ActorID,
		arg.CursorRevision,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduleRevision
	for rows.Next() {
		var i ScheduleRevision
		if err := rows.Scan(
			&i.ID,
			&i.Revision,
			&i.UserID,
			&i.ProjectID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartAt,
			&i.EndAt,
			&i.SeriesID,
			&i.OccurrenceDate,
			&i.Timezone,
			&i.IsException,
			&i.RepeatState,
			&i.FrequencyAnchorDate,
			&i.IntervalWeeks,
			&i.Completed,
			&i.DeletedAt,
			&i.SkippedAt,
			&i.Frequencies,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChangedBy,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskRevisionsByActor = `-- name: ListTaskRevisionsByActor :many
SELECT tr.id, tr.revision, tr.user_id, tr.project_id, tr.assignee_id, tr.title, tr.description, tr.due_date, tr.estimated_minutes, tr.actual_minutes, tr.priority, tr.status, tr.deleted_at, tr.created_at, tr.updated_at, tr.changed_by, tr.changed_at
FROM task_revisions AS tr
JOIN tasks AS t ON t.id = tr.id
LEFT JOIN projects AS p ON p.id = t.project_id
WHERE tr.id = $1::text
  AND (
      (t.deleted_at IS NULL AND (p.id IS NULL OR p.deleted_at IS NULL)
       AND task_has_permission(t.id, $2::text, 'task', 'read'))
      OR (t.deleted_at IS NOT NULL OR p.deleted_at IS NOT NULL)
       AND (t.user_id = $2::text
            OR (p.id IS NOT NULL AND project_has_permission(p.id, $2::text, 'deleted_history', 'read')))
  )
  AND ($3::integer IS NULL OR tr.revision < $3::integer)
ORDER BY tr.revision DESC
LIMIT $4::integer
`

type ListTaskRevisionsByActorParams struct {
	ID             string
	ActorID        string
	CursorRevision pgtype.Int4
	PageLimit      int32
}

func (q *Queries) ListTaskRevisionsByActor(ctx context.Context, arg ListTaskRevisionsByActorParams) ([]TaskRevision, error) {
	rows, err := q.db.Query(ctx, listTaskRevisionsByActor,
		arg.ID,
		arg.ActorID,
		arg.CursorRevision,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskRevision
	for rows.Next() {
		var i TaskRevision
		if err := rows.Scan(
			&i.ID,
			&i.Revision,
			&i.UserID,
			&i.ProjectID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Priority,
			&i.Status,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChangedBy,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
