// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: roles.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPermissions = `-- name: ListPermissions :many
SELECT p.permission_id, p.resource_id, mr.name AS resource_name,
       p.action::text AS action, p.effect::text AS effect, p.description
FROM permissions AS p
JOIN managed_resources AS mr ON mr.resource_id = p.resource_id
ORDER BY p.resource_id, p.action, p.effect
`

type ListPermissionsRow struct {
	PermissionID int64
	ResourceID   string
	ResourceName string
	Action       string
	Effect       string
	Description  string
}

func (q *Queries) ListPermissions(ctx context.Context) ([]ListPermissionsRow, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermissionsRow
	for rows.Next() {
		var i ListPermissionsRow
		if err := rows.Scan(
			&i.PermissionID,
			&i.ResourceID,
			&i.ResourceName,
			&i.Action,
			&i.Effect,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesWithPermissions = `-- name: ListRolesWithPermissions :many
SELECT r.role_id, r.name,
       p.permission_id,
       p.resource_id,
       mr.name AS resource_name,
       p.action::text AS action,
       p.effect::text AS effect,
       p.description
FROM roles AS r
LEFT JOIN role_permissions AS rp ON rp.role_id = r.role_id
LEFT JOIN permissions AS p ON p.permission_id = rp.permission_id
LEFT JOIN managed_resources AS mr ON mr.resource_id = p.resource_id
ORDER BY r.role_id, p.resource_id, p.action, p.effect
`

type ListRolesWithPermissionsRow struct {
	RoleID       string
	Name         string
	PermissionID pgtype.Int8
	ResourceID   pgtype.Text
	ResourceName pgtype.Text
	Action       string
	Effect       string
	Description  pgtype.Text
}

func (q *Queries) ListRolesWithPermissions(ctx context.Context) ([]ListRolesWithPermissionsRow, error) {
	rows, err := q.db.Query(ctx, listRolesWithPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesWithPermissionsRow
	for rows.Next() {
		var i ListRolesWithPermissionsRow
		if err := rows.Scan(
			&i.RoleID,
			&i.Name,
			&i.PermissionID,
			&i.ResourceID,
			&i.ResourceName,
			&i.Action,
			&i.Effect,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
