// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: schedules.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getScheduleByUserIDForPermission = `-- name: GetScheduleByUserIDForPermission :one
SELECT s.id, s.user_id, s.project_id, s.assignee_id, s.title, s.description, s.location,
       r.interval_weeks, r.repeat_state, r.frequency_anchor_date,
       s.series_id, s.occurrence_date, s.timezone, s.is_exception, s.completed,
       (s.deleted_at IS NOT NULL) AS deleted,
       ARRAY(SELECT f.frequency FROM schedule_frequencies f WHERE f.schedule_id = s.series_id ORDER BY f.frequency)::text[] AS frequencies,
       s.start_at, s.end_at, s.created_at, s.updated_at, s.revision, s.changed_by
FROM schedules s
JOIN schedules r ON r.id = s.series_id AND r.user_id = s.user_id
WHERE s.id = $1::text
  AND schedule_has_permission(s.id, $2::text, $3::text, $4::action)
  AND s.deleted_at IS NULL
`

type GetScheduleByUserIDForPermissionParams struct {
	ID         string
	ActorID    string
	ResourceID string
	Action     Action
}

type GetScheduleByUserIDForPermissionRow struct {
	ID                  string
	UserID              string
	ProjectID           pgtype.Text
	AssigneeID          string
	Title               string
	Description         pgtype.Text
	Location            pgtype.Text
	IntervalWeeks       int32
	RepeatState         pgtype.Text
	FrequencyAnchorDate pgtype.Date
	SeriesID            string
	OccurrenceDate      pgtype.Date
	Timezone            string
	IsException         bool
	Completed           bool
	Deleted             interface{}
	Frequencies         []string
	StartAt             pgtype.Timestamptz
	EndAt               pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Revision            int32
	ChangedBy           string
}

func (q *Queries) GetScheduleByUserIDForPermission(ctx context.Context, arg GetScheduleByUserIDForPermissionParams) (GetScheduleByUserIDForPermissionRow, error) {
	row := q.db.QueryRow(ctx, getScheduleByUserIDForPermission,
		arg.ID,
		arg.ActorID,
		arg.ResourceID,
		arg.Action,
	)
	var i GetScheduleByUserIDForPermissionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.IntervalWeeks,
		&i.RepeatState,
		&i.FrequencyAnchorDate,
		&i.SeriesID,
		&i.OccurrenceDate,
		&i.Timezone,
		&i.IsException,
		&i.Completed,
		&i.Deleted,
		&i.Frequencies,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
		&i.ChangedBy,
	)
	return i, err
}

const getScheduleProjectByUserIDForPermission = `-- name: GetScheduleProjectByUserIDForPermission :one
SELECT s.project_id
FROM schedules AS s
WHERE s.id = $1::text
  AND s.id = s.series_id
  AND s.deleted_at IS NULL
  AND schedule_has_permission(s.id, $2::text, $3::text, $4::action)
`

type GetScheduleProjectByUserIDForPermissionParams struct {
	SeriesID   string
	ActorID    string
	ResourceID string
	Action     Action
}

func (q *Queries) GetScheduleProjectByUserIDForPermission(ctx context.Context, arg GetScheduleProjectByUserIDForPermissionParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getScheduleProjectByUserIDForPermission,
		arg.SeriesID,
		arg.ActorID,
		arg.ResourceID,
		arg.Action,
	)
	var project_id pgtype.Text
	err := row.Scan(&project_id)
	return project_id, err
}

const listActiveScheduleSeriesByAssigneeUserID = `-- name: ListActiveScheduleSeriesByAssigneeUserID :many
SELECT s.id, s.user_id, s.project_id, s.assignee_id, s.title, s.description, s.location,
       s.interval_weeks, s.repeat_state, s.frequency_anchor_date,
       s.series_id, s.occurrence_date, s.timezone, s.is_exception, s.completed,
       (s.deleted_at IS NOT NULL) AS deleted,
       ARRAY(SELECT f.frequency FROM schedule_frequencies f WHERE f.schedule_id = s.id ORDER BY f.frequency)::text[] AS frequencies,
       s.start_at, s.end_at, s.created_at, s.updated_at, s.revision, s.changed_by
FROM schedules s
WHERE s.id = s.series_id AND s.assignee_id = $1::text
  AND s.repeat_state = 'active' AND s.deleted_at IS NULL
  AND (s.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = s.project_id AND p.deleted_at IS NULL))
  AND schedule_has_permission(s.id, $1::text, 'schedule', 'read')
ORDER BY s.id
`

type ListActiveScheduleSeriesByAssigneeUserIDRow struct {
	ID                  string
	UserID              string
	ProjectID           pgtype.Text
	AssigneeID          string
	Title               string
	Description         pgtype.Text
	Location            pgtype.Text
	IntervalWeeks       int32
	RepeatState         pgtype.Text
	FrequencyAnchorDate pgtype.Date
	SeriesID            string
	OccurrenceDate      pgtype.Date
	Timezone            string
	IsException         bool
	Completed           bool
	Deleted             interface{}
	Frequencies         []string
	StartAt             pgtype.Timestamptz
	EndAt               pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Revision            int32
	ChangedBy           string
}

func (q *Queries) ListActiveScheduleSeriesByAssigneeUserID(ctx context.Context, userID string) ([]ListActiveScheduleSeriesByAssigneeUserIDRow, error) {
	rows, err := q.db.Query(ctx, listActiveScheduleSeriesByAssigneeUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveScheduleSeriesByAssigneeUserIDRow
	for rows.Next() {
		var i ListActiveScheduleSeriesByAssigneeUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.IntervalWeeks,
			&i.RepeatState,
			&i.FrequencyAnchorDate,
			&i.SeriesID,
			&i.OccurrenceDate,
			&i.Timezone,
			&i.IsException,
			&i.Completed,
			&i.Deleted,
			&i.Frequencies,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Revision,
			&i.ChangedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEligibleScheduleAssignees = `-- name: ListEligibleScheduleAssignees :many
SELECT u.id, u.first_name, u.last_name, u.email, (u.id = s.user_id) AS is_owner
FROM schedules s
JOIN users u ON u.id = s.user_id
WHERE s.id = $1::text
  AND schedule_has_permission(s.id, $2::text, 'schedule_assignment', 'update')
UNION
SELECT u.id, u.first_name, u.last_name, u.email, false AS is_owner
FROM schedules s
JOIN project_members pm ON pm.project_id = s.project_id
JOIN users u ON u.id = pm.user_id
WHERE s.id = $1::text
  AND s.project_id IS NOT NULL
  AND schedule_has_permission(s.id, $2::text, 'schedule_assignment', 'update')
ORDER BY is_owner DESC, last_name, first_name, id
`

type ListEligibleScheduleAssigneesParams struct {
	ID      string
	ActorID string
}

type ListEligibleScheduleAssigneesRow struct {
	ID        string
	FirstName string
	LastName  string
	Email     string
	IsOwner   bool
}

func (q *Queries) ListEligibleScheduleAssignees(ctx context.Context, arg ListEligibleScheduleAssigneesParams) ([]ListEligibleScheduleAssigneesRow, error) {
	rows, err := q.db.Query(ctx, listEligibleScheduleAssignees, arg.ID, arg.ActorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEligibleScheduleAssigneesRow
	for rows.Next() {
		var i ListEligibleScheduleAssigneesRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.IsOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleSkippedOccurrencesByUserID = `-- name: ListScheduleSkippedOccurrencesByUserID :many
SELECT child.occurrence_date
FROM schedules child
JOIN schedules root ON root.id = child.series_id AND root.user_id = child.user_id AND root.series_id = root.id
WHERE child.series_id = $1::text
  AND child.id <> child.series_id AND child.deleted_at IS NULL AND child.skipped_at IS NOT NULL
  AND root.deleted_at IS NULL
  AND schedule_has_permission(root.id, $2::text, 'schedule', 'read')
ORDER BY child.occurrence_date
`

type ListScheduleSkippedOccurrencesByUserIDParams struct {
	SeriesID string
	UserID   string
}

func (q *Queries) ListScheduleSkippedOccurrencesByUserID(ctx context.Context, arg ListScheduleSkippedOccurrencesByUserIDParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listScheduleSkippedOccurrencesByUserID, arg.SeriesID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var occurrence_date pgtype.Date
		if err := rows.Scan(&occurrence_date); err != nil {
			return nil, err
		}
		items = append(items, occurrence_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleSkippedOccurrencesForPermission = `-- name: ListScheduleSkippedOccurrencesForPermission :many
SELECT child.occurrence_date
FROM schedules child
JOIN schedules root ON root.id = child.series_id AND root.user_id = child.user_id AND root.series_id = root.id
WHERE child.series_id = $1::text
  AND child.id <> child.series_id AND child.deleted_at IS NULL AND child.skipped_at IS NOT NULL
  AND root.deleted_at IS NULL
  AND schedule_has_permission(root.id, $2::text, $3::text, $4::action)
ORDER BY child.occurrence_date
`

type ListScheduleSkippedOccurrencesForPermissionParams struct {
	SeriesID   string
	ActorID    string
	ResourceID string
	Action     Action
}

func (q *Queries) ListScheduleSkippedOccurrencesForPermission(ctx context.Context, arg ListScheduleSkippedOccurrencesForPermissionParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listScheduleSkippedOccurrencesForPermission,
		arg.SeriesID,
		arg.ActorID,
		arg.ResourceID,
		arg.Action,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var occurrence_date pgtype.Date
		if err := rows.Scan(&occurrence_date); err != nil {
			return nil, err
		}
		items = append(items, occurrence_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesForOccurrenceCommandByUserID = `-- name: ListSchedulesForOccurrenceCommandByUserID :many
SELECT s.id, s.user_id, s.project_id, s.assignee_id, s.title, s.description, s.location,
       r.interval_weeks, r.repeat_state, r.frequency_anchor_date,
       s.series_id, s.occurrence_date, s.timezone, s.is_exception, s.completed,
       (s.deleted_at IS NOT NULL) AS deleted,
       ARRAY(SELECT f.frequency FROM schedule_frequencies f WHERE f.schedule_id = s.series_id ORDER BY f.frequency)::text[] AS frequencies,
       s.start_at, s.end_at, s.created_at, s.updated_at, s.revision, s.changed_by
FROM schedules s
JOIN schedules r ON r.id = s.series_id AND r.user_id = s.user_id
WHERE s.series_id = $1::text
  AND schedule_has_permission(s.id, $2::text, $3::text, $4::action)
ORDER BY s.start_at, s.occurrence_date, s.id
`

type ListSchedulesForOccurrenceCommandByUserIDParams struct {
	SeriesID   string
	ActorID    string
	ResourceID string
	Action     Action
}

type ListSchedulesForOccurrenceCommandByUserIDRow struct {
	ID                  string
	UserID              string
	ProjectID           pgtype.Text
	AssigneeID          string
	Title               string
	Description         pgtype.Text
	Location            pgtype.Text
	IntervalWeeks       int32
	RepeatState         pgtype.Text
	FrequencyAnchorDate pgtype.Date
	SeriesID            string
	OccurrenceDate      pgtype.Date
	Timezone            string
	IsException         bool
	Completed           bool
	Deleted             interface{}
	Frequencies         []string
	StartAt             pgtype.Timestamptz
	EndAt               pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Revision            int32
	ChangedBy           string
}

func (q *Queries) ListSchedulesForOccurrenceCommandByUserID(ctx context.Context, arg ListSchedulesForOccurrenceCommandByUserIDParams) ([]ListSchedulesForOccurrenceCommandByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listSchedulesForOccurrenceCommandByUserID,
		arg.SeriesID,
		arg.ActorID,
		arg.ResourceID,
		arg.Action,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchedulesForOccurrenceCommandByUserIDRow
	for rows.Next() {
		var i ListSchedulesForOccurrenceCommandByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.IntervalWeeks,
			&i.RepeatState,
			&i.FrequencyAnchorDate,
			&i.SeriesID,
			&i.OccurrenceDate,
			&i.Timezone,
			&i.IsException,
			&i.Completed,
			&i.Deleted,
			&i.Frequencies,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Revision,
			&i.ChangedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesForOccurrenceProjectionByAssigneeUserID = `-- name: ListSchedulesForOccurrenceProjectionByAssigneeUserID :many
SELECT s.id, s.user_id, s.project_id, s.assignee_id, s.title, s.description, s.location,
       r.interval_weeks, r.repeat_state, r.frequency_anchor_date,
       s.series_id, s.occurrence_date, s.timezone, s.is_exception, s.completed,
       (s.deleted_at IS NOT NULL) AS deleted,
       ARRAY(SELECT f.frequency FROM schedule_frequencies f WHERE f.schedule_id = s.series_id ORDER BY f.frequency)::text[] AS frequencies,
       s.start_at, s.end_at, s.created_at, s.updated_at, s.revision, s.changed_by
FROM schedules s
JOIN schedules r ON r.id = s.series_id AND r.user_id = s.user_id
WHERE s.assignee_id = $1::text
  AND (s.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = s.project_id AND p.deleted_at IS NULL))
  AND (
      s.user_id = $1::text
      OR (
          s.project_id IS NOT NULL
          AND EXISTS (SELECT 1 FROM projects p WHERE p.id = s.project_id AND p.deleted_at IS NULL)
          AND project_has_permission(s.project_id, $1::text, 'schedule', 'read')
      )
  )
ORDER BY s.start_at, s.id
`

type ListSchedulesForOccurrenceProjectionByAssigneeUserIDRow struct {
	ID                  string
	UserID              string
	ProjectID           pgtype.Text
	AssigneeID          string
	Title               string
	Description         pgtype.Text
	Location            pgtype.Text
	IntervalWeeks       int32
	RepeatState         pgtype.Text
	FrequencyAnchorDate pgtype.Date
	SeriesID            string
	OccurrenceDate      pgtype.Date
	Timezone            string
	IsException         bool
	Completed           bool
	Deleted             interface{}
	Frequencies         []string
	StartAt             pgtype.Timestamptz
	EndAt               pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Revision            int32
	ChangedBy           string
}

func (q *Queries) ListSchedulesForOccurrenceProjectionByAssigneeUserID(ctx context.Context, userID string) ([]ListSchedulesForOccurrenceProjectionByAssigneeUserIDRow, error) {
	rows, err := q.db.Query(ctx, listSchedulesForOccurrenceProjectionByAssigneeUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchedulesForOccurrenceProjectionByAssigneeUserIDRow
	for rows.Next() {
		var i ListSchedulesForOccurrenceProjectionByAssigneeUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.IntervalWeeks,
			&i.RepeatState,
			&i.FrequencyAnchorDate,
			&i.SeriesID,
			&i.OccurrenceDate,
			&i.Timezone,
			&i.IsException,
			&i.Completed,
			&i.Deleted,
			&i.Frequencies,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Revision,
			&i.ChangedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesForOccurrenceProjectionByProjectAndUserID = `-- name: ListSchedulesForOccurrenceProjectionByProjectAndUserID :many
SELECT s.id, s.user_id, s.project_id, s.assignee_id, s.title, s.description, s.location,
       r.interval_weeks, r.repeat_state, r.frequency_anchor_date,
       s.series_id, s.occurrence_date, s.timezone, s.is_exception, s.completed,
       (s.deleted_at IS NOT NULL) AS deleted,
       ARRAY(SELECT f.frequency FROM schedule_frequencies f WHERE f.schedule_id = s.series_id ORDER BY f.frequency)::text[] AS frequencies,
       s.start_at, s.end_at, s.created_at, s.updated_at, s.revision, s.changed_by
FROM schedules s
JOIN schedules r ON r.id = s.series_id AND r.user_id = s.user_id
WHERE s.project_id = $1::text
  AND EXISTS (SELECT 1 FROM projects p WHERE p.id = s.project_id AND p.deleted_at IS NULL)
  AND (
      s.user_id = $2::text
      OR (
          EXISTS (SELECT 1 FROM projects p WHERE p.id = s.project_id AND p.deleted_at IS NULL)
          AND project_has_permission(s.project_id, $2::text, 'schedule', 'read')
      )
  )
ORDER BY s.start_at, s.id
`

type ListSchedulesForOccurrenceProjectionByProjectAndUserIDParams struct {
	ProjectID string
	UserID    string
}

type ListSchedulesForOccurrenceProjectionByProjectAndUserIDRow struct {
	ID                  string
	UserID              string
	ProjectID           pgtype.Text
	AssigneeID          string
	Title               string
	Description         pgtype.Text
	Location            pgtype.Text
	IntervalWeeks       int32
	RepeatState         pgtype.Text
	FrequencyAnchorDate pgtype.Date
	SeriesID            string
	OccurrenceDate      pgtype.Date
	Timezone            string
	IsException         bool
	Completed           bool
	Deleted             interface{}
	Frequencies         []string
	StartAt             pgtype.Timestamptz
	EndAt               pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Revision            int32
	ChangedBy           string
}

func (q *Queries) ListSchedulesForOccurrenceProjectionByProjectAndUserID(ctx context.Context, arg ListSchedulesForOccurrenceProjectionByProjectAndUserIDParams) ([]ListSchedulesForOccurrenceProjectionByProjectAndUserIDRow, error) {
	rows, err := q.db.Query(ctx, listSchedulesForOccurrenceProjectionByProjectAndUserID, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchedulesForOccurrenceProjectionByProjectAndUserIDRow
	for rows.Next() {
		var i ListSchedulesForOccurrenceProjectionByProjectAndUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.IntervalWeeks,
			&i.RepeatState,
			&i.FrequencyAnchorDate,
			&i.SeriesID,
			&i.OccurrenceDate,
			&i.Timezone,
			&i.IsException,
			&i.Completed,
			&i.Deleted,
			&i.Frequencies,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Revision,
			&i.ChangedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesForOccurrenceProjectionByUserID = `-- name: ListSchedulesForOccurrenceProjectionByUserID :many
SELECT s.id, s.user_id, s.project_id, s.assignee_id, s.title, s.description, s.location,
       r.interval_weeks, r.repeat_state, r.frequency_anchor_date,
       s.series_id, s.occurrence_date, s.timezone, s.is_exception, s.completed,
       (s.deleted_at IS NOT NULL) AS deleted,
       ARRAY(SELECT f.frequency FROM schedule_frequencies f WHERE f.schedule_id = s.series_id ORDER BY f.frequency)::text[] AS frequencies,
       s.start_at, s.end_at, s.created_at, s.updated_at, s.revision, s.changed_by
FROM schedules s
JOIN schedules r ON r.id = s.series_id AND r.user_id = s.user_id
WHERE s.assignee_id = $1::text
  AND (s.user_id = $1::text OR (
      s.project_id IS NOT NULL
      AND EXISTS (SELECT 1 FROM projects p WHERE p.id = s.project_id AND p.deleted_at IS NULL)
      AND project_has_permission(s.project_id, $1::text, 'schedule', 'read')
  ))
ORDER BY s.start_at, s.occurrence_date, s.id
`

type ListSchedulesForOccurrenceProjectionByUserIDRow struct {
	ID                  string
	UserID              string
	ProjectID           pgtype.Text
	AssigneeID          string
	Title               string
	Description         pgtype.Text
	Location            pgtype.Text
	IntervalWeeks       int32
	RepeatState         pgtype.Text
	FrequencyAnchorDate pgtype.Date
	SeriesID            string
	OccurrenceDate      pgtype.Date
	Timezone            string
	IsException         bool
	Completed           bool
	Deleted             interface{}
	Frequencies         []string
	StartAt             pgtype.Timestamptz
	EndAt               pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Revision            int32
	ChangedBy           string
}

func (q *Queries) ListSchedulesForOccurrenceProjectionByUserID(ctx context.Context, userID string) ([]ListSchedulesForOccurrenceProjectionByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listSchedulesForOccurrenceProjectionByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchedulesForOccurrenceProjectionByUserIDRow
	for rows.Next() {
		var i ListSchedulesForOccurrenceProjectionByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.IntervalWeeks,
			&i.RepeatState,
			&i.FrequencyAnchorDate,
			&i.SeriesID,
			&i.OccurrenceDate,
			&i.Timezone,
			&i.IsException,
			&i.Completed,
			&i.Deleted,
			&i.Frequencies,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Revision,
			&i.ChangedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveProjectForScheduleMutation = `-- name: LockActiveProjectForScheduleMutation :one
SELECT p.id
FROM projects AS p
WHERE p.id = $1::text
  AND p.deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) LockActiveProjectForScheduleMutation(ctx context.Context, projectID string) (string, error) {
	row := q.db.QueryRow(ctx, lockActiveProjectForScheduleMutation, projectID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const lockScheduleByUserIDForPermission = `-- name: LockScheduleByUserIDForPermission :one
SELECT s.project_id
FROM schedules AS s
WHERE s.id = $1::text
  AND s.id = s.series_id
  AND s.deleted_at IS NULL
  AND schedule_has_permission(s.id, $2::text, $3::text, $4::action)
FOR UPDATE
`

type LockScheduleByUserIDForPermissionParams struct {
	SeriesID   string
	ActorID    string
	ResourceID string
	Action     Action
}

func (q *Queries) LockScheduleByUserIDForPermission(ctx context.Context, arg LockScheduleByUserIDForPermissionParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, lockScheduleByUserIDForPermission,
		arg.SeriesID,
		arg.ActorID,
		arg.ResourceID,
		arg.Action,
	)
	var project_id pgtype.Text
	err := row.Scan(&project_id)
	return project_id, err
}
