// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule_recurrence.mut.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearScheduleFrequenciesByUserID = `-- name: ClearScheduleFrequenciesByUserID :exec
DELETE FROM schedule_frequencies f
USING schedules root
WHERE f.schedule_id = root.id
  AND root.id = $1::text
  AND root.id = root.series_id
  AND root.deleted_at IS NULL
  AND schedule_has_permission(root.id, $2::text, 'schedule', 'update')
`

type ClearScheduleFrequenciesByUserIDParams struct {
	SeriesID string
	UserID   string
}

func (q *Queries) ClearScheduleFrequenciesByUserID(ctx context.Context, arg ClearScheduleFrequenciesByUserIDParams) error {
	_, err := q.db.Exec(ctx, clearScheduleFrequenciesByUserID, arg.SeriesID, arg.UserID)
	return err
}

const createScheduleFrequenciesByUserID = `-- name: CreateScheduleFrequenciesByUserID :exec
INSERT INTO schedule_frequencies (schedule_id, frequency)
SELECT root.id, f.frequency
FROM schedules root
CROSS JOIN unnest($1::text[]) AS f(frequency)
WHERE root.id = $2::text
  AND root.id = root.series_id
  AND root.deleted_at IS NULL
  AND schedule_has_permission(root.id, $3::text, 'schedule', 'update')
ON CONFLICT DO NOTHING
`

type CreateScheduleFrequenciesByUserIDParams struct {
	Frequencies []string
	SeriesID    string
	UserID      string
}

func (q *Queries) CreateScheduleFrequenciesByUserID(ctx context.Context, arg CreateScheduleFrequenciesByUserIDParams) error {
	_, err := q.db.Exec(ctx, createScheduleFrequenciesByUserID, arg.Frequencies, arg.SeriesID, arg.UserID)
	return err
}

const replaceScheduleFrequenciesByUserID = `-- name: ReplaceScheduleFrequenciesByUserID :exec
DELETE FROM schedule_frequencies f
USING schedules root
WHERE f.schedule_id = root.id
  AND root.id = $1::text
  AND root.id = root.series_id
  AND root.deleted_at IS NULL
  AND schedule_has_permission(root.id, $2::text, 'schedule', 'update')
`

type ReplaceScheduleFrequenciesByUserIDParams struct {
	SeriesID string
	UserID   string
}

func (q *Queries) ReplaceScheduleFrequenciesByUserID(ctx context.Context, arg ReplaceScheduleFrequenciesByUserIDParams) error {
	_, err := q.db.Exec(ctx, replaceScheduleFrequenciesByUserID, arg.SeriesID, arg.UserID)
	return err
}

const setScheduleRecurrenceByUserID = `-- name: SetScheduleRecurrenceByUserID :execrows
UPDATE schedules root
SET repeat_state = 'active',
    frequency_anchor_date = $1::date,
    interval_weeks = $2::integer,
    changed_by = $3::text,
    updated_at = now()
WHERE root.id = $4::text
  AND root.id = root.series_id
  AND root.deleted_at IS NULL
  AND schedule_has_permission(root.id, $3::text, 'schedule', 'update')
  AND $2::integer > 0
`

type SetScheduleRecurrenceByUserIDParams struct {
	FrequencyAnchorDate pgtype.Date
	IntervalWeeks       int32
	UserID              string
	SeriesID            string
}

func (q *Queries) SetScheduleRecurrenceByUserID(ctx context.Context, arg SetScheduleRecurrenceByUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, setScheduleRecurrenceByUserID,
		arg.FrequencyAnchorDate,
		arg.IntervalWeeks,
		arg.UserID,
		arg.SeriesID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const snapshotScheduleRootOccurrenceByUserID = `-- name: SnapshotScheduleRootOccurrenceByUserID :exec
INSERT INTO schedules (
    id, user_id, project_id, assignee_id, title, description, location, start_at, end_at, completed,
    series_id, occurrence_date, timezone, is_exception, repeat_state,
    frequency_anchor_date, interval_weeks, deleted_at, changed_by
)
SELECT $1::text, root.user_id, root.project_id, root.assignee_id,
       root.title, root.description, root.location, root.start_at, root.end_at, root.completed,
       root.id, root.occurrence_date, root.timezone, true, NULL, NULL, 0, root.deleted_at, $2::text
FROM schedules root
WHERE root.id = $3::text
  AND root.id = root.series_id
  AND root.deleted_at IS NULL
  AND schedule_has_permission(root.id, $2::text, 'schedule', 'update')
ON CONFLICT (series_id, occurrence_date) WHERE id <> series_id DO NOTHING
`

type SnapshotScheduleRootOccurrenceByUserIDParams struct {
	ID       string
	UserID   string
	SeriesID string
}

func (q *Queries) SnapshotScheduleRootOccurrenceByUserID(ctx context.Context, arg SnapshotScheduleRootOccurrenceByUserIDParams) error {
	_, err := q.db.Exec(ctx, snapshotScheduleRootOccurrenceByUserID, arg.ID, arg.UserID, arg.SeriesID)
	return err
}

const stopScheduleRecurrenceByUserID = `-- name: StopScheduleRecurrenceByUserID :execrows
UPDATE schedules root
SET repeat_state = 'stopped', interval_weeks = 0, changed_by = $1::text, updated_at = now()
WHERE root.id = $2::text
  AND root.id = root.series_id
  AND root.deleted_at IS NULL
  AND schedule_has_permission(root.id, $1::text, 'schedule', 'update')
  AND root.repeat_state IN ('active', 'stopped')
`

type StopScheduleRecurrenceByUserIDParams struct {
	UserID   string
	SeriesID string
}

func (q *Queries) StopScheduleRecurrenceByUserID(ctx context.Context, arg StopScheduleRecurrenceByUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, stopScheduleRecurrenceByUserID, arg.UserID, arg.SeriesID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateScheduleSeriesTemplateByUserID = `-- name: UpdateScheduleSeriesTemplateByUserID :execrows
UPDATE schedules root
SET title = $1::text,
    description = $2::text,
    location = $3::text,
    start_at = $4::timestamptz,
    end_at = $5::timestamptz,
    timezone = $6::text,
    changed_by = $7::text,
    updated_at = now()
WHERE root.id = $8::text
  AND root.id = root.series_id
  AND root.deleted_at IS NULL
  AND schedule_has_permission(root.id, $7::text, 'schedule', 'update')
`

type UpdateScheduleSeriesTemplateByUserIDParams struct {
	Title       string
	Description pgtype.Text
	Location    pgtype.Text
	StartAt     pgtype.Timestamptz
	EndAt       pgtype.Timestamptz
	Timezone    string
	UserID      string
	SeriesID    string
}

func (q *Queries) UpdateScheduleSeriesTemplateByUserID(ctx context.Context, arg UpdateScheduleSeriesTemplateByUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateScheduleSeriesTemplateByUserID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartAt,
		arg.EndAt,
		arg.Timezone,
		arg.UserID,
		arg.SeriesID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
