// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule_tags.mut.sql

package sqlc

import (
	"context"
)

const addScheduleTagToScheduleByUserID = `-- name: AddScheduleTagToScheduleByUserID :one
WITH owned_pair AS (
    SELECT s.series_id AS schedule_id, t.id AS tag_id
    FROM schedules AS s
    JOIN tags AS t ON t.user_id = s.user_id
    WHERE s.id = $1::text
      AND s.deleted_at IS NULL
      AND t.id = $2::text
      AND schedule_has_permission(s.id, $3::text, 'schedule', 'update')
), inserted AS (
    INSERT INTO schedule_tag_assignments (schedule_id, tag_id)
    SELECT schedule_id, tag_id FROM owned_pair
    ON CONFLICT (schedule_id, tag_id) DO NOTHING
    RETURNING 1
)
SELECT EXISTS (SELECT 1 FROM owned_pair) AS owned,
       EXISTS (SELECT 1 FROM inserted) AS added
`

type AddScheduleTagToScheduleByUserIDParams struct {
	ScheduleID string
	TagID      string
	UserID     string
}

type AddScheduleTagToScheduleByUserIDRow struct {
	Owned bool
	Added bool
}

func (q *Queries) AddScheduleTagToScheduleByUserID(ctx context.Context, arg AddScheduleTagToScheduleByUserIDParams) (AddScheduleTagToScheduleByUserIDRow, error) {
	row := q.db.QueryRow(ctx, addScheduleTagToScheduleByUserID, arg.ScheduleID, arg.TagID, arg.UserID)
	var i AddScheduleTagToScheduleByUserIDRow
	err := row.Scan(&i.Owned, &i.Added)
	return i, err
}

const removeScheduleTagFromScheduleByUserID = `-- name: RemoveScheduleTagFromScheduleByUserID :one
WITH owned_pair AS (
    SELECT s.series_id AS schedule_id, t.id AS tag_id
    FROM schedules AS s
    JOIN tags AS t ON t.user_id = s.user_id
    WHERE s.id = $1::text
      AND s.deleted_at IS NULL
      AND t.id = $2::text
      AND schedule_has_permission(s.id, $3::text, 'schedule', 'update')
), deleted AS (
    DELETE FROM schedule_tag_assignments AS assignment
    USING owned_pair
    WHERE assignment.schedule_id = owned_pair.schedule_id
      AND assignment.tag_id = owned_pair.tag_id
    RETURNING 1
)
SELECT EXISTS (SELECT 1 FROM owned_pair) AS owned,
       EXISTS (SELECT 1 FROM deleted) AS removed
`

type RemoveScheduleTagFromScheduleByUserIDParams struct {
	ScheduleID string
	TagID      string
	UserID     string
}

type RemoveScheduleTagFromScheduleByUserIDRow struct {
	Owned   bool
	Removed bool
}

func (q *Queries) RemoveScheduleTagFromScheduleByUserID(ctx context.Context, arg RemoveScheduleTagFromScheduleByUserIDParams) (RemoveScheduleTagFromScheduleByUserIDRow, error) {
	row := q.db.QueryRow(ctx, removeScheduleTagFromScheduleByUserID, arg.ScheduleID, arg.TagID, arg.UserID)
	var i RemoveScheduleTagFromScheduleByUserIDRow
	err := row.Scan(&i.Owned, &i.Removed)
	return i, err
}
