// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: schedules.mut.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScheduleByUserID = `-- name: CreateScheduleByUserID :one
WITH project_scope AS (
    SELECT p.id, p.user_id
    FROM projects p
    WHERE p.id = $1::text
      AND project_has_permission(p.id, $2::text, 'schedule', 'create')
    UNION ALL
    SELECT NULL::text, $2::text
    WHERE $1::text IS NULL
), inserted AS (
    INSERT INTO schedules (
        id, user_id, project_id, assignee_id, title, description, location,
        series_id, occurrence_date, timezone, is_exception, start_at, end_at,
        repeat_state, frequency_anchor_date, interval_weeks, changed_by
    )
    SELECT $3::text, scope.user_id, scope.id, scope.user_id,
           $4::text, $5::text, $6::text,
           $7::text, $8::date, $9::text,
           $10::boolean, $11::timestamptz, $12::timestamptz,
           CASE WHEN $13::integer > 0 THEN 'active' ELSE 'one_off' END,
           CASE WHEN $13::integer > 0 THEN $8::date ELSE NULL END,
           $13::integer, $2::text
    FROM project_scope scope
    RETURNING id, user_id, project_id, assignee_id, title, description, location, start_at, end_at, series_id, occurrence_date, timezone, is_exception, repeat_state, frequency_anchor_date, interval_weeks, completed, deleted_at, skipped_at, revision, changed_by, created_at, updated_at
), inserted_frequencies AS (
    INSERT INTO schedule_frequencies(schedule_id, frequency)
    SELECT i.id, unnest($14::text[])
    FROM inserted i
    WHERE i.id = i.series_id AND i.interval_weeks > 0
    ON CONFLICT DO NOTHING
    RETURNING schedule_id, frequency
), initial_history AS (
    INSERT INTO schedule_revisions (
        id, revision, user_id, project_id, assignee_id, title, description, location,
        start_at, end_at, series_id, occurrence_date, timezone, is_exception,
        repeat_state, frequency_anchor_date, interval_weeks, completed, deleted_at,
        skipped_at, frequencies, created_at, updated_at, changed_by, changed_at
    )
    SELECT i.id, i.revision, i.user_id, i.project_id, i.assignee_id, i.title, i.description, i.location,
           i.start_at, i.end_at, i.series_id, i.occurrence_date, i.timezone, i.is_exception,
           i.repeat_state, i.frequency_anchor_date, i.interval_weeks, i.completed, i.deleted_at,
           i.skipped_at,
           COALESCE(ARRAY(
               SELECT f.frequency FROM inserted_frequencies f
               WHERE f.schedule_id = i.id ORDER BY f.frequency
           ), '{}'::text[]),
           i.created_at, i.updated_at, i.changed_by, i.updated_at
    FROM inserted i
    WHERE i.id = i.series_id AND i.repeat_state = 'active'
    RETURNING id
)
SELECT i.id, i.user_id, i.project_id, i.assignee_id, i.title, i.description, i.location,
       i.interval_weeks, i.repeat_state, i.frequency_anchor_date,
       i.series_id, i.occurrence_date, i.timezone, i.is_exception, i.completed,
       false AS deleted,
       ARRAY(SELECT f.frequency FROM schedule_frequencies f WHERE f.schedule_id = i.series_id ORDER BY f.frequency)::text[] AS frequencies,
       i.start_at, i.end_at, i.created_at, i.updated_at, i.revision, i.changed_by
FROM inserted i
`

type CreateScheduleByUserIDParams struct {
	ProjectID      pgtype.Text
	ActorID        string
	ID             string
	Title          string
	Description    pgtype.Text
	Location       pgtype.Text
	SeriesID       string
	OccurrenceDate pgtype.Date
	Timezone       string
	IsException    bool
	StartAt        pgtype.Timestamptz
	EndAt          pgtype.Timestamptz
	IntervalWeeks  int32
	Frequencies    []string
}

type CreateScheduleByUserIDRow struct {
	ID                  string
	UserID              string
	ProjectID           pgtype.Text
	AssigneeID          string
	Title               string
	Description         pgtype.Text
	Location            pgtype.Text
	IntervalWeeks       int32
	RepeatState         pgtype.Text
	FrequencyAnchorDate pgtype.Date
	SeriesID            string
	OccurrenceDate      pgtype.Date
	Timezone            string
	IsException         bool
	Completed           bool
	Deleted             bool
	Frequencies         []string
	StartAt             pgtype.Timestamptz
	EndAt               pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Revision            int32
	ChangedBy           string
}

func (q *Queries) CreateScheduleByUserID(ctx context.Context, arg CreateScheduleByUserIDParams) (CreateScheduleByUserIDRow, error) {
	row := q.db.QueryRow(ctx, createScheduleByUserID,
		arg.ProjectID,
		arg.ActorID,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.SeriesID,
		arg.OccurrenceDate,
		arg.Timezone,
		arg.IsException,
		arg.StartAt,
		arg.EndAt,
		arg.IntervalWeeks,
		arg.Frequencies,
	)
	var i CreateScheduleByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.IntervalWeeks,
		&i.RepeatState,
		&i.FrequencyAnchorDate,
		&i.SeriesID,
		&i.OccurrenceDate,
		&i.Timezone,
		&i.IsException,
		&i.Completed,
		&i.Deleted,
		&i.Frequencies,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
		&i.ChangedBy,
	)
	return i, err
}

const createScheduleOccurrenceByUserID = `-- name: CreateScheduleOccurrenceByUserID :one
INSERT INTO schedules (
    id, user_id, project_id, assignee_id, title, description, location,
    series_id, occurrence_date, timezone, is_exception, start_at, end_at,
    repeat_state, frequency_anchor_date, interval_weeks, changed_by
)
SELECT $1::text, root.user_id, root.project_id, root.assignee_id,
       root.title, root.description, root.location,
       root.id, $2::date, $3::text,
       $4::boolean, $5::timestamptz, $6::timestamptz,
       NULL, NULL, 0, $7::text
FROM schedules root
WHERE root.id = $8::text
  AND root.id = root.series_id
  AND root.user_id = $7::text
  AND root.repeat_state = 'active'
  AND root.frequency_anchor_date <= $2::date
  AND root.deleted_at IS NULL
  AND (root.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = root.project_id AND p.deleted_at IS NULL))
ON CONFLICT (series_id, occurrence_date) WHERE id <> series_id DO UPDATE
SET id = schedules.id
WHERE schedules.deleted_at IS NULL
RETURNING id
`

type CreateScheduleOccurrenceByUserIDParams struct {
	ID             string
	OccurrenceDate pgtype.Date
	Timezone       string
	IsException    bool
	StartAt        pgtype.Timestamptz
	EndAt          pgtype.Timestamptz
	UserID         string
	SeriesID       string
}

func (q *Queries) CreateScheduleOccurrenceByUserID(ctx context.Context, arg CreateScheduleOccurrenceByUserIDParams) (string, error) {
	row := q.db.QueryRow(ctx, createScheduleOccurrenceByUserID,
		arg.ID,
		arg.OccurrenceDate,
		arg.Timezone,
		arg.IsException,
		arg.StartAt,
		arg.EndAt,
		arg.UserID,
		arg.SeriesID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteProjectSchedulesByActor = `-- name: DeleteProjectSchedulesByActor :execrows
UPDATE schedules AS s
SET deleted_at = now(),
    changed_by = $1::text,
    updated_at = now()
WHERE s.project_id = $2::text
  AND s.deleted_at IS NULL
`

type DeleteProjectSchedulesByActorParams struct {
	ActorID   string
	ProjectID string
}

func (q *Queries) DeleteProjectSchedulesByActor(ctx context.Context, arg DeleteProjectSchedulesByActorParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectSchedulesByActor, arg.ActorID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteScheduleByUserID = `-- name: DeleteScheduleByUserID :one
UPDATE schedules s
SET deleted_at = COALESCE(s.deleted_at, now()), changed_by = $1::text, updated_at = now()
WHERE s.id = $2::text
  AND s.deleted_at IS NULL
  AND schedule_has_permission(s.id, $1::text, 'schedule', 'delete')
RETURNING s.id
`

type DeleteScheduleByUserIDParams struct {
	ActorID string
	ID      string
}

func (q *Queries) DeleteScheduleByUserID(ctx context.Context, arg DeleteScheduleByUserIDParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteScheduleByUserID, arg.ActorID, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteUneditedFutureSchedulesBySeries = `-- name: DeleteUneditedFutureSchedulesBySeries :execrows
UPDATE schedules s
SET deleted_at = COALESCE(s.deleted_at, now()), changed_by = $1::text, updated_at = now()
WHERE s.series_id = $2::text
  AND s.id <> s.series_id
  AND s.start_at > $3::timestamptz
  AND s.is_exception = false
  AND s.completed = false
  AND s.deleted_at IS NULL
  AND schedule_has_permission(s.id, $1::text, 'schedule', 'update')
`

type DeleteUneditedFutureSchedulesBySeriesParams struct {
	UserID   string
	SeriesID string
	FromAt   pgtype.Timestamptz
}

func (q *Queries) DeleteUneditedFutureSchedulesBySeries(ctx context.Context, arg DeleteUneditedFutureSchedulesBySeriesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUneditedFutureSchedulesBySeries, arg.UserID, arg.SeriesID, arg.FromAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUneditedFutureSchedulesByUserID = `-- name: DeleteUneditedFutureSchedulesByUserID :execrows
UPDATE schedules s
SET deleted_at = COALESCE(s.deleted_at, now()), changed_by = $1::text, updated_at = now()
WHERE s.user_id = $1::text
  AND s.id <> s.series_id
  AND s.start_at > $2::timestamptz
  AND s.is_exception = false
  AND s.completed = false
  AND s.deleted_at IS NULL
  AND schedule_has_permission(s.id, $1::text, 'schedule', 'update')
`

type DeleteUneditedFutureSchedulesByUserIDParams struct {
	UserID string
	FromAt pgtype.Timestamptz
}

func (q *Queries) DeleteUneditedFutureSchedulesByUserID(ctx context.Context, arg DeleteUneditedFutureSchedulesByUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUneditedFutureSchedulesByUserID, arg.UserID, arg.FromAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reassignProjectMemberSchedulesByActor = `-- name: ReassignProjectMemberSchedulesByActor :execrows
UPDATE schedules AS s
SET assignee_id = p.user_id,
    changed_by = $1::text,
    updated_at = now()
FROM projects AS p
WHERE s.project_id = p.id
  AND p.id = $2::text
  AND s.assignee_id = $3::text
`

type ReassignProjectMemberSchedulesByActorParams struct {
	ActorID   string
	ProjectID string
	MemberID  string
}

func (q *Queries) ReassignProjectMemberSchedulesByActor(ctx context.Context, arg ReassignProjectMemberSchedulesByActorParams) (int64, error) {
	result, err := q.db.Exec(ctx, reassignProjectMemberSchedulesByActor, arg.ActorID, arg.ProjectID, arg.MemberID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setScheduleCompletedByUserID = `-- name: SetScheduleCompletedByUserID :execrows
UPDATE schedules s
SET completed = $1::boolean,
    is_exception = CASE WHEN s.id = s.series_id THEN s.is_exception ELSE true END,
    changed_by = $2::text,
    updated_at = now()
WHERE s.id = $3::text
  AND s.deleted_at IS NULL
  AND schedule_has_permission(s.id, $2::text, 'schedule', 'update')
`

type SetScheduleCompletedByUserIDParams struct {
	Completed bool
	ActorID   string
	ID        string
}

func (q *Queries) SetScheduleCompletedByUserID(ctx context.Context, arg SetScheduleCompletedByUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, setScheduleCompletedByUserID, arg.Completed, arg.ActorID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tombstoneScheduleByUserID = `-- name: TombstoneScheduleByUserID :one
UPDATE schedules s
SET deleted_at = COALESCE(s.deleted_at, now()), changed_by = $1::text, updated_at = now()
WHERE s.id = $2::text
  AND s.deleted_at IS NULL
  AND schedule_has_permission(s.id, $1::text, 'schedule', 'delete')
RETURNING s.id
`

type TombstoneScheduleByUserIDParams struct {
	ActorID string
	ID      string
}

func (q *Queries) TombstoneScheduleByUserID(ctx context.Context, arg TombstoneScheduleByUserIDParams) (string, error) {
	row := q.db.QueryRow(ctx, tombstoneScheduleByUserID, arg.ActorID, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateScheduleAssigneeByUserID = `-- name: UpdateScheduleAssigneeByUserID :execrows
WITH eligible_root AS (
    SELECT root.id, root.project_id, root.user_id
    FROM schedules root
    WHERE root.id = $3::text
      AND root.id = root.series_id
      AND root.deleted_at IS NULL
      AND schedule_has_permission(root.id, $2::text, 'schedule_assignment', 'update')
      AND (
          $1::text = root.user_id
          OR EXISTS (SELECT 1 FROM project_members pm WHERE pm.project_id = root.project_id AND pm.user_id = $1::text)
      )
)
UPDATE schedules s
SET assignee_id = $1::text,
    changed_by = $2::text,
    updated_at = now()
FROM eligible_root root
WHERE s.series_id = root.id
  AND s.user_id = root.user_id
`

type UpdateScheduleAssigneeByUserIDParams struct {
	AssigneeID string
	ActorID    string
	SeriesID   string
}

func (q *Queries) UpdateScheduleAssigneeByUserID(ctx context.Context, arg UpdateScheduleAssigneeByUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateScheduleAssigneeByUserID, arg.AssigneeID, arg.ActorID, arg.SeriesID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateScheduleByUserID = `-- name: UpdateScheduleByUserID :one
WITH updated AS (
    UPDATE schedules s
    SET title = $1::text,
        description = $2::text,
        location = $3::text,
        start_at = $4::timestamptz,
        end_at = $5::timestamptz,
        is_exception = CASE WHEN s.id = s.series_id THEN s.is_exception ELSE true END,
        changed_by = $6::text,
        updated_at = now()
    WHERE s.id = $7::text
      AND s.deleted_at IS NULL
      AND schedule_has_permission(s.id, $6::text, 'schedule', 'update')
    RETURNING s.id, s.user_id, s.project_id, s.assignee_id, s.title, s.description, s.location, s.start_at, s.end_at, s.series_id, s.occurrence_date, s.timezone, s.is_exception, s.repeat_state, s.frequency_anchor_date, s.interval_weeks, s.completed, s.deleted_at, s.skipped_at, s.revision, s.changed_by, s.created_at, s.updated_at
)
SELECT u.id, u.user_id, u.project_id, u.assignee_id, u.title, u.description, u.location,
       r.interval_weeks, r.repeat_state, r.frequency_anchor_date,
       u.series_id, u.occurrence_date, u.timezone, u.is_exception, u.completed,
       false AS deleted,
       ARRAY(SELECT f.frequency FROM schedule_frequencies f WHERE f.schedule_id = u.series_id ORDER BY f.frequency)::text[] AS frequencies,
       u.start_at, u.end_at, u.created_at, u.updated_at, u.revision, u.changed_by
FROM updated u JOIN schedules r ON r.id = u.series_id AND r.user_id = u.user_id
`

type UpdateScheduleByUserIDParams struct {
	Title       string
	Description pgtype.Text
	Location    pgtype.Text
	StartAt     pgtype.Timestamptz
	EndAt       pgtype.Timestamptz
	ActorID     string
	ID          string
}

type UpdateScheduleByUserIDRow struct {
	ID                  string
	UserID              string
	ProjectID           pgtype.Text
	AssigneeID          string
	Title               string
	Description         pgtype.Text
	Location            pgtype.Text
	IntervalWeeks       int32
	RepeatState         pgtype.Text
	FrequencyAnchorDate pgtype.Date
	SeriesID            string
	OccurrenceDate      pgtype.Date
	Timezone            string
	IsException         bool
	Completed           bool
	Deleted             bool
	Frequencies         []string
	StartAt             pgtype.Timestamptz
	EndAt               pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Revision            int32
	ChangedBy           string
}

func (q *Queries) UpdateScheduleByUserID(ctx context.Context, arg UpdateScheduleByUserIDParams) (UpdateScheduleByUserIDRow, error) {
	row := q.db.QueryRow(ctx, updateScheduleByUserID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartAt,
		arg.EndAt,
		arg.ActorID,
		arg.ID,
	)
	var i UpdateScheduleByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.IntervalWeeks,
		&i.RepeatState,
		&i.FrequencyAnchorDate,
		&i.SeriesID,
		&i.OccurrenceDate,
		&i.Timezone,
		&i.IsException,
		&i.Completed,
		&i.Deleted,
		&i.Frequencies,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Revision,
		&i.ChangedBy,
	)
	return i, err
}

const updateScheduleProjectByUserID = `-- name: UpdateScheduleProjectByUserID :execrows
WITH locked AS (
    SELECT root.id, root.user_id, root.project_id
    FROM schedules root
    WHERE root.id = $2::text
      AND root.id = root.series_id
      AND root.deleted_at IS NULL
      AND schedule_has_permission(root.id, $1::text, 'schedule', 'update')
    FOR UPDATE
), target AS (
    SELECT p.id
    FROM projects p, locked l
    WHERE p.id = $3::text
      AND p.user_id = l.user_id
      AND p.deleted_at IS NULL
      AND project_has_permission(p.id, $1::text, 'schedule', 'create')
    UNION ALL
    SELECT NULL::text
    FROM locked l
    WHERE $3::text IS NULL
      AND (l.project_id IS NULL OR project_has_permission(l.project_id, $1::text, 'schedule', 'update'))
)
UPDATE schedules s
SET project_id = target.id,
    assignee_id = CASE WHEN s.assignee_id = s.user_id OR EXISTS (
        SELECT 1 FROM project_members pm WHERE pm.project_id = target.id AND pm.user_id = s.assignee_id
    ) THEN s.assignee_id ELSE s.user_id END,
    changed_by = $1::text,
    updated_at = now()
FROM locked, target
WHERE s.series_id = locked.id
  AND s.user_id = locked.user_id
`

type UpdateScheduleProjectByUserIDParams struct {
	ActorID   string
	SeriesID  string
	ProjectID pgtype.Text
}

func (q *Queries) UpdateScheduleProjectByUserID(ctx context.Context, arg UpdateScheduleProjectByUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateScheduleProjectByUserID, arg.ActorID, arg.SeriesID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
