// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: schedule_occurrences.mut.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSkippedScheduleOccurrenceByUserID = `-- name: DeleteSkippedScheduleOccurrenceByUserID :exec
UPDATE schedules child
SET deleted_at = now(), changed_by = $1::text, updated_at = now()
FROM schedules root
WHERE child.series_id = root.id
  AND child.series_id = $2::text
  AND child.occurrence_date = $3::date
  AND child.id <> child.series_id
  AND NOT child.is_exception
  AND child.deleted_at IS NULL
  AND child.skipped_at IS NOT NULL
  AND root.deleted_at IS NULL
  AND root.id = root.series_id
  AND schedule_has_permission(root.id, $1::text, 'occurrence', 'update')
`

type DeleteSkippedScheduleOccurrenceByUserIDParams struct {
	UserID         string
	SeriesID       string
	OccurrenceDate pgtype.Date
}

func (q *Queries) DeleteSkippedScheduleOccurrenceByUserID(ctx context.Context, arg DeleteSkippedScheduleOccurrenceByUserIDParams) error {
	_, err := q.db.Exec(ctx, deleteSkippedScheduleOccurrenceByUserID, arg.UserID, arg.SeriesID, arg.OccurrenceDate)
	return err
}

const restoreScheduleOccurrenceByUserID = `-- name: RestoreScheduleOccurrenceByUserID :exec
UPDATE schedules child
SET skipped_at = NULL, changed_by = $1::text, updated_at = now()
FROM schedules root
WHERE child.series_id = root.id
  AND child.series_id = $2::text
  AND child.occurrence_date = $3::date
  AND child.id <> child.series_id
  AND child.is_exception
  AND child.deleted_at IS NULL
  AND child.skipped_at IS NOT NULL
  AND root.deleted_at IS NULL
  AND root.id = root.series_id
  AND schedule_has_permission(root.id, $1::text, 'occurrence', 'update')
`

type RestoreScheduleOccurrenceByUserIDParams struct {
	UserID         string
	SeriesID       string
	OccurrenceDate pgtype.Date
}

func (q *Queries) RestoreScheduleOccurrenceByUserID(ctx context.Context, arg RestoreScheduleOccurrenceByUserIDParams) error {
	_, err := q.db.Exec(ctx, restoreScheduleOccurrenceByUserID, arg.UserID, arg.SeriesID, arg.OccurrenceDate)
	return err
}

const skipScheduleOccurrenceByUserID = `-- name: SkipScheduleOccurrenceByUserID :one
INSERT INTO schedules (
    id, user_id, project_id, assignee_id, title, description, location, start_at, end_at,
    series_id, occurrence_date, timezone, is_exception, completed,
    repeat_state, frequency_anchor_date, interval_weeks, deleted_at, skipped_at, changed_by
)
SELECT $1::text, root.user_id, root.project_id, root.assignee_id,
       root.title, root.description, root.location, root.start_at, root.end_at,
       root.id, $2::date, root.timezone, false,
       false, NULL, NULL, 0, NULL, now(), $3::text
FROM schedules root
WHERE root.id = $4::text
  AND root.id = root.series_id
  AND root.deleted_at IS NULL
  AND schedule_has_permission(root.id, $3::text, 'occurrence', 'update')
ON CONFLICT (series_id, occurrence_date) WHERE id <> series_id
DO UPDATE SET skipped_at = COALESCE(schedules.skipped_at, now()), changed_by = $3::text, updated_at = now()
WHERE schedules.deleted_at IS NULL
RETURNING id
`

type SkipScheduleOccurrenceByUserIDParams struct {
	ID             string
	OccurrenceDate pgtype.Date
	UserID         string
	SeriesID       string
}

func (q *Queries) SkipScheduleOccurrenceByUserID(ctx context.Context, arg SkipScheduleOccurrenceByUserIDParams) (string, error) {
	row := q.db.QueryRow(ctx, skipScheduleOccurrenceByUserID,
		arg.ID,
		arg.OccurrenceDate,
		arg.UserID,
		arg.SeriesID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const upsertScheduleOverrideByUserID = `-- name: UpsertScheduleOverrideByUserID :one
INSERT INTO schedules (
    id, user_id, project_id, assignee_id, title, description, location, start_at, end_at,
    series_id, occurrence_date, timezone, is_exception, completed,
    repeat_state, frequency_anchor_date, interval_weeks, deleted_at, skipped_at, changed_by
)
SELECT $1::text, root.user_id, root.project_id, root.assignee_id,
       $2::text, $3::text, $4::text,
       $5::timestamptz, $6::timestamptz,
       root.id, $7::date, $8::text, true,
       $9::boolean, NULL, NULL, 0,
       CASE WHEN $10::boolean THEN now() ELSE NULL END, NULL, $11::text
FROM schedules root
WHERE root.id = $12::text
  AND root.id = root.series_id
  AND root.deleted_at IS NULL
  AND schedule_has_permission(root.id, $11::text, 'schedule', 'update')
ON CONFLICT (series_id, occurrence_date) WHERE id <> series_id DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    location = EXCLUDED.location,
    start_at = EXCLUDED.start_at,
    end_at = EXCLUDED.end_at,
    timezone = EXCLUDED.timezone,
    is_exception = true,
    completed = EXCLUDED.completed,
    deleted_at = EXCLUDED.deleted_at,
    changed_by = EXCLUDED.changed_by,
    updated_at = now()
WHERE schedules.deleted_at IS NULL
RETURNING id
`

type UpsertScheduleOverrideByUserIDParams struct {
	ID             string
	Title          string
	Description    pgtype.Text
	Location       pgtype.Text
	StartAt        pgtype.Timestamptz
	EndAt          pgtype.Timestamptz
	OccurrenceDate pgtype.Date
	Timezone       string
	Completed      bool
	Deleted        bool
	UserID         string
	SeriesID       string
}

func (q *Queries) UpsertScheduleOverrideByUserID(ctx context.Context, arg UpsertScheduleOverrideByUserIDParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertScheduleOverrideByUserID,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartAt,
		arg.EndAt,
		arg.OccurrenceDate,
		arg.Timezone,
		arg.Completed,
		arg.Deleted,
		arg.UserID,
		arg.SeriesID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
