// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: schedule_tags.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listScheduleTagsByScheduleAndUserID = `-- name: ListScheduleTagsByScheduleAndUserID :many
SELECT t.id, t.user_id, t.name, t.created_at, t.updated_at
FROM schedule_tag_assignments AS sta
JOIN tags AS t ON t.id = sta.tag_id
JOIN schedules AS s ON s.id = sta.schedule_id
JOIN schedules AS requested ON requested.series_id = s.id
WHERE requested.id = $1::text
  AND requested.deleted_at IS NULL
  AND requested.series_id = sta.schedule_id
  AND schedule_has_permission(requested.id, $2::text, 'schedule', 'read')
  AND t.user_id = requested.user_id
ORDER BY t.name, t.id
`

type ListScheduleTagsByScheduleAndUserIDParams struct {
	ScheduleID string
	UserID     string
}

func (q *Queries) ListScheduleTagsByScheduleAndUserID(ctx context.Context, arg ListScheduleTagsByScheduleAndUserIDParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listScheduleTagsByScheduleAndUserID, arg.ScheduleID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleTagsByScheduleIDsAndUserID = `-- name: ListScheduleTagsByScheduleIDsAndUserID :many
WITH requested AS (
    SELECT DISTINCT s.id AS schedule_id, s.series_id, s.user_id
    FROM schedules AS s
    WHERE s.id = ANY($1::text[])
      AND s.deleted_at IS NULL
      AND schedule_has_permission(s.id, $2::text, 'schedule', 'read')
)
SELECT requested.schedule_id, t.id, t.user_id, t.name, t.created_at, t.updated_at
FROM requested
JOIN schedule_tag_assignments AS sta ON sta.schedule_id = requested.series_id
JOIN tags AS t ON t.id = sta.tag_id AND t.user_id = requested.user_id
ORDER BY requested.schedule_id, t.name, t.id
`

type ListScheduleTagsByScheduleIDsAndUserIDParams struct {
	ScheduleIds []string
	UserID      string
}

type ListScheduleTagsByScheduleIDsAndUserIDRow struct {
	ScheduleID string
	ID         string
	UserID     string
	Name       string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) ListScheduleTagsByScheduleIDsAndUserID(ctx context.Context, arg ListScheduleTagsByScheduleIDsAndUserIDParams) ([]ListScheduleTagsByScheduleIDsAndUserIDRow, error) {
	rows, err := q.db.Query(ctx, listScheduleTagsByScheduleIDsAndUserID, arg.ScheduleIds, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduleTagsByScheduleIDsAndUserIDRow
	for rows.Next() {
		var i ListScheduleTagsByScheduleIDsAndUserIDRow
		if err := rows.Scan(
			&i.ScheduleID,
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
