// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: series_templates.mut.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const snapshotTodoItemRootOccurrenceByTaskAndUserID = `-- name: SnapshotTodoItemRootOccurrenceByTaskAndUserID :exec
INSERT INTO todo_items (
    id, task_id, title, description, due_date, completed, position,
    series_id, occurrence_date, timezone, is_exception, repeat_state,
    frequency_anchor_date, interval_weeks, deleted_at
)
SELECT $1::text, root.task_id, root.title, root.description, root.due_date,
       root.completed, root.position, root.id, root.occurrence_date, root.timezone,
       true, NULL, NULL, 0, root.deleted_at
FROM todo_items root
JOIN tasks t ON t.id = root.task_id
WHERE root.id = $2::text
  AND root.series_id = root.id
  AND root.task_id = $3::text
  AND root.deleted_at IS NULL
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND task_has_permission(t.id, $4::text, 'todo_item', 'update')
ON CONFLICT (series_id, occurrence_date) WHERE id <> series_id DO NOTHING
`

type SnapshotTodoItemRootOccurrenceByTaskAndUserIDParams struct {
	ID       string
	SeriesID string
	TaskID   string
	UserID   string
}

func (q *Queries) SnapshotTodoItemRootOccurrenceByTaskAndUserID(ctx context.Context, arg SnapshotTodoItemRootOccurrenceByTaskAndUserIDParams) error {
	_, err := q.db.Exec(ctx, snapshotTodoItemRootOccurrenceByTaskAndUserID,
		arg.ID,
		arg.SeriesID,
		arg.TaskID,
		arg.UserID,
	)
	return err
}

const updateTodoItemSeriesTemplateByTaskAndUserID = `-- name: UpdateTodoItemSeriesTemplateByTaskAndUserID :execrows
UPDATE todo_items root
SET title = $1::text,
    description = $2::text,
    due_date = $3::date,
    position = $4::integer,
    updated_at = now()
FROM tasks t
WHERE root.id = $5::text
  AND root.series_id = root.id
  AND root.task_id = $6::text
  AND root.deleted_at IS NULL
  AND t.id = root.task_id
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id = t.project_id AND p.deleted_at IS NULL))
  AND task_has_permission(t.id, $7::text, 'todo_item', 'update')
`

type UpdateTodoItemSeriesTemplateByTaskAndUserIDParams struct {
	Title       string
	Description pgtype.Text
	DueDate     pgtype.Date
	Position    int32
	SeriesID    string
	TaskID      string
	UserID      string
}

func (q *Queries) UpdateTodoItemSeriesTemplateByTaskAndUserID(ctx context.Context, arg UpdateTodoItemSeriesTemplateByTaskAndUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTodoItemSeriesTemplateByTaskAndUserID,
		arg.Title,
		arg.Description,
		arg.DueDate,
		arg.Position,
		arg.SeriesID,
		arg.TaskID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
