// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTask = `-- name: GetTask :one
SELECT id, user_id, project_id, assignee_id, title, description, due_date, estimated_minutes, actual_minutes, priority, status, revision, deleted_at, changed_by, created_at, updated_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.DueDate,
		&i.EstimatedMinutes,
		&i.ActualMinutes,
		&i.Priority,
		&i.Status,
		&i.Revision,
		&i.DeletedAt,
		&i.ChangedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByFrequency = `-- name: GetTaskByFrequency :many
SELECT t.id, t.user_id, t.project_id, t.assignee_id, t.title, t.description, t.due_date, t.estimated_minutes, t.actual_minutes, t.priority, t.status, t.revision, t.deleted_at, t.changed_by, t.created_at, t.updated_at
FROM tasks AS t
WHERE t.deleted_at IS NULL
AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id=t.project_id AND p.deleted_at IS NULL))
AND EXISTS (
    SELECT 1
    FROM action_items AS ti
    JOIN action_item_frequencies AS tif ON tif.action_item_id = ti.series_id
    WHERE ti.task_id = t.id
      AND tif.frequency = $1::text
)
`

func (q *Queries) GetTaskByFrequency(ctx context.Context, frequency string) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTaskByFrequency, frequency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Priority,
			&i.Status,
			&i.Revision,
			&i.DeletedAt,
			&i.ChangedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByPriority = `-- name: GetTaskByPriority :many
SELECT id, user_id, project_id, assignee_id, title, description, due_date, estimated_minutes, actual_minutes, priority, status, revision, deleted_at, changed_by, created_at, updated_at FROM tasks WHERE tasks.priority = $1 AND deleted_at IS NULL
  AND (project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id=tasks.project_id AND p.deleted_at IS NULL))
`

func (q *Queries) GetTaskByPriority(ctx context.Context, priority string) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTaskByPriority, priority)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Priority,
			&i.Status,
			&i.Revision,
			&i.DeletedAt,
			&i.ChangedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByProject = `-- name: GetTaskByProject :many
SELECT id, user_id, project_id, assignee_id, title, description, due_date, estimated_minutes, actual_minutes, priority, status, revision, deleted_at, changed_by, created_at, updated_at FROM tasks WHERE project_id = $1::text AND deleted_at IS NULL
  AND EXISTS (SELECT 1 FROM projects p WHERE p.id=tasks.project_id AND p.deleted_at IS NULL)
`

func (q *Queries) GetTaskByProject(ctx context.Context, projectID string) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTaskByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Priority,
			&i.Status,
			&i.Revision,
			&i.DeletedAt,
			&i.ChangedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByStatus = `-- name: GetTaskByStatus :many
SELECT id, user_id, project_id, assignee_id, title, description, due_date, estimated_minutes, actual_minutes, priority, status, revision, deleted_at, changed_by, created_at, updated_at FROM tasks WHERE tasks.status = $1 AND deleted_at IS NULL
  AND (project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id=tasks.project_id AND p.deleted_at IS NULL))
`

func (q *Queries) GetTaskByStatus(ctx context.Context, status string) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTaskByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Priority,
			&i.Status,
			&i.Revision,
			&i.DeletedAt,
			&i.ChangedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByTag = `-- name: GetTaskByTag :many
SELECT t.id, t.user_id, t.project_id, t.assignee_id, t.title, t.description, t.due_date, t.estimated_minutes, t.actual_minutes, t.priority, t.status, t.revision, t.deleted_at, t.changed_by, t.created_at, t.updated_at
FROM tasks AS t
JOIN task_tag_assignments AS tta ON tta.task_id = t.id
WHERE tta.tag_id = $1
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id=t.project_id AND p.deleted_at IS NULL))
`

func (q *Queries) GetTaskByTag(ctx context.Context, tagID string) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTaskByTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Priority,
			&i.Status,
			&i.Revision,
			&i.DeletedAt,
			&i.ChangedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByUserID = `-- name: GetTaskByUserID :one
SELECT id, user_id, project_id, assignee_id, title, description, due_date, estimated_minutes, actual_minutes, priority, status, revision, deleted_at, changed_by, created_at, updated_at
FROM tasks AS t
WHERE t.id = $1
  AND task_has_permission(t.id, $2, 'task', 'read')
`

type GetTaskByUserIDParams struct {
	ID       string
	ActorKey string
}

func (q *Queries) GetTaskByUserID(ctx context.Context, arg GetTaskByUserIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByUserID, arg.ID, arg.ActorKey)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.DueDate,
		&i.EstimatedMinutes,
		&i.ActualMinutes,
		&i.Priority,
		&i.Status,
		&i.Revision,
		&i.DeletedAt,
		&i.ChangedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByUserIDForPermission = `-- name: GetTaskByUserIDForPermission :one
SELECT id, user_id, project_id, assignee_id, title, description, due_date, estimated_minutes, actual_minutes, priority, status, revision, deleted_at, changed_by, created_at, updated_at
FROM tasks AS t
WHERE t.id = $1::text
  AND task_has_permission(t.id, $2::text, $3::text, $4::action)
`

type GetTaskByUserIDForPermissionParams struct {
	ID         string
	ActorID    string
	ResourceID string
	Action     Action
}

func (q *Queries) GetTaskByUserIDForPermission(ctx context.Context, arg GetTaskByUserIDForPermissionParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByUserIDForPermission,
		arg.ID,
		arg.ActorID,
		arg.ResourceID,
		arg.Action,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.DueDate,
		&i.EstimatedMinutes,
		&i.ActualMinutes,
		&i.Priority,
		&i.Status,
		&i.Revision,
		&i.DeletedAt,
		&i.ChangedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActionItemsByTaskForUser = `-- name: ListActionItemsByTaskForUser :many
SELECT
    ti.id,
    ti.task_id,
    ti.title,
    ti.description,
    ti.due_date,
    ti.completed,
    ti.position,
    COALESCE((SELECT r.interval_weeks FROM action_items r WHERE r.id = ti.series_id ), 0)::integer AS interval_weeks,
    ARRAY(
        SELECT tif.frequency
        FROM action_item_frequencies AS tif
        WHERE tif.action_item_id = ti.series_id
        ORDER BY tif.frequency
    )::text[] AS frequencies,
    ti.created_at,
    ti.updated_at
FROM action_items AS ti
JOIN tasks AS t ON t.id = ti.task_id
WHERE ti.task_id = $1
  AND t.user_id = $2
	AND ti.deleted_at IS NULL
ORDER BY ti.position ASC
`

type ListActionItemsByTaskForUserParams struct {
	TaskID string
	UserID string
}

type ListActionItemsByTaskForUserRow struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	DueDate       pgtype.Date
	Completed     bool
	Position      int32
	IntervalWeeks int32
	Frequencies   []string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) ListActionItemsByTaskForUser(ctx context.Context, arg ListActionItemsByTaskForUserParams) ([]ListActionItemsByTaskForUserRow, error) {
	rows, err := q.db.Query(ctx, listActionItemsByTaskForUser, arg.TaskID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActionItemsByTaskForUserRow
	for rows.Next() {
		var i ListActionItemsByTaskForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.Completed,
			&i.Position,
			&i.IntervalWeeks,
			&i.Frequencies,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTasksByUserIDCursorPage = `-- name: ListProjectTasksByUserIDCursorPage :many
SELECT t.id, t.user_id, t.project_id, t.assignee_id, t.title, t.description, t.due_date, t.estimated_minutes, t.actual_minutes, t.priority, t.status, t.revision, t.deleted_at, t.changed_by, t.created_at, t.updated_at
FROM tasks AS t
JOIN projects AS p ON p.id = t.project_id AND p.user_id = t.user_id AND p.deleted_at IS NULL
WHERE t.project_id = $1
  AND t.deleted_at IS NULL
  AND task_has_permission(t.id, $2, 'task', 'read')
  AND ($3::timestamptz IS NULL OR (t.created_at, t.id) < ($3::timestamptz, $4::text))
ORDER BY t.created_at DESC, t.id DESC
LIMIT $5::integer
`

type ListProjectTasksByUserIDCursorPageParams struct {
	ProjectID pgtype.Text
	UserID    string
	CursorAt  pgtype.Timestamptz
	CursorID  pgtype.Text
	PageLimit int32
}

func (q *Queries) ListProjectTasksByUserIDCursorPage(ctx context.Context, arg ListProjectTasksByUserIDCursorPageParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listProjectTasksByUserIDCursorPage,
		arg.ProjectID,
		arg.UserID,
		arg.CursorAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Priority,
			&i.Status,
			&i.Revision,
			&i.DeletedAt,
			&i.ChangedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProjectAndUserID = `-- name: ListTasksByProjectAndUserID :many
SELECT t.id, t.user_id, t.project_id, t.title, t.description, t.due_date, t.estimated_minutes, t.actual_minutes,
       t.priority, t.status, t.created_at, t.updated_at
FROM tasks AS t
JOIN projects AS p ON p.id = t.project_id
WHERE t.project_id = $1
  AND p.user_id = $2
ORDER BY t.created_at ASC
`

type ListTasksByProjectAndUserIDParams struct {
	ProjectID pgtype.Text
	UserID    string
}

type ListTasksByProjectAndUserIDRow struct {
	ID               string
	UserID           string
	ProjectID        pgtype.Text
	Title            string
	Description      pgtype.Text
	DueDate          pgtype.Date
	EstimatedMinutes pgtype.Int4
	ActualMinutes    pgtype.Int4
	Priority         string
	Status           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) ListTasksByProjectAndUserID(ctx context.Context, arg ListTasksByProjectAndUserIDParams) ([]ListTasksByProjectAndUserIDRow, error) {
	rows, err := q.db.Query(ctx, listTasksByProjectAndUserID, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksByProjectAndUserIDRow
	for rows.Next() {
		var i ListTasksByProjectAndUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByUserIDCursorPage = `-- name: ListTasksByUserIDCursorPage :many
SELECT t.id, t.user_id, t.project_id, t.assignee_id, t.title, t.description, t.due_date, t.estimated_minutes, t.actual_minutes, t.priority, t.status, t.revision, t.deleted_at, t.changed_by, t.created_at, t.updated_at
FROM tasks AS t
WHERE t.assignee_id = $1
  AND t.deleted_at IS NULL
  AND task_has_permission(t.id, $1, 'task', 'read')
  AND ($2::timestamptz IS NULL OR (created_at, id) < ($2::timestamptz, $3::text))
ORDER BY created_at DESC, id DESC
LIMIT $4::integer
`

type ListTasksByUserIDCursorPageParams struct {
	UserID    string
	CursorAt  pgtype.Timestamptz
	CursorID  pgtype.Text
	PageLimit int32
}

func (q *Queries) ListTasksByUserIDCursorPage(ctx context.Context, arg ListTasksByUserIDCursorPageParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByUserIDCursorPage,
		arg.UserID,
		arg.CursorAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.EstimatedMinutes,
			&i.ActualMinutes,
			&i.Priority,
			&i.Status,
			&i.Revision,
			&i.DeletedAt,
			&i.ChangedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithActiveRecurrences = `-- name: ListUsersWithActiveRecurrences :many
SELECT DISTINCT t.user_id
FROM tasks AS t
WHERE t.status <> 'done'
  AND t.deleted_at IS NULL
  AND (t.project_id IS NULL OR EXISTS (SELECT 1 FROM projects p WHERE p.id=t.project_id AND p.deleted_at IS NULL AND p.status <> 'done'))
  AND EXISTS (
      SELECT 1 FROM action_items AS ti
      WHERE ti.task_id = t.id AND ti.id = ti.series_id
        AND ti.repeat_state = 'active' AND ti.deleted_at IS NULL
  )
ORDER BY t.user_id
`

func (q *Queries) ListUsersWithActiveRecurrences(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listUsersWithActiveRecurrences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
