// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_schedules.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTaskSchedule = `-- name: GetTaskSchedule :one
SELECT
    ts.id,
    ts.task_id,
    ts.title,
    ts.description,
    ts.location,
    ts.interval_weeks,
    ARRAY(
        SELECT tsf.frequency
        FROM task_schedule_frequencies AS tsf
        WHERE tsf.task_schedule_id = ts.id
        ORDER BY tsf.frequency
    )::text[] AS frequencies,
    ts.start_at,
    ts.end_at,
    ts.created_at,
    ts.updated_at
FROM task_schedules AS ts
WHERE ts.id = $1
`

type GetTaskScheduleRow struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	Location      pgtype.Text
	IntervalWeeks int32
	Frequencies   []string
	StartAt       pgtype.Timestamptz
	EndAt         pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) GetTaskSchedule(ctx context.Context, id string) (GetTaskScheduleRow, error) {
	row := q.db.QueryRow(ctx, getTaskSchedule, id)
	var i GetTaskScheduleRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.IntervalWeeks,
		&i.Frequencies,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskScheduleByTaskAndUser = `-- name: GetTaskScheduleByTaskAndUser :one
SELECT
    ts.id,
    ts.task_id,
    ts.title,
    ts.description,
    ts.location,
    ts.interval_weeks,
    ARRAY(
        SELECT tsf.frequency
        FROM task_schedule_frequencies AS tsf
        WHERE tsf.task_schedule_id = ts.id
        ORDER BY tsf.frequency
    )::text[] AS frequencies,
    ts.start_at,
    ts.end_at,
    ts.created_at,
    ts.updated_at
FROM task_schedules AS ts
JOIN tasks AS t ON t.id = ts.task_id
WHERE ts.id = $1
  AND ts.task_id = $2
  AND t.user_id = $3
`

type GetTaskScheduleByTaskAndUserParams struct {
	ID     string
	TaskID string
	UserID string
}

type GetTaskScheduleByTaskAndUserRow struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	Location      pgtype.Text
	IntervalWeeks int32
	Frequencies   []string
	StartAt       pgtype.Timestamptz
	EndAt         pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) GetTaskScheduleByTaskAndUser(ctx context.Context, arg GetTaskScheduleByTaskAndUserParams) (GetTaskScheduleByTaskAndUserRow, error) {
	row := q.db.QueryRow(ctx, getTaskScheduleByTaskAndUser, arg.ID, arg.TaskID, arg.UserID)
	var i GetTaskScheduleByTaskAndUserRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.IntervalWeeks,
		&i.Frequencies,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTaskSchedulesByTaskAndUser = `-- name: ListTaskSchedulesByTaskAndUser :many
SELECT
    ts.id,
    ts.task_id,
    ts.title,
    ts.description,
    ts.location,
    ts.interval_weeks,
    ARRAY(
        SELECT tsf.frequency
        FROM task_schedule_frequencies AS tsf
        WHERE tsf.task_schedule_id = ts.id
        ORDER BY tsf.frequency
    )::text[] AS frequencies,
    ts.start_at,
    ts.end_at,
    ts.created_at,
    ts.updated_at
FROM task_schedules AS ts
JOIN tasks AS t ON t.id = ts.task_id
WHERE ts.task_id = $1
  AND t.user_id = $2
ORDER BY ts.start_at ASC
`

type ListTaskSchedulesByTaskAndUserParams struct {
	TaskID string
	UserID string
}

type ListTaskSchedulesByTaskAndUserRow struct {
	ID            string
	TaskID        string
	Title         string
	Description   pgtype.Text
	Location      pgtype.Text
	IntervalWeeks int32
	Frequencies   []string
	StartAt       pgtype.Timestamptz
	EndAt         pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) ListTaskSchedulesByTaskAndUser(ctx context.Context, arg ListTaskSchedulesByTaskAndUserParams) ([]ListTaskSchedulesByTaskAndUserRow, error) {
	rows, err := q.db.Query(ctx, listTaskSchedulesByTaskAndUser, arg.TaskID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskSchedulesByTaskAndUserRow
	for rows.Next() {
		var i ListTaskSchedulesByTaskAndUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.IntervalWeeks,
			&i.Frequencies,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
