// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_tags.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTagByUserID = `-- name: GetTagByUserID :one
SELECT id, user_id, name, created_at, updated_at
FROM tags
WHERE id = $1::text
  AND user_id = $2::text
`

type GetTagByUserIDParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetTagByUserID(ctx context.Context, arg GetTagByUserIDParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByUserID, arg.ID, arg.UserID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTagsByUserID = `-- name: ListTagsByUserID :many
SELECT id, user_id, name, created_at, updated_at
FROM tags
WHERE user_id = $1::text
ORDER BY name ASC, id ASC
`

func (q *Queries) ListTagsByUserID(ctx context.Context, userID string) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByUserIDPage = `-- name: ListTagsByUserIDPage :many
SELECT id, user_id, name, created_at, updated_at
FROM tags
WHERE user_id = $1::text
  AND ($2::citext IS NULL OR (name, id) > ($2::citext, $3::text))
ORDER BY name ASC, id ASC
LIMIT $4::integer
`

type ListTagsByUserIDPageParams struct {
	UserID     string
	CursorName pgtype.Text
	CursorID   pgtype.Text
	PageLimit  int32
}

func (q *Queries) ListTagsByUserIDPage(ctx context.Context, arg ListTagsByUserIDPageParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByUserIDPage,
		arg.UserID,
		arg.CursorName,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskTagsByTaskAndUserID = `-- name: ListTaskTagsByTaskAndUserID :many
SELECT tt.id, tt.user_id, tt.name, tt.created_at, tt.updated_at
FROM tags AS tt
JOIN task_tag_assignments AS tta ON tta.tag_id = tt.id
JOIN tasks AS t ON t.id = tta.task_id
WHERE t.id = $1::text
  AND task_has_permission(t.id, $2::text, 'task', 'read')
  AND tt.user_id = t.user_id
ORDER BY tt.name ASC, tt.id ASC
`

type ListTaskTagsByTaskAndUserIDParams struct {
	TaskID string
	UserID string
}

func (q *Queries) ListTaskTagsByTaskAndUserID(ctx context.Context, arg ListTaskTagsByTaskAndUserIDParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTaskTagsByTaskAndUserID, arg.TaskID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
