// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_tags.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTaskTagByUserID = `-- name: GetTaskTagByUserID :one
SELECT id, user_id, name, created_at, updated_at
FROM task_tags
WHERE id = $1::text
  AND user_id = $2::text
`

type GetTaskTagByUserIDParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetTaskTagByUserID(ctx context.Context, arg GetTaskTagByUserIDParams) (TaskTag, error) {
	row := q.db.QueryRow(ctx, getTaskTagByUserID, arg.ID, arg.UserID)
	var i TaskTag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTaskTagsByTaskAndUserID = `-- name: ListTaskTagsByTaskAndUserID :many
SELECT tt.id, tt.user_id, tt.name, tt.created_at, tt.updated_at
FROM task_tags AS tt
JOIN task_tag_assignments AS tta ON tta.tag_id = tt.id
JOIN tasks AS t ON t.id = tta.task_id
WHERE t.id = $1::text
  AND task_has_permission(t.id, $2::text, 'task', 'read')
  AND tt.user_id = t.user_id
ORDER BY tt.name ASC, tt.id ASC
`

type ListTaskTagsByTaskAndUserIDParams struct {
	TaskID string
	UserID string
}

func (q *Queries) ListTaskTagsByTaskAndUserID(ctx context.Context, arg ListTaskTagsByTaskAndUserIDParams) ([]TaskTag, error) {
	rows, err := q.db.Query(ctx, listTaskTagsByTaskAndUserID, arg.TaskID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskTag
	for rows.Next() {
		var i TaskTag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskTagsByUserID = `-- name: ListTaskTagsByUserID :many
SELECT id, user_id, name, created_at, updated_at
FROM task_tags
WHERE user_id = $1::text
ORDER BY name ASC, id ASC
`

func (q *Queries) ListTaskTagsByUserID(ctx context.Context, userID string) ([]TaskTag, error) {
	rows, err := q.db.Query(ctx, listTaskTagsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskTag
	for rows.Next() {
		var i TaskTag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskTagsByUserIDPage = `-- name: ListTaskTagsByUserIDPage :many
SELECT id, user_id, name, created_at, updated_at
FROM task_tags
WHERE user_id = $1::text
  AND ($2::citext IS NULL OR (name, id) > ($2::citext, $3::text))
ORDER BY name ASC, id ASC
LIMIT $4::integer
`

type ListTaskTagsByUserIDPageParams struct {
	UserID     string
	CursorName pgtype.Text
	CursorID   pgtype.Text
	PageLimit  int32
}

func (q *Queries) ListTaskTagsByUserIDPage(ctx context.Context, arg ListTaskTagsByUserIDPageParams) ([]TaskTag, error) {
	rows, err := q.db.Query(ctx, listTaskTagsByUserIDPage,
		arg.UserID,
		arg.CursorName,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskTag
	for rows.Next() {
		var i TaskTag
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
