// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_tags.mut.sql

package sqlc

import (
	"context"
)

const addTaskTagToTaskByUserID = `-- name: AddTaskTagToTaskByUserID :one
WITH owned_pair AS (
    SELECT t.id AS task_id, tt.id AS tag_id
    FROM tasks AS t
    JOIN task_tags AS tt ON tt.user_id = t.user_id
    WHERE t.id = $1::text
      AND tt.id = $2::text
      AND task_has_permission(t.id, $3::text, 'task', 'update')
), inserted AS (
    INSERT INTO task_tag_assignments (task_id, tag_id)
    SELECT task_id, tag_id FROM owned_pair
    ON CONFLICT (task_id, tag_id) DO NOTHING
    RETURNING 1
)
SELECT EXISTS (SELECT 1 FROM owned_pair) AS owned,
       EXISTS (SELECT 1 FROM inserted) AS added
`

type AddTaskTagToTaskByUserIDParams struct {
	TaskID string
	TagID  string
	UserID string
}

type AddTaskTagToTaskByUserIDRow struct {
	Owned bool
	Added bool
}

func (q *Queries) AddTaskTagToTaskByUserID(ctx context.Context, arg AddTaskTagToTaskByUserIDParams) (AddTaskTagToTaskByUserIDRow, error) {
	row := q.db.QueryRow(ctx, addTaskTagToTaskByUserID, arg.TaskID, arg.TagID, arg.UserID)
	var i AddTaskTagToTaskByUserIDRow
	err := row.Scan(&i.Owned, &i.Added)
	return i, err
}

const createTaskTag = `-- name: CreateTaskTag :one
INSERT INTO task_tags (id, user_id, name)
VALUES ($1::text, $2::text, $3::citext)
RETURNING id, user_id, name, created_at, updated_at
`

type CreateTaskTagParams struct {
	ID     string
	UserID string
	Name   string
}

func (q *Queries) CreateTaskTag(ctx context.Context, arg CreateTaskTagParams) (TaskTag, error) {
	row := q.db.QueryRow(ctx, createTaskTag, arg.ID, arg.UserID, arg.Name)
	var i TaskTag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTaskTagByUserID = `-- name: DeleteTaskTagByUserID :execrows
DELETE FROM task_tags
WHERE id = $1::text
  AND user_id = $2::text
`

type DeleteTaskTagByUserIDParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteTaskTagByUserID(ctx context.Context, arg DeleteTaskTagByUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaskTagByUserID, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeTaskTagFromTaskByUserID = `-- name: RemoveTaskTagFromTaskByUserID :one
WITH owned_pair AS (
    SELECT t.id AS task_id, tt.id AS tag_id
    FROM tasks AS t
    JOIN task_tags AS tt ON tt.user_id = t.user_id
    WHERE t.id = $1::text
      AND tt.id = $2::text
      AND task_has_permission(t.id, $3::text, 'task', 'update')
), deleted AS (
    DELETE FROM task_tag_assignments AS assignment
    USING owned_pair
    WHERE assignment.task_id = owned_pair.task_id
      AND assignment.tag_id = owned_pair.tag_id
    RETURNING 1
)
SELECT EXISTS (SELECT 1 FROM owned_pair) AS owned,
       EXISTS (SELECT 1 FROM deleted) AS removed
`

type RemoveTaskTagFromTaskByUserIDParams struct {
	TaskID string
	TagID  string
	UserID string
}

type RemoveTaskTagFromTaskByUserIDRow struct {
	Owned   bool
	Removed bool
}

func (q *Queries) RemoveTaskTagFromTaskByUserID(ctx context.Context, arg RemoveTaskTagFromTaskByUserIDParams) (RemoveTaskTagFromTaskByUserIDRow, error) {
	row := q.db.QueryRow(ctx, removeTaskTagFromTaskByUserID, arg.TaskID, arg.TagID, arg.UserID)
	var i RemoveTaskTagFromTaskByUserIDRow
	err := row.Scan(&i.Owned, &i.Removed)
	return i, err
}

const renameTaskTagByUserID = `-- name: RenameTaskTagByUserID :one
UPDATE task_tags
SET name = $1::citext,
    updated_at = now()
WHERE id = $2::text
  AND user_id = $3::text
RETURNING id, user_id, name, created_at, updated_at
`

type RenameTaskTagByUserIDParams struct {
	Name   string
	ID     string
	UserID string
}

func (q *Queries) RenameTaskTagByUserID(ctx context.Context, arg RenameTaskTagByUserIDParams) (TaskTag, error) {
	row := q.db.QueryRow(ctx, renameTaskTagByUserID, arg.Name, arg.ID, arg.UserID)
	var i TaskTag
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
