// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_assignees.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const isEligibleTaskAssignee = `-- name: IsEligibleTaskAssignee :one
SELECT EXISTS (
    SELECT 1
    FROM tasks AS t
    WHERE t.id = $1::text
      AND t.deleted_at IS NULL
      AND task_has_permission(t.id, $2::text, 'task_assignment', 'update')
      AND (
          $3::text = t.user_id
          OR EXISTS (
              SELECT 1 FROM project_members AS pm
              WHERE pm.project_id = t.project_id
                AND pm.user_id = $3::text
          )
      )
) AS eligible
`

type IsEligibleTaskAssigneeParams struct {
	TaskID     string
	ActorID    string
	AssigneeID string
}

func (q *Queries) IsEligibleTaskAssignee(ctx context.Context, arg IsEligibleTaskAssigneeParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEligibleTaskAssignee, arg.TaskID, arg.ActorID, arg.AssigneeID)
	var eligible bool
	err := row.Scan(&eligible)
	return eligible, err
}

const listEligibleTaskAssignees = `-- name: ListEligibleTaskAssignees :many
SELECT u.id, u.first_name, u.last_name, u.email,
       (u.id = t.user_id) AS is_project_owner
FROM tasks AS t
JOIN users AS u ON (
    u.id = t.user_id
    OR EXISTS (
        SELECT 1 FROM project_members AS pm
        WHERE pm.project_id = t.project_id AND pm.user_id = u.id
    )
)
WHERE t.id = $1::text
  AND t.deleted_at IS NULL
  AND task_has_permission(t.id, $2::text, 'task_assignment', 'update')
ORDER BY is_project_owner DESC, u.last_name, u.first_name, u.id
`

type ListEligibleTaskAssigneesParams struct {
	TaskID  string
	ActorID string
}

type ListEligibleTaskAssigneesRow struct {
	ID             string
	FirstName      string
	LastName       string
	Email          string
	IsProjectOwner bool
}

func (q *Queries) ListEligibleTaskAssignees(ctx context.Context, arg ListEligibleTaskAssigneesParams) ([]ListEligibleTaskAssigneesRow, error) {
	rows, err := q.db.Query(ctx, listEligibleTaskAssignees, arg.TaskID, arg.ActorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEligibleTaskAssigneesRow
	for rows.Next() {
		var i ListEligibleTaskAssigneesRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.IsProjectOwner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTaskForAssigneeChange = `-- name: LockTaskForAssigneeChange :one
SELECT t.id
FROM tasks AS t
WHERE t.id = $1::text
  AND t.deleted_at IS NULL
  AND task_has_permission(t.id, $2::text, 'task_assignment', 'update')
FOR UPDATE
`

type LockTaskForAssigneeChangeParams struct {
	TaskID  string
	ActorID string
}

func (q *Queries) LockTaskForAssigneeChange(ctx context.Context, arg LockTaskForAssigneeChangeParams) (string, error) {
	row := q.db.QueryRow(ctx, lockTaskForAssigneeChange, arg.TaskID, arg.ActorID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const lockTaskProjectForAssigneeChange = `-- name: LockTaskProjectForAssigneeChange :one
SELECT p.id
FROM tasks AS t
JOIN projects AS p ON p.id = t.project_id
WHERE t.id = $1::text
  AND t.deleted_at IS NULL
  AND p.deleted_at IS NULL
  AND task_has_permission(t.id, $2::text, 'task_assignment', 'update')
FOR UPDATE OF p
`

type LockTaskProjectForAssigneeChangeParams struct {
	TaskID  string
	ActorID string
}

func (q *Queries) LockTaskProjectForAssigneeChange(ctx context.Context, arg LockTaskProjectForAssigneeChangeParams) (string, error) {
	row := q.db.QueryRow(ctx, lockTaskProjectForAssigneeChange, arg.TaskID, arg.ActorID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const taskProjectForAssigneeChange = `-- name: TaskProjectForAssigneeChange :one
SELECT t.project_id
FROM tasks AS t
WHERE t.id = $1::text
  AND t.deleted_at IS NULL
  AND task_has_permission(t.id, $2::text, 'task_assignment', 'update')
`

type TaskProjectForAssigneeChangeParams struct {
	TaskID  string
	ActorID string
}

func (q *Queries) TaskProjectForAssigneeChange(ctx context.Context, arg TaskProjectForAssigneeChangeParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, taskProjectForAssigneeChange, arg.TaskID, arg.ActorID)
	var project_id pgtype.Text
	err := row.Scan(&project_id)
	return project_id, err
}
