// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: todo_lists.query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTodoList = `-- name: GetTodoList :one
SELECT id, user_id, list_date, created_at, updated_at
FROM todo_lists
WHERE id = $1
`

func (q *Queries) GetTodoList(ctx context.Context, id string) (TodoList, error) {
	row := q.db.QueryRow(ctx, getTodoList, id)
	var i TodoList
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ListDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTodoListByUserIDAndDate = `-- name: GetTodoListByUserIDAndDate :one
SELECT id, user_id, list_date, created_at, updated_at
FROM todo_lists
WHERE user_id = $1
  AND list_date = $2
`

type GetTodoListByUserIDAndDateParams struct {
	UserID   string
	ListDate pgtype.Date
}

func (q *Queries) GetTodoListByUserIDAndDate(ctx context.Context, arg GetTodoListByUserIDAndDateParams) (TodoList, error) {
	row := q.db.QueryRow(ctx, getTodoListByUserIDAndDate, arg.UserID, arg.ListDate)
	var i TodoList
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ListDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTodoListItems = `-- name: ListTodoListItems :many
SELECT todo_list_id, todo_item_id, position, created_at
FROM todo_list_items
WHERE todo_list_id = $1
ORDER BY position ASC
`

func (q *Queries) ListTodoListItems(ctx context.Context, todoListID string) ([]TodoListItem, error) {
	rows, err := q.db.Query(ctx, listTodoListItems, todoListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoListItem
	for rows.Next() {
		var i TodoListItem
		if err := rows.Scan(
			&i.TodoListID,
			&i.TodoItemID,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoListSchedules = `-- name: ListTodoListSchedules :many
SELECT tls.todo_list_id, tls.schedule_id, tls.created_at
FROM todo_list_schedules AS tls
JOIN schedules AS s ON s.id = tls.schedule_id
WHERE tls.todo_list_id = $1
ORDER BY s.start_at ASC
`

func (q *Queries) ListTodoListSchedules(ctx context.Context, todoListID string) ([]TodoListSchedule, error) {
	rows, err := q.db.Query(ctx, listTodoListSchedules, todoListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoListSchedule
	for rows.Next() {
		var i TodoListSchedule
		if err := rows.Scan(&i.TodoListID, &i.ScheduleID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoListsByUserID = `-- name: ListTodoListsByUserID :many
SELECT id, user_id, list_date, created_at, updated_at
FROM todo_lists
WHERE user_id = $1
ORDER BY list_date DESC
`

func (q *Queries) ListTodoListsByUserID(ctx context.Context, userID string) ([]TodoList, error) {
	rows, err := q.db.Query(ctx, listTodoListsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoList
	for rows.Next() {
		var i TodoList
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ListDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
