// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todo_lists.mut.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTodoListItem = `-- name: AddTodoListItem :one
INSERT INTO todo_list_items (todo_list_id, action_item_id, position)
VALUES ($1, $2, $3)
RETURNING todo_list_id, action_item_id, position, created_at
`

type AddTodoListItemParams struct {
	TodoListID   string
	ActionItemID string
	Position     int32
}

func (q *Queries) AddTodoListItem(ctx context.Context, arg AddTodoListItemParams) (TodoListItem, error) {
	row := q.db.QueryRow(ctx, addTodoListItem, arg.TodoListID, arg.ActionItemID, arg.Position)
	var i TodoListItem
	err := row.Scan(
		&i.TodoListID,
		&i.ActionItemID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const addTodoListSchedule = `-- name: AddTodoListSchedule :one
INSERT INTO todo_list_schedules (todo_list_id, schedule_id)
VALUES ($1, $2)
RETURNING todo_list_id, schedule_id, created_at
`

type AddTodoListScheduleParams struct {
	TodoListID string
	ScheduleID string
}

func (q *Queries) AddTodoListSchedule(ctx context.Context, arg AddTodoListScheduleParams) (TodoListSchedule, error) {
	row := q.db.QueryRow(ctx, addTodoListSchedule, arg.TodoListID, arg.ScheduleID)
	var i TodoListSchedule
	err := row.Scan(&i.TodoListID, &i.ScheduleID, &i.CreatedAt)
	return i, err
}

const createTodoList = `-- name: CreateTodoList :one
INSERT INTO todo_lists (id, user_id, list_date)
VALUES ($1, $2, $3)
RETURNING id, user_id, list_date, created_at, updated_at
`

type CreateTodoListParams struct {
	ID       string
	UserID   string
	ListDate pgtype.Date
}

func (q *Queries) CreateTodoList(ctx context.Context, arg CreateTodoListParams) (TodoList, error) {
	row := q.db.QueryRow(ctx, createTodoList, arg.ID, arg.UserID, arg.ListDate)
	var i TodoList
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ListDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTodoList = `-- name: DeleteTodoList :exec
DELETE FROM todo_lists
WHERE id = $1
`

func (q *Queries) DeleteTodoList(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTodoList, id)
	return err
}

const removeTodoListItem = `-- name: RemoveTodoListItem :exec
DELETE FROM todo_list_items
WHERE todo_list_id = $1
  AND action_item_id = $2
`

type RemoveTodoListItemParams struct {
	TodoListID   string
	ActionItemID string
}

func (q *Queries) RemoveTodoListItem(ctx context.Context, arg RemoveTodoListItemParams) error {
	_, err := q.db.Exec(ctx, removeTodoListItem, arg.TodoListID, arg.ActionItemID)
	return err
}

const removeTodoListSchedule = `-- name: RemoveTodoListSchedule :exec
DELETE FROM todo_list_schedules
WHERE todo_list_id = $1
  AND schedule_id = $2
`

type RemoveTodoListScheduleParams struct {
	TodoListID string
	ScheduleID string
}

func (q *Queries) RemoveTodoListSchedule(ctx context.Context, arg RemoveTodoListScheduleParams) error {
	_, err := q.db.Exec(ctx, removeTodoListSchedule, arg.TodoListID, arg.ScheduleID)
	return err
}

const updateTodoListItemPosition = `-- name: UpdateTodoListItemPosition :one
UPDATE todo_list_items
SET position = $3
WHERE todo_list_id = $1
  AND action_item_id = $2
RETURNING todo_list_id, action_item_id, position, created_at
`

type UpdateTodoListItemPositionParams struct {
	TodoListID   string
	ActionItemID string
	Position     int32
}

func (q *Queries) UpdateTodoListItemPosition(ctx context.Context, arg UpdateTodoListItemPositionParams) (TodoListItem, error) {
	row := q.db.QueryRow(ctx, updateTodoListItemPosition, arg.TodoListID, arg.ActionItemID, arg.Position)
	var i TodoListItem
	err := row.Scan(
		&i.TodoListID,
		&i.ActionItemID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
