// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.query.sql

package sqlc

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, first_name, last_name, email, password, created_at, updated_at, timezone
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, email, password, created_at, updated_at, timezone
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
	)
	return i, err
}

const getUserTimezone = `-- name: GetUserTimezone :one
SELECT timezone
FROM users
WHERE id = $1
`

func (q *Queries) GetUserTimezone(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getUserTimezone, id)
	var timezone string
	err := row.Scan(&timezone)
	return timezone, err
}
